### ISSUE TITLE
Certain snippets don't work properly with fci-mode enabled.

### ISSUE THREAD

**Issue by jimeh** [capitaomorte/yasnippet#1]
The and `cls` snippet and similar don't work properly with `fci-mode` enabled. The generated class name that's auto-inserted by the snippet gets inserted right at the end of the snippet, so you endup with:

    class 
    
    endMyAwesomeClass

Instead of:

    class MyAwesomeClass
    
    end

Aside from that, Yasnippet now works great for me with fci-mode :)

**Comment by npostavs** [comment]
Seems to work fine now. There is a mention in https://github.com/alpaker/Fill-Column-Indicator/issues/3 about some fci-mode incompatibility being fixed, perhaps it was this one.
