### ISSUE TITLE
Newline added at end of snippets

### ISSUE THREAD

**Issue by joaotavora** [capitaomorte/yasnippet#117]
<b>What steps will reproduce the problem?</b>
Expand a snippet and a new line will be added after the snippet. It'd be nice if there was an 
option to stop this happening

<b>What version of the product are you using? On what operating system?</b>
0.6.1c Mac OS X 10.6

I've done a quick hack to stop a newline being added by replacing 
(insert template)
with
(if (string= "\n" (substring template -1 nil))
     (insert (substring template 0 -1))
   (insert template))

in yas/expand-snippet

Google Code Info:
Issue #: 115
Author: alexdul...@gmail.com
Created On: 2009-11-20T22:41:18.000Z
Closed On: 2009-11-26T09:48:16.000Z

**Comment by NightMachinary** [comment]
@joaotavora Is there a way to move the cursor down without inserting a newline? (Of course, this is impossible to do when at the end of the file, but that special case can be just ignored.)

Another question: Is it possible to limit a snippet to be expanded only in comments?
