### ISSUE TITLE
compressed source bundle - such as zip or jar - also avoid unicode characters on filesystem,

### ISSUE THREAD

**Issue by capitaomorte** [capitaomorte/yasnippet#119]
<b>What steps will reproduce the problem?</b>
1. untar ya-snippet source
2. examine snippet directories.

<b>What is the expected output? What do you see instead?</b>
N/A

<b>What version of the product are you using? On what operating system?</b>
Emacs 23 on Ubuntu Linux

<b>Please provide any additional information below.</b>

It would be great if when specifying yas/root-directory, you could point it
at a zip file containing the snippet tree, rather than the expanded directory.

so something like this might work:
(setq yas/root-directory 
("~/my-snippets/" 
"/usr/share/shared-yasnippets.zip" 
"/usr/local/site-lisp/yasnippet-0.6.1b/bundle-snippets.zip"))

You could cache snippets in memory based on mode/first use. Or unzip parts
of the bundle to /tmp or TMPDIR based on mode/first use.

Google Code Info:
Issue #: 117
Author: tim.ocal...@gmail.com
Created On: 2009-12-08T12:30:28.000Z
Closed On:

**Comment by npostavs** [comment]
I'm closing, as the use cases for this are covered by compiling snippets (the resulting `.compiled-snippets.el` avoids special characters in filenames and may be compressed), and the file name is no longer coupled to the snippet's name or key.
