### ISSUE TITLE
[Question] How not to be shown a list of candidates when a single snippet has been found?

### ISSUE THREAD

**Issue by rodrigo-morales-1** [capitaomorte/yasnippet#1199]
I am using the default value of `yas-prompt-functions` which is `(yas-dropdown-prompt yas-completing-prompt yas-maybe-ido-prompt yas-no-prompt)`. 

Whenever I insert a snippet, the prompt `Choose a snippet` is shown in the minibuffer. This prompt is shown even when the inserted keys correspond to a single snippet, this is redundant.

A workaround to that problem is setting `(setq yas-prompt-functions '(yas-no-prompt))`. However, this causes `yas-insert-snippet` to insert a snippet immediately (i.e. it doesn't show the completion list anymore.) I sometimes want to insert snippets through `yas-insert-snippet`, but at the same time I want that the completion list not to be shown when there's a single candidate. How to accomplish this behavior?

# System information

* yasnippet.el version: 0.14.1
* Emacs version: GNU Emacs 29.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)

**Comment by karta0807913** [comment]
did you try the function `yas-expand`? I think this function won't show the list by default.

**Comment by monnier** [comment]
> I investigated more on this and I think I have found the root cause:
> Snippets that belong to the directory `fundamental-mode` are found
> twice.  It seems that this issue has been fixed in
> e23a80177a9c434174ed8a5955c296d7828a1060 so I just need to update.

Thanks for tracking it down.  If the update doesn't fix your problem,
let us know.

**Comment by monnier** [comment]
> Updating solved the problem.

Thanks for the confirmation!
