### ISSUE TITLE
`search-backward` and friends in embedded elisp aren't predictable

### ISSUE THREAD

**Issue by capitaomorte** [capitaomorte/yasnippet#141]
When I try to generate output based on existence of some string within
buffer, it fails.

Check following snippet:

```
# -*- mode: snippet -*-
# name: search test
# --
`(save-excursion
  (if (search-backward "SEARCHEDSTRING" nil t 1)
  "YES"
  "NO"))`.$1
```

I expect output "YES" if "SEARCHEDSTRING" appears in buffer text and
otherwise output "NO". It always outputs "YES"

Version I'm using is 0.6.1c

Problem lies in yas/replace-backquotes function.
It starts with snippet content inserted into buffer. It evaluates as follows:
- parse lisp code
- evaluate lisp code
- remove snippet lisp code from buffer

It will work if order would be:
- parse lisp code
- remove snippet lisp code from buffer
- evaluate lisp code

I updated this function on my side and it works properly. Updated version:

```lisp
(defun yas/replace-backquotes ()
	"Replace all the \"`(lisp-expression)`\"-style expression
	with their evaluated value"
	(while (re-search-forward yas/backquote-lisp-expression-regexp nil t)
		(let ((current-string (match-string 1)) transformed)
			(delete-region (match-beginning 0) (match-end 0))
			(setq transformed (yas/read-and-eval-string (yas/restore-escapes
current-string)))
			(goto-char (match-beginning 0))
			(when transformed (insert transformed)))))
```

Google Code Info:
Issue #: 139
Author: marius...@gmail.com
Created On: 2010-05-12T10:40:42.000Z
Closed On:

**Comment by capitaomorte** [comment]
Heads up @npostavs : the problem reported by @gabrielelanaro is *not* the original problem, which tries to search in the *buffer*, not `yas-text` to make decisions in embedded elisp. That's where things become upredictable.

**Comment by npostavs** [comment]
I actually can't reproduce the original problem now. It seems the proposal in the OP

> It will work if order would be:
- parse lisp code
- remove snippet lisp code from buffer
- evaluate lisp code

was in fact implemented by 2ccd85a7262b71a3567e4910cdd7216dc1ecc6d2.

**Comment by capitaomorte** [comment]
@npostavs: the issue still stands afaik, searching the expansion buffer from embedded elisp is unpredictable: we don't know how much of the template is there already (or not yet). Not sure if this was the original report or not.

**Comment by npostavs** [comment]
Well I think #688 should take care of most of the remaining problem cases, but I suppose fully solving would require parsing the snippet text before inserting it. That's what the snippet-engine branch is going to do, right?

**Comment by capitaomorte** [comment]
> That's what the snippet-engine branch is going to do, right?

Hmm, yes, among other things. 

Good call then.
