### ISSUE TITLE
Insertion for new created file fails

### ISSUE THREAD

**Issue by capitaomorte** [capitaomorte/yasnippet#152]
<b>What steps will reproduce the problem?</b>

Use that lisp code to add default content far new created files:
```lisp
(defun cw:yasnippet:insert-snippet-new-file ()
  "Insert a default file skeleton when a new file is created.

To make this tip work, a \"header.yasnippet\" file should contain
the default file skeleton.

Note: yasnippet newerc than 650 does not work."
  (interactive)
  (when (and (buffer-file-name)
	     (not (file-exists-p (buffer-file-name)))
	     (= (point-max) 1))
    (insert "new-file-tpl")
    (yas/expand)))
 (add-hook 'yas/minor-mode-hook 'cw:yasnippet:insert-snippet-new-file)
```

<b>What is the expected output? What do you see instead?</b>

The content of "new-file-tpl" should be included in the new buffer.

Until commit 650 it works perfectly. But since commit 651 (Sun Aug 29
11:34:09 2010 +0000), a new created file buffer only contains:
```
new-file-tpl

```
with a new line after the "new-file-tpl", as if (yas/expand) does not
interpret the snippet itself.

If I move point at end of line and hit TAB, then the template is
correctly expanded.

is I missed something ?

<b>What version of the product are you using? On what operating system?</b>

Buggy since commit 651 (Sun Aug 29 11:34:09 2010 +0000) on emacs snapshot (debian sid version)

Google Code Info:
Issue #: 150
Author: sebastie...@gmail.com
Created On: 2010-10-13T08:11:12.000Z
Closed On:

**Comment by npostavs** [comment]
Closing, since the `setq` vs `setq-default` is explained in the docstring by now.
