### ISSUE TITLE
yasnippet inserts newline although the snippet does *not* contain a newline

### ISSUE THREAD

**Issue by joaotavora** [capitaomorte/yasnippet#192]
<b>What steps will reproduce the problem?</b>
1. Define ~/Library/Preferences/Aquamacs Emacs/Preferences.el to be:
   (require 'yasnippet) 
   (yas/initialize)
   (yas/load-directory "~/Library/Preferences/Aquamacs Emacs/plugins/yasnippet-0.6.1c/snippets")
2. define the following snippet (call it "bm.yasnippet"; the star \* symbolizes where the cursor ends -- note that there is no newline) 

```
# name: \bm{}{}
# key: bm
# --
\\bm{$1}*
```
1. open a .tex file and type in bm + TAB 
2. A newline is added after the snippet. This is quite inconvenient since "\bm{foo}" is typically used textstyle, so for example in "The vector \bm{x} is not the null vector". 

I read a bit about the problem (http://code.google.com/p/yasnippet/issues/detail?id=115 or http://yasnippet.googlecode.com/svn/trunk/doc/faq.html) but couldn't find a solution.

<b>What is the expected output? What do you see instead?</b>

The expected output is that the snippet (when inserted between two words) does not insert a newline. However, a newline is inserted after the closing bracket of the snippet.

<b>What version of the product are you using? On what operating system?</b>

0.6.1c + Aquamacs 2.3a [on Mac OS X 10.6.8]

<b>Please provide any additional information below.</b>

Google Code Info:
Issue #: 190
Author: marius.h...@gmail.com
Created On: 2011-09-28T16:29:40.000Z
Closed On: 2011-10-01T19:58:19.000Z

**Comment by azer** [comment]
this still happens to me, not sure why it's closed

**Comment by npostavs** [comment]
It's closed because the original reporter found that the problem was simply due to `require-final-newline` = `t`. If you have a recipe to reproduce the problem starting from `emacs -Q` please open a new issue.
