### ISSUE TITLE
Call  yas//after-snippet-exit-hook after expanding a nsippet with no fields

### ISSUE THREAD

**Issue by tomprince** [capitaomorte/yasnippet#199]
(or some other hook)
My use case is the following snippet. org-edit-special opens the SRC block in an a separate buffer in latex-mode for editing.

```
# name: diagram
# expand-env ((yas/after-exit-snippet-hook . '(org-edit-special)))
# --
#+BEGIN_SRC latex
  \begin{diagram}
    $0
  \end{diagram}
#+END_SRC
```

**Comment by npostavs** [comment]
Dup of #28.

PS: it should be `# expand-env: ((yas/after-exit-snippet-hook '(org-edit-special)))` (there was a missing `:` and extra `.`).
