### ISSUE TITLE
change yas/prompt-functions order when I call yas/insert-snippet

### ISSUE THREAD

**Issue by redguardtoo** [capitaomorte/yasnippet#256]
What steps will reproduce the problem?
1. (require 'dropdown-list)
2.  M-x yas/insert-snippet
3.  You can see here only limited candidates are displayed in yas/dropdown-prompt if candidate window height is bigger than the screen height
4. I this case I think yas/completing-prompt is better

My suggestion:
Use yas/completing-prompt when and ONLY when I call yas/insert-snippet.

Any work around could be found without changing yasnippet code?

yasnippet 0.7.0

**Comment by chenyangguang** [comment]
niubility
