### ISSUE TITLE
Emacs Lisp based Texmate snippet import

### ISSUE THREAD

**Issue by mattfidler** [capitaomorte/yasnippet#260]
Instead of using ruby to import textmate snippets, I propose using lisp.

Currently, this adds new functionality to yasnippet since it supports Texmate style replacements.

https://github.com/mlf176f2/textmate-to-yas.el

There are some current limitations:
* `yas/define-menu` is not implemented.
* It does not support binary plists.

This is in response to issue #232.  Issues have also been created here https://github.com/mlf176f2/textmate-to-yas.el/issues

**Comment by npostavs** [comment]
Uh, why is this labled "feature request"? I don't see anything being requested.

Is there any need to keep this open?

---
(I have no clue what a binary plist is).

**Comment by mattfidler** [comment]
Binary plists

http://hints.macworld.com/article.php?story=2005061422012079

Some textmate bundles use binary plists instead of text plists.  I was requesting that textmate bundles be imported by yasnippet without using ruby, just emacs lisp.

**Comment by npostavs** [comment]
> I was requesting that textmate bundles be imported by yasnippet without using ruby, just emacs lisp.

yasnippet doesn't do any importing, ruby or otherwise. Oh, looking at https://github.com/capitaomorte/yasnippet/issues/232#issuecomment-6613694, did you mean that we should add a reference to https://github.com/mlf176f2/textmate-to-yas.el in yasnippet's README?

**Comment by mattfidler** [comment]
It used to have a ruby tool.

At the time I wanted a link.

Its upnto you.

**Comment by npostavs** [comment]
Okay, I added a link in the README for now. Possibly we could fiddle with the submodules too.

67a45a61de49e0ae78b21753ccf15b6d02fbbe24
