### ISSUE TITLE
yas/visit-snippet-file is not working - prompt never registers what is typed in

### ISSUE THREAD

**Issue by tamouse** [capitaomorte/yasnippet#266]
When I run yas/visit-snippet-file, it prompts me in the mini-buffer for the snippet, but does not accept completions, nor does it accept what I type after I press return. Instead, it bounces down to a new line. I cannot get out of this function by pressing C-g either. It shows Quit in the mini-buffer, but then shows the prompt again. I have to quit emacs to get back to a working environment.

I have version 0.7.0 as cloned from the git repo. This is running on GNUEmacs.app for the Mac (OS/X 10.5.8 Leopard) which reports version GNU Emacs 23.1.1 (i386-apple-darwin9.8.0, NS apple-appkit-949.54) of 2009-08-16 on black.local.

I have recently upgraded from the old 0.6.7 version from google code to this one at github. I may still have somethings configured incorrectly, but I did remove all the old configuration code from my .emacs file and replaced with what is documented for 0.7.0.

**Comment by npostavs** [comment]
> Also it doesn't happen on emacs 24.

@capitaomorte: do you remember what "it" means here? Did you mean that with Emacs 24 `ido-completing-read` *doesn't* fail if `ido-mode` is off? I'm thinking to remove the `(>= emacs-major-version 24)` check; IMO the user choosing not to turn on `ido-mode` means we shouldn't use it, even if we are in Emacs 24.
