### ISSUE TITLE
How to eat spaces backward before expanding?

### ISSUE THREAD

**Issue by thisirs** [capitaomorte/yasnippet#275]
Let's say I want to expand a snippet by inserting "blah" and suppose that the point is at the end of a word. I first have to type a space to separate the preceding word from the yasnippet key and then type the key blah, expand the snippet and finally remove the space introduced... Is it a better way? Tweaking  yas/key-syntaxes didn't work for me...

**Comment by npostavs** [comment]
> Let's say I want to expand a snippet [...] suppose that the point is at the end of a word. I first have to type a space to separate the preceding word from the yasnippet key and then type the key blah, expand the snippet and finally remove the space introduced... Is it a better way?

Actually, a better way is to use `yas-insert-snippet`. Then there's no need to worry about the inserting and removing the snippet key and/or spaces.
