### ISSUE TITLE
Executing lisp code after TAB

### ISSUE THREAD

**Issue by capitaomorte** [capitaomorte/yasnippet#34]
<b>What steps will reproduce the problem?</b>
<b>1.</b>
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>

I use MSF abbrevs since long for LATEX templates. I could replace it with
YASnippets (especially the compilation to one file etc.) if the elisp would
be (optionally) executed after going to the next field with TAB instead of
entering a single key.

e.g.:
```
# --
\section{${1:Name}}%
\index{${1:$(reftex-label)}}%
```
The reftex funktion takes a (depending on the files) long time to evaluate
the input $1, which makes the template useless to work with. msf abbrev
evaluates after finishing the field with tab, so the function is called once.

So my proposal would be to add some switch (or command) to have this behaviour.

Thank you

<b>What version of the product are you using? On what operating system?</b>

<b>Please provide any additional information below.</b>

 

Google Code Info:
Issue #: 31
Author: ropewalk...@gmail.com
Created On: 2008-07-18T09:53:15.000Z
Closed On:

**Comment by npostavs** [comment]
> Won't take action on this enhancement issue until further feedback

I think we've waited long enough.
