### ISSUE TITLE
When acitve snippet with a keybinding (not key), if menu poped, fall back to key active.

### ISSUE THREAD

**Issue by zw963** [capitaomorte/yasnippet#371]
If exist two snippet, with differnce name, same key and  same binding, if active snippet with a keybinding (e.g. C-c a),  pop-up a selective menu,  It seem broken `binding invoke', fall back to key invoke...

**Comment by npostavs** [comment]
Sorry, I can't work out what this means.

**Comment by zw963** [comment]
Want to add step to step process, but found github head snippets is change 
a lot than old version. ( 0.8.1)

Anyway, I will reproduce when others possible problem is reported.
