### ISSUE TITLE
BUG? Transformation upon yas-moving-away-p doesn't update the field

### ISSUE THREAD

**Issue by immerrr** [capitaomorte/yasnippet#381]
I'm getting weird results trying to do something like

```lisp

${1:$(when yas-moving-away-p (ensure-is-quoted text))}
```

Basically, nothing is replaced, but I see `ensure-is-quoted` is being executed.

It appears that [in `yas-next-field`](https://github.com/capitaomorte/yasnippet/blob/master/yasnippet.el#L3102) the transform is evaluated with `yas--eval-lisp`, but the field is never updated. Is this intentional? The doc -- slightly outdated -- [mentions `yas/moving-away-p`](http://capitaomorte.github.io/yasnippet/snippet-development.html#id22), but doesn't say anything specific about its use.

**Comment by Skrylar** [comment]
I found a fix for this posted to the newsgroup years ago here: https://groups.google.com/forum/#!topic/smart-snippet/HEJ5JLIXhp8

Had to update it to use the newer namespaces but it mostly works.  I'll toss a patch up on github when I've made sure it updates other mirrors correctly and have access to my github box again.

**Comment by capitaomorte** [comment]
@Skrylar, just a heads up, you can of course propose such a thing in a pull request, but I doubt I'll merge it without some thorough reviewing of its implications. I've only very briefly skimmed the patch you make mention to, and I would rather prefer to revive the effort that is connecting yasnippet to the new `snippet-engine` branch, and work from there. But open the new pull request and I'll have a better look there.

**Comment by npostavs** [comment]
> It appears that in yas-next-field the transform is evaluated with yas--eval-lisp, but the field is never updated. Is this intentional?

Looks like a simple bug to me, will be fixed in #689.

The rest of this thread started to branch out a lot and got kind of confusing, if anyone wants to follow up on something here, I suggest opening a new issue.
