### ISSUE TITLE
Yasnippet Elisp environment broken when expanding snippets

### ISSUE THREAD

**Issue by nickpascucci** [capitaomorte/yasnippet#401]
When expanding snippets I'm consistently getting elisp errors using the latest version of Yasnippet from MELPA (20130829.1020). For a simple example:

1) Eval the following in a clean Emacs instance:
```(require 'yasnippet)
(require 's)

``````
2) Add this snippet to the Java mode snippet collection:
```# -*- mode: snippet -*-
# name: local-variable-declare
# key: dlv
# --
private final $1 ${1:$(s-lower-camel-case text)};
``````

2) Switch to a Java mode buffer and execute _M-x yas/minor-mode_ and _M-x yas/reload-all_

3) Type _dlv_ into the buffer and hit _tab_

4) An Elisp error will show:
`private final  [yas] elisp error! Symbol's value as variable is void: text;`

This is occurring with more complex snippets as well, causing the variables in the expand environment not to be bound. I haven't been able to get a good handle on why that's happening just yet.

**Comment by rhacker** [comment]
I have the same problem with this text, do you guys know what's wrong: 

```
#snippet
const Usage = `
   Usage:
`

# error 
[yas] elisp error: Symbol's value as variable is void: Usage
```

**Comment by enzochiau** [comment]
I think you need escape for ``'. Otherwise, the content between them will be treated as Elisp
