### ISSUE TITLE
yas indent-according-to-mode having troubles with py-indent-line

### ISSUE THREAD

**Issue by offbyone** [capitaomorte/yasnippet#414]
I'm using the ELPA python-mode and yasnippet:

    python-mode        6.0.10       installed  Python major mode
    yasnippet          20131014.928 installed  Yet another snippet extension for Emacs. [github]

When I try to insert a snippet in an empty file, yas--indent-according-to-mode emits this message:

    [yas] Warning: `yas--indent-according-to-mode' having problems running py-indent-line

I modified the error message to include the VAR value in the message and got this:

    [yas] Warning: `yas--indent-according-to-mode' having problems running py-indent-line: (args-out-of-range 251 253)

This is the snippet:

    # -*- mode: snippet -*-
    # name: module
    # key: module
    # --
    """
    `(file-name-nondirectory (buffer-file-name))`
    ${1:One line Description}

    Created by ${2:Chris Rose} on `(format-time-string "%Y-%m-%d" (current-time))`.
    Copyright (c) `(format-time-string "%Y" (current-time))` ${3:Off By One Services}. All rights reserved.
    """
    import logging
    ${5:#additional stdlib imports}

    ${6:#additional imports}

    log = logging.getLogger(${4:__name__})

    $0

When this message appears, the snippet insertion hangs, for lack of a better word, and I have to `keyboard-quit` to get the snippet to appear, at which point the text is present, but the usual field editing flow doesn't happen; the text is just inserted as-is, and the point is left at (0,0)

I have attempted to run the indent functions in edebug, but when I do so the error does not manifest; the snippet appears as normal with the full editing workflow.

**Comment by npostavs** [comment]
I'm not able to reproduce this with Emacs 24.5, latest yasnippet 606b32221ca639f31f0b746fd543720ed311ec24, and python-mode [`9e115cd8e`][pmode]. Is it fixed?

[pmode]: https://gitlab.com/python-mode-devs/python-mode/commit/9e115cd8e75e4790a14974ca705826d811eadb3a
