### ISSUE TITLE
Conflict with `undo-tree` persistence undo

### ISSUE THREAD

**Issue by tungd** [capitaomorte/yasnippet#478]
I use `undo-tree` and `undo-tree-auto-save-history` to have `buffer-undo-list` saved to a file and loaded back when the file is reopened. If any snippets is expanded in the buffer, the history file will become unusable.

I did some analysis on this, the problem is when yasnippet expand, it push an action to the `buffer-undo-list` with:

``` lisp
(push `(apply yas--take-care-of-redo ,start ,end ,snippet)
      buffer-undo-list))
```

Undo-tree then just blindly `print` the value of `buffer-undo-list` to the history file. However, the snippet struct contains markers and overlays which do not have read syntax, hence undo-tree was unable to `read` back the history. I think the issue can be fixed by changing the parameters passed to `yas--take-care-of-redo` or having a custom way to serialize/unserialize snippet struct, however I'm not good enough at Emacs LISP to fix this.

Example of undo-tree's history file: http://pastebin.com/LwC1uKyf

**Comment by fikovnik** [comment]
I really like both packages, is there any solution to this? I get hit by this fairly often.

**Comment by npostavs** [comment]
Actually, it looks like the only unreadable objects in the undo list are the leftover markers and overlays that we don't really need to save anyway, see if the patch in #804 helps.

**Comment by fikovnik** [comment]
Maybe I have a different problem, but I still see corrupted undo:

```
(set|q-default ...)
```

hit tab

```
 ((set |)q-default ...)
```

undo

```
 set| (q-default ...)
```

where the `|` indicates cursor.

**Comment by tsc25** [comment]
On 13/04/2017 13:16, Noam Postavsky wrote:
> Actually, it looks like the only unreadable objects in the undo list are
> the leftover markers and overlays that we don't really need to save
> anyway, see if the patch in #804
> <https://github.com/joaotavora/yasnippet/pull/804> helps.

Note that standard markers/overlay undo entries in the undo history 
are/should already be handled gracefully by undo-tree. By which I mean 
entries of the form (see Elisp manual, Undo section):

   (marker . adjustment)

If you mean yasnippet adds actual marker/overlay objects to the undo 
history then yes, that would generate unreadable undo history when 
serialised to file.

A generic solution would be to either serialise or delete all 
non-readable undo entries from the undo history written to file. As I 
wrote 3 years ago upthread, undo-tree already maps a cleanup function 
over the tree before writing to file, so this is not a difficult change.

If it would help yasnippet, I'd be happy to add a couple of hooks to 
undo-tree that get called on undo entries before writing to file, to 
make it easy to add custom deletion/serialisation functions for 
yasnippet-specific undo entries.

Best,
Toby
-- 
Dr T. S. Cubitt
Royal Society University Research Fellow
Quantum Information Theory
Department of Computer Science
University College London

email: tsc25@cantab.net
web:   www.dr-qubit.org

**Comment by tsc25** [comment]
On 13/04/2017 14:29, Toby Cubitt wrote:
> A generic solution would be to either serialise or delete all
> non-readable undo entries from the undo history written to file. As I
> wrote 3 years ago upthread, undo-tree already maps a cleanup function
> over the tree before writing to file, so this is not a difficult change.

...by which I mean it wouldn't be difficult to map custom 
serialisation/deletion functions over the undo tree before writing to 
file, to make the history readable. Equally easy to map custom 
deserialisation functions over the undo tree when reading from file, to 
restore custom undo entries. Happy to add hooks for this to undo-tree if 
helpful.

I didn't mean *writing* those serialisation/deserialisation functions 
would be easy. Sorry if that wasn't clear from my reply, above! I have 
no idea how difficult these would be to write for the custom yasnippet 
undo entries, and I'd completely understand if Noam doesn't feel this is 
important enough to write himself.

After all, if you're using yasnippet without undo-tree, you can't save 
undo history to file as Emacs doesn't provide that feature. Any other 
3rd-party packages that implement persistent undo history will suffer 
from the same compatibility issue as undo-tree. And yasnippet works fine 
with undo-tree except for the persistent history feature, which can be 
toggled off.

Best,
Toby
-- 
Dr T. S. Cubitt
Royal Society University Research Fellow
Quantum Information Theory
Department of Computer Science
University College London

email: tsc25@cantab.net
web:   www.dr-qubit.org

**Comment by fikovnik** [comment]
> And yasnippet works fine with undo-tree except for the persistent history feature, which can be
toggled off.

Is my issue above related to persistent history feature? I guess I do not have something configured properly, but to me it seems that they do not work together.

**Comment by npostavs** [comment]
@fikovnik that sounds like a completely different issue, this one is about errors when running `undo-tree-save-history` (or when doing that automatically by setting `undo-tree-auto-save-history`). Please open a new issue with exact instructions to reproduce your problem starting from [`emacs -Q`][emacs-Q], including versions of Emacs, yasnippet, and undo-tree.

[emacs-Q]: http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html.

---

@tsc25 wrote:
> If you mean yasnippet adds actual marker/overlay objects to the undo history

Yeah, it adds snippet structs which contain marker and overlay objects.

> If it would help yasnippet, I'd be happy to add a couple of hooks to undo-tree that get called on undo entries before writing to file, to make it easy to add custom deletion/serialisation functions for yasnippet-specific undo entries.

Thanks, but I think there's no need, at the end of snippet interaction we make the markers and overlays in question point nowhere so we might as well just get rid of them then too. Which will incidentally fix this serialization issue (unless we serialize in the middle of expanding a snippet(?), but hopefully that should be rare enough not to matter).

**Comment by npostavs** [comment]
>> If it would help yasnippet, I'd be happy to add a couple of hooks to undo-tree that get called on undo entries before writing to file, to make it easy to add custom deletion/serialisation functions for yasnippet-specific undo entries.
> 
> Thanks, but I think there's no need,

No pressing need for yasnippet that is, but a question on stack exchange recently popped up which suggests to me that these hooks would be useful regardless: https://emacs.stackexchange.com/questions/32194/undo-tree-history-file-without-text-properties

**Comment by npostavs** [comment]
> Unfortunately, I can't make my extension compatible with all other third party extensions :-(. I already strive pretty hard to make it compatible with Emacs :-)

For the record, I'd like to make clear that my policy is a bit different: I want to make yasnippet compatible at least with all GNU ELPA extensions, like undo-tree. I think #804 should have fixed this bug, and I will try to address any reports showing otherwise.
