### ISSUE TITLE
Re-Document `.yas-ignore-filenames-as-triggers` or remove filenames as triggers altogether

### ISSUE THREAD

**Issue by jfeltz** [capitaomorte/yasnippet#490]
Can you please document the hidden, non-obvious, and unreported behavior that causes yas-snippet to ignore snippets defined with keywords of file-names?

This would have saved me lots of time, and is in general a crappy thing to do to your users otherwise. Thanks.

**Comment by guraltsev** [comment]
Wait, but how do you disable using filenames as triggers. I want to author a snippet that does not have a trigger (only a name that I can insert explicitly via =yas-insert-snippet=). My yasnippet always tries to use filenames as triggers.
