### ISSUE TITLE
Consider tagging a new release

### ISSUE THREAD

**Issue by ccharles** [capitaomorte/yasnippet#512]
YASnippet has a [single tagged release](https://github.com/capitaomorte/yasnippet/releases), `0.8.0`, which is over two years old.

Since MELPA [uses tags to identify stable releases](https://github.com/milkypostman/melpa#stable-packages), those of us using MELPA Stable get a very old version of YASnippet. Worse yet, it doesn't work because [this commit](https://github.com/capitaomorte/yasnippet/pull/377/commits) removing the dependency on `dropdown-list` is not included.

**Comment by 4lex1v** [comment]
Is it possible to add some release or pre-release (alpha, beta, gamma, etc...) to the project? It's been a while since `0.9.0-a`. Just to see which commit i can checkout to wait for the next milestone

**Comment by phillord** [comment]
A release would be good. 

I am currently getting a error on the emacs-25 build based on the last release, but not on trunk of yasnippet. Doesn't seem worth the effort of reporting if it has already been fixed!

**Comment by npostavs** [comment]
> It's been a while since `0.9.0-a`

I've tagged `0.9.1-snapshot` (bumped micro version due to `a` vs `alpha` confusion).

**Comment by capitaomorte** [comment]
@npostavs, perhaps we should also update the version identifiers in the yasnippet.el file (and possibly elsewhere? I hope not)

There are "Version: ", "Package-version: " headers in the yasnippet.el file and then there is also the `yas--version` variable. We could reduce this number, but more importantly, have them all consistent between themselves and the latest tag.

**Comment by npostavs** [comment]
> perhaps we should also update the version identifiers in the yasnippet.el file

yes, but merging such a change to ELPA will make a new release (correct?), so I want to finish the NEWS first.

**Comment by phillord** [comment]
Yeah, bumping the version numbers will make a new release.

**Comment by capitaomorte** [comment]
@npostavs I did that extra bit of work and i'd say the `NEWS.org` is more or less ready for a 0.9.1 release. What do you think?

**Comment by npostavs** [comment]
Yeah, I just have to check https://github.com/capitaomorte/yasnippet/compare/news...master, like I said in #650.

**Comment by npostavs** [comment]
> Yeah, I just have to check news...master,

Ok done. I also added in the changes from GNU ELPA. So we just have to add the final NEWS file, bump the version headers and we're ready to release I think.

**Comment by npostavs** [comment]
The new `0.9.1` release has now been pushed and tagged. I pushed also to GNU ELPA, I guess it should be available from there by tomorrow or so.

**Comment by capitaomorte** [comment]
Congrats, @npostavs :trumpet: :trumpet: ... (my emoji-fu is weeakk, where are the confetti?)
