### ISSUE TITLE
Suggestion: yas-insert-snippet should insert new snippet for current mode in the right folder

### ISSUE THREAD

**Issue by ghost** [capitaomorte/yasnippet#534]
First of all, I really love the plugin. I'm very new to Emacs and switching from Vim, yasnippets is awesome. However, I'm a bit struggle at the part when I use `yas-new-snippet` in for example : `ruby-mode`, a new snippet is created in the same folder of the project instead of `snippets` folder where it should be.

I'm pretty sure there would be a way to archive this, but I don't know yet. 

Thanks for reading .

**Comment by stardiviner** [comment]
maybe create a key alias to `[C-c C-c]` for `[C-c C-s]`.
