### ISSUE TITLE
Conflict [uim-mode] [latex-mode]: Prefix key C-c overshadowed.

### ISSUE THREAD

**Issue by Araeos** [capitaomorte/yasnippet#539]
# Reproduction

uim (universal input method) is required for reproduction.

> $ emacs --version
> GNU Emacs 25.0.50.2
> $ cd /tmp/
> $ git clone https://github.com/capitaomorte/yasnippet.git yasnippet-bug
> $ cd yasnippet-bug
> $ git log -1 --oneline
> 50ca8d3 Update README.mdown

Copy this custom snippet (notice the binding) in /tmp/yasnippet-bug/yasnippets/latex-mode/jd

    # -*- mode: snippet; require-final-newline: nil -*-
    # name: latex \jdash
    # key: jd
    # binding: C-c d
    # --
    \\jdash 

Then executing this (in this order at least) yields the overshadowing of many keybindings.

> $ HOME=$PWD emacs -L .

    (latex-mode)
    (require 'yasnippet)
    (yas-global-mode 1)
    (require 'uim)
    (uim-mode)
    (yas-load-directory "/tmp/yasnippet-bug/yasnippets/")

# Description

According to my little understanding uim tries to read all input using its keymap _(uim-mode keymap)_ in _minor-mode-map-alist_ in order to send some key to the uim process. In this way I can use shortcuts for uim as well as emacs keybindings like _C-c C-c_(in Auctex).

This itself works well, but combined with the mentioned yasnippet it stops working. To be exact, all key sequences with the prefix key _C-c_ stop working as if they were not defined. This includes all Auctex bindings beginning with _C-c_.

Now I gathered from the code that uim uses the _minor-mode-map-alist_ while yasnippet uses _emulation-mode-map-alists_ and since the snippet (above) uses the prefix key _C-c_ it seems to overshadow all global and minor mode key bindings.

# Observations

- I get a normal "... is undefined" error 
- Even _C-x C-c_ stops working, which I find very odd.
- When other modes are enabled, even more keys may stop working (can't remember which).
- Disabling either uim-mode or all conflicting modes (latex-mode) helps but is no real fix.
- Disabling yasnippet didn't work 
- _(add-to-list 'emulation-mode-map-alists (list (car minor-mode-map-alist)))_ seems to enable all broken keybindings by adding _((uim-mode kemap))_ in front of yasnippets alist, but then the snippet keybindings seem to stop working...

I am know this is quite specific and could very well not be a bug, but I hope this helps anyone.

**Comment by npostavs** [comment]
@Araeos is this fixed in uim-el now?
