### ISSUE TITLE
yas-minor-mode does not load snippets

### ISSUE THREAD

**Issue by PythonNut** [capitaomorte/yasnippet#544]
* Emacs `24.4.1`
* Arch Linux `Testing 12/18/14`
* Yasnippet `20141117.327`

**Steps to reproduce**

1. `emacs -Q`
2. <kbd>M-:</kbd>  <kbd>(package-initialize)</kbd> <kbd>&lt;ret&gt;</kbd>
3. Enter this in `*scratch*`:
```emacs
(add-hook 'prog-mode-hook
          '(lambda ()
             (yas-minor-mode)))
```
4. <kbd>M-x</kbd>  <kbd>eval-buffer</kbd>
5. Find a python file, however you like to open files.
6. Type <kbd>cls</kbd> and <kbd>&lt;tab&gt;</kbd>

**Expected result**
Let `|` be the point and `!` be the mark.
```python
class |class!:
```
**Actual result**
```python
    cls|
```
**Extra info**
1. Now do <kbd>M-x</kbd>  <kbd>yas-global-mode</kbd>
2. <kbd>cls</kbd> and <kbd>&lt;tab&gt;</kbd>
Result:
```python
class |class!:
```

**Comment by andreas-roehler** [comment]
May confirm the bug.
Found here "~/.emacs.d/elpa/yasnippet-0.8.0"

Updating 

(defcustom yas-snippet-dirs

with this entry seems an option.

**Comment by npostavs** [comment]
I think there is no reason to change the current behaviour.
