### ISSUE TITLE
string-match/match-string doesn't work properly

### ISSUE THREAD

**Issue by enzochiau** [capitaomorte/yasnippet#545]
I try to write a snippet with transformation like this:

    # -*- mode: snippet; require-final-newline: nil -*-
    # name: test_only
    # key: test
    # binding: direct-keybinding
    # --
    
    ${1:hello}
    
    new ${1:$(upcase yas-text)}
    
    substring ${1:$(let ((s (substring-no-properties yas-text)))
    (string-match "\\(he\\)" s) (match-string 1 s))}
    
    not transform ${2:`(let ((s "hello")) (string-match "\\(he\\)" s)
    (match-string 1 s))`}

But the line at "substring" isn't transformed properly. I got this error:

    
    hello
    
    new HELLO
    
    substring [yas] elisp error: Args out of range: "hello", 55, 56
    
    not transform he

**Comment by npostavs** [comment]
The backslashes are getting interpreted as escapes by yasnippet, doubling them up works (but that's a bad workaround because it would break if this bug is fixed).

```
# -*- mode: snippet; require-final-newline: nil -*-
# name: test_only
# key: test
# --

${1:hello}

new ${1:$(upcase yas-text)}

substring ${1:$(let ((s (substring-no-properties yas-text)))
(string-match "\\\\(he\\\\)" s) (match-string 1 s))}

not transform ${2:`(let ((s "hello")) (string-match "\\(he\\)" s)
(match-string 1 s))`}
```

**Comment by npostavs** [comment]
Actually this was noticed in https://github.com/capitaomorte/yasnippet/issues/271#issuecomment-7825342, and @capitaomorte decided not to fix it then, so I won't fix it now either, as it's probably too difficult anyway.

A better workaround would be to avoid backslashes altogether, e.g, with `rx` or `regexp-opt`:
```
# -*- mode: snippet; require-final-newline: nil -*-
# name: test_only
# key: test
# --

${1:hello}

new ${1:$(upcase yas-text)}

regexp-opt: substring ${1:$(let ((s (substring-no-properties yas-text)))
(string-match (regexp-opt '("he") t) s) (match-string 1 s))}

rx: substring ${1:$(let ((s (substring-no-properties yas-text)))
(string-match (rx (group "he")) s) (match-string 1 s))}

not transform ${2:`(let ((s "hello")) (string-match "\\(he\\)" s)
(match-string 1 s))`}
```
