### ISSUE TITLE
Start passing NOMESSAGE to load at low verbosity levels

### ISSUE THREAD

**Issue by PythonNut** [capitaomorte/yasnippet#549]
`yas-verbosity` is quite good at keeping echo area chatter down, but one area it fails to suppress is the loading of `.yas-setup.el` files.

    Loading /home/pythonnut/.emacs.d/data/snippets/fundamental-mode/.yas-setup...done

 Ideally, `yasnippet` would also suppress those messages, by passing `t` to the `NOMESSAGE` parameter of `load`.

I'm not sure when this will go into effect, but verbosity level 0 and level 1 are good candidates.

**Comment by marcinant** [comment]
:+1:

**Comment by capitaomorte** [comment]
Sorry for the delay @PythonNut this was a bit lost here.

**Comment by PythonNut** [comment]
Not a problem at all. Thank you.
