### ISSUE TITLE
different expand behaviour between 'key' and 'menu'

### ISSUE THREAD

**Issue by enzochiau** [capitaomorte/yasnippet#553]
Just try to modify `elisp` snippet for `org-mode` as below:

    # -*- mode: snippet -*-
    # name: elisp source block
    # key: src_elisp
    # group: Source
    # --
    #+BEGIN_SRC emacs-lisp :tangle yes :results ${1:none}
    $0
    #+END_SRC 

When I expand from `menu` YASnippet->org-mode->Source->src_elisp, everything works fine. The curser stop at `$1` location first then `$0`.

But when I use `TAB` right after type `src_elisp`, it expands it but the curser stops at begin of `#+BEGIN_SRC ...` and in the mini-buffer it shows `[No matches]`.

**Comment by npostavs** [comment]
Couldn't reproduce on latest `master` (6f4e4c16bc6718d39bef07d2a7349b52a084b0dd) with Emacs 24.4.1 (Windows).

What Emacs and yasnippet versions do you have? Does it happen starting from `emacs -Q`?

**Comment by enzochiau** [comment]
Just check the yasnippet version, shows (version 0.8.0beta) (21ffe4b). I still have that problem.

I am using Emacs 25.0.50.1

I can't find the SHA you mentioned in your reply.

    $ git show 6f4e4c1
    fatal: ambiguous argument '6f4e4c1': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'

**Comment by npostavs** [comment]
Oops, I let my yasnippet fork diverge a while back and totally forgot about it.

I confirm the problem shows up with 21ffe4b797e7c54f128fdf3ee205273e74f1be33, with 24.4.1 as well.

**Comment by npostavs** [comment]
Hmm, actually I don't think I'm seeing the problem. I added a new src_elisp snippet instead of replacing the existing elisp one. But now that I got rid of the elisp one it seems to work fine.

Tested with `emacs -Q -l check-553.el` then hit `<tab>`, where check-553.el contains:

```elisp
(add-to-list 'load-path "~/src/yasnippet/")
(require 'yasnippet)
(yas-global-mode +1)
(switch-to-buffer (get-buffer-create "foo.org"))
(org-mode)
(insert "src_elisp")
```

yasnippet 21ffe4b797e7c54f128fdf3ee205273e74f1be33, Emacs 24.4.1

**Comment by npostavs** [comment]
Works also with Emacs 25.0.50.1, emacs-mirror/emacs@20c6b227ea69b9cd47f92d1a7e0935312e8ce83c

This is probably caused by your config. Or else it was a bug in the particular 25.0.50.1 you were using.
