### ISSUE TITLE
I constantly get: No snippets can be inserted here!

### ISSUE THREAD

**Issue by hellofunk** [capitaomorte/yasnippet#554]
I have installed yasnippet and the clojure snippets from dnolen. I found conflicting documentation on how to install his snippets, so I have this:

(require 'yasnippet)
(yas-global-mode 1)
;dnolen's snippets:
;https://github.com/swannodette/clojure-snippets
(yas/load-directory "~/.emacs.d/hellofunk-config/clojure-yasnippets")
(setq yas-snippet-dirs '( "~/.emacs.d/hellofunk-config/clojure-yasnippets"  ))

In any case, the mode is turned on and commands are available, but nothing happens whenever I try them out. I've tried `yas-expand` when cursor is after the word `defn` onscreen, but all it does it enter a carriage return. I've tried `yas-insert-snippet` but it provides the message `No snippets can be inserted here!`

I don't know where the problem lies. Can you assist in helping me track down the cause?

**Comment by hellofunk** [comment]
some folks on #emacs suggested I try this:

`C-u M-x yas-describe-tables`

It shows an empty buffer that says `YASnippet tables by NAMEHASH` at the top, suggesting nothing was loaded?

**Comment by capitaomorte** [comment]
I advise against using `yas\load-directory` directly. **DONT** do it. Where did you read instructions that suggested that you should, btw?

The documentation at http://capitaomorte.github.io/yasnippet/snippet-organization.html tells how to set `yas-snippet-dirs`, which you have more or less followed. But you should organize your configuration lines as follows.

```elisp
(require 'yasnippet)
;; the following line foregoes all of yasnippet's bundled snippets
;; that's OK but may not be what you want.
(setq yas-snippet-dirs '( "~/.emacs.d/hellofunk-config/clojure-yasnippets" ))
;; this takes care of loading the snippets just in time
;;
(yas-global-mode 1)
```

I don't know what is in those snippets, but if they are configured correctly for `clojure-mode` or something like that, according to http://capitaomorte.github.io/yasnippet/snippet-organization.html, then it should start working.

If it doesn't, post a complete reproduction recipe with all needed data for analysis according to the guidelines explained in https://github.com/capitaomorte/yasnippet/blob/master/README.mdown#important-note-regarding-bug-reporting

**Comment by npostavs** [comment]
> ;https://github.com/swannodette/clojure-snippets
> (setq yas-snippet-dirs '( "~/.emacs.d/hellofunk-config/clojure-yasnippets" ))

The snippet files themselves must be located in a directory called `clojure-mode` and the directory *above* that one should go in `yas-snippet-dirs`.

**Comment by hellofunk** [comment]
@capitaomorte i was following the install method shown here: https://github.com/swannodette/clojure-snippets

@npostavs thanks for that pointer, that was the piece i was missing. it's all working now.

thanks everyone
