### ISSUE TITLE
Provide a way to create global snippets.

### ISSUE THREAD

**Issue by tmccombs** [capitaomorte/yasnippet#557]
I have some snippets that I would like to work in any mode (such as a copyright notice, an email, etc.) However as far as I understand a snippet is always associated with one or more modes, and the only way to make such a global snippet is to put it in some directory like global-mode or snippet and add .yas-parents files to every other mode. 

This is a pain, especially since I want to be able to use these global snippets in modes where I may not have any other snippets.

**Comment by npostavs** [comment]
Does putting it in `fundamental-mode` work?

**Comment by tmccombs** [comment]
No, putting it in fundamental-mode doesn't seem to work. Although putting it in prog-mode does work for all programming modes.  (at least for lisp-mode derived-mode-p returns nil for fundamental-mode).

**Comment by capitaomorte** [comment]
There's also `text-mode` for most other modes. Also
`yas-activate-extra-mode` can activate arbitrary "yas-only" modes
corresponding to the names of snippet subdirectories, and not necessarily
actual major-mode names, so long as you remember to have this function run
in every buffer you create, file you visit etc. There are various hooks for
this. Curiously, there is no `fundamental-mode-hook`, which would be a
natural choice for what I think are your intents. The question of lack of
globality thus leads to a design decision in emacs itself, which I don't
know how to justify right now.

On Sun, Feb 1, 2015 at 5:13 AM, Thayne McCombs <notifications@github.com>
wrote:

> No, putting it in fundamental-mode doesn't seem to work. Although putting
> it in prog-mode does work for all programming modes. (at least for
> lisp-mode derived-mode-p returns nil for fundamental-mode).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/capitaomorte/yasnippet/issues/557#issuecomment-72352085>
> .
>



-- 
João Távora

**Comment by npostavs** [comment]
> at least for lisp-mode derived-mode-p returns nil for fundamental-mode

Oh, it's because despite `(define-derived-mode prog-mode fundamental-mode "Prog"` we have

```elisp
(defmacro define-derived-mode (child parent name &optional docstring &rest body)
...
  (when (eq parent 'fundamental-mode) (setq parent nil))
```

**Comment by capitaomorte** [comment]
@npostavs that's right, there is an exception for `fundamental-mode` which is grounded on some criteria that I don't remember very well, but they should also explain why there is no `fundamental-mode-hook`.

@tmccombs I'd just like to add to my previous comment that if you do

```elisp
(add-hook 'yas-minor-mode-hook
          (lambda ()
            (yas-activate-extra-mode 'fundamental-mode)))
```

And have a `fundamental-mode` directory alongside whatever other snippet dirs you use, the behaviour you originally requested should come to life. Let us know if it doesn't.

**Comment by capitaomorte** [comment]
Provided solution should work. Meanwhile, closing

**Comment by mohsenBanan** [comment]
I have been doing the equivalent  of that with .yas-parents.
In the .yas-parents file, I have a globals.
And I always use a .yas-parents file.
What I don't like is that the order in .yas-parents is not respected.
