### ISSUE TITLE
Unable to change tigger key

### ISSUE THREAD

**Issue by QiangF** [capitaomorte/yasnippet#560]
Hi, 
Does anyone know how to change the yas-expand trigger key?
none of the following works.
(define-key yas-minor-mode-map "\t" nil)
(define-key yas-minor-mode-map [(tab)]        nil)
(define-key yas-minor-mode-map (kbd "TAB")    nil)
(define-key yas-minor-mode-map (kbd "<tab>")  nil)
I also tried all in this thread
http://stackoverflow.com/questions/14066526/unset-tab-binding-for-yasnippet
Thank you for your help.

**Comment by npostavs** [comment]
To **unbind** tab from `yas-expand` use

```elisp
(define-key yas-minor-mode-map "\t" nil)
(define-key yas-minor-mode-map [(tab)] nil)
;; or
(define-key yas-minor-mode-map (kbd "TAB") nil)
(define-key yas-minor-mode-map (kbd "<tab>") nil)
```
If you want to **change** the trigger you need to bind to something else:
```elisp
(define-key yas-minor-mode-map (kbd "C-c y") 'yas-expand)
```
