### ISSUE TITLE
Can a character be used to indicate the end of a field?

### ISSUE THREAD

**Issue by cpitclaudel** [capitaomorte/yasnippet#561]
Statements in the Coq proof assistant are terminated by dots or semicolons, so if I'm filling in a snippet like `apply $0` typing a `.` or `;` indicates that I'm done with that snippet. 

Can I configure yasnippet to recognize this pattern? As it stands if I want to type `apply a; apply b` I have to force yasnippet to exit the first snippet by using <kbd>&lt;tab></kbd> after I type `a`.

**Comment by capitaomorte** [comment]
You might have some luck with 
```
(define-key yas-keymap (kbd ".") 'yas-exit-snippet)
```

However, that will terminate snippets for all modes, not just `coq-mode`. A workaround would be to define a new function (untested)
```elisp
(defun my-yas-dot ()
  (interactive)
  (when (eq major-mode 'coq-mode) (yas-exit-snippet))
  (self-insert-command 1))
```
and then
```elisp
(define-key yas-keymap (kbd ".") 'my-yas-dot)
```

An alternative workaround would be to add a command to `coq-mode-map` (assuming it exists), that does the reciprocal: check whether a snippet expansion is in progress with the *non-API but reasonably stable* `yas--snippets-at-point`, and call `yas-exit-snippet` from it (also untested)

```elisp
(defun my-coq-dot ()
  (interactive)
  (when (yas--snippets-at-point) (yas-exit-snippet))
  (self-insert-command 1))
```
  
and then
```elisp
(define-key coq-mode-map (kbd ".") 'my-coq-dot)
```

**Comment by cpitclaudel** [comment]
This looks neat, thanks! The second solution in particular looks pretty unintrusive. Should it be `(yas-exit-snippet (car (yas--snippets-at-point)))` though?

**Comment by cpitclaudel** [comment]
Also, is there a way to check whether the current hole is the last one of the current snippet? I don't really want to be exiting if people type a dot in the middle of a snippet.

**Comment by cpitclaudel** [comment]
Ok, after some testing it works really nice. The only thing I miss now is a way to check whether the current field is the last of the current snippet (in other words, whether (next-field) would exit the current snippet). Could this be added?

**Comment by npostavs** [comment]
Ah, actually you want `yas-next-field` instead of `yas-exit-snippet`:
```
yas-next-field is an interactive compiled Lisp function in
`yasnippet.el'.

(yas-next-field &optional ARG)

Navigate to the ARGth next field.

If there's none, exit the snippet.
```

**Comment by cpitclaudel** [comment]
Hi @npostavs,

I'm not sure why this was closed; were you doing a cleanup? (and so should open a new ticket for this?)

Cheers,
Clément.

**Comment by npostavs** [comment]
I was thinking that using `yas-next-field` would satisfy your needs, but maybe I was a bit hasty in closing, as I am sort in a cleanup mindset.

So, does using `yas-next-field` work for you?

**Comment by cpitclaudel** [comment]
I don't think so; I just want to check whether the point is currently in the last snippet or not, but I don't want to move it.

**Comment by cpitclaudel** [comment]
Congratulations on becoming the new maintainer, by the way!

**Comment by npostavs** [comment]
> I don't think so; I just want to check whether the point is currently in the last snippet or not, but I don't want to move it.

Ah, so you don't want `;` to move to the next field in a snippet?

> Congratulations on becoming the new maintainer, by the way!

Thanks, though I'm not sure "congratulations" is the right word for it :p

**Comment by cpitclaudel** [comment]
> Ah, so you don't want ; to move to the next field in a snippet?

No; I want `;` to exit the snippet, if the point is currently in the last field.

**Comment by npostavs** [comment]
Okay, so I'm thinking something like this:

```elisp
(defun yas-next-field-exits-p ()
  "Return non-nil if `yas-next-field' would exit the current snippet."
  (when (overlayp yas--active-field-overlay)
    (let* ((active-field (overlay-get yas--active-field-overlay 'yas--field))
           (next-field (yas--field-next active-field)))
      ;; Skip over mirrors, because we won't stop there.
      (while (yas--mirror-p next-field)
        (setq next-field (yas--mirror-next next-field)))
      (not (yas--field-p next-field)))))

(defun my-coq-dot ()
  (interactive)
  (when (yas-next-field-exits-p) (yas-exit-snippet))
  (self-insert-command 1))
```

@capitaomorte: does that code look correct? It seemed to do the right thing when I tried it out.

**Comment by capitaomorte** [comment]
@npostavs I don't know it but above all I think it should be used in the `yas-next-field` interactive too , aside from exporting it to @cpitclaudel. So that if that logic is wrong, at least we have a single point of failure regarding snippet exiting.

On a second look, I think it should consider "active" fields. Look at `yas-next-field` and try to extract that predicate from it.

**Comment by capitaomorte** [comment]
@npostavs, sorry I wrote the above comment in a hurry and perhaps it's a bit unreadable. I just wanted to say that `yas-next-field-exists-p` (or perhaps only `yas-next-field-p`) is perfectly ok, but:

1. I think it should be reused everywhere where that logic is being applied
2. The implementation doesn't seem to take into account what `yas-next-field` currently takes into account.
3. It could be a generalized boolean, i.e. one that returns as its non-nil value the actual next field. Also useful would be to make it `yas-next-field-p (&optional n)` with `n` defaulting to 1.

**Comment by npostavs** [comment]
Oh, I see missed the `yas--field-probably-deleted-p` check.

It seems that the fields can be enumerated from the snippet struct, and also by following the `next` member of a field struct, is that correct?

**Comment by capitaomorte** [comment]
I believe the second is not true. Using the `next` slot of a `f`ield `o`r `m`irror (`fom` for short, search for it) should bring you to the next such entity, which might not be a field, but a mirror or a snippet exit instead. I'd take the enumeration approach that I use in `yas-next-field`, and hide it in the new function. The implementation can be cleaned up later.

**Comment by npostavs** [comment]
Okay, but if I follow the `next` slots of all `fom`s, then I will enumerate the fields (in addition to mirrors and snippet exit)?

**Comment by capitaomorte** [comment]
@npostavs yes. By "enumeration approach" earlier I meant using what `yas-next-field' uses though:

```lisp
(let ((active-field ...) (live-fields (remove-if #'(lambda (field)
                                     (and (not (eq field active-field))
                                          (yas--field-probably-deleted-p snippet field)))
                                 (yas--snippet-fields snippet))
```

**Comment by cpitclaudel** [comment]
Thanks. One question still: currently `yas-next-field-will-exit-p` throws an exception when called outside of a snippet. Am I correct to think that I still need to look at `(car (yas--snippets-at-point))` to check whether I'm in a snippet before calling that function?

If so, could we make it so there's a way to achieve this without depending on private YASnippet functions?

Thanks!

**Comment by npostavs** [comment]
Do you think it's enough that `yas-next-field-will-exit-p` would return `nil` when outside a snippet (I think that was my original intention as seen [above](https://github.com/joaotavora/yasnippet/issues/561#issuecomment-174610305)), or should we add a separate function to check that condition?

**Comment by cpitclaudel** [comment]
I don't think that would work too well; after calling yas-next-fiel-will-exit-p, there's a good chance that I'll call a YAS function based on the result. Depending on the function, I might run into the same issue (not being in a snippet).

Could we make a function `yas-in-snippet-p`, or something similar? Maybe one that returns the current depth (how many nested snippets we're in), where 0 would mean "not in a snippet"?

**Comment by joaotavora** [comment]
> Could we make a function yas-in-snippet-p, or something similar? Maybe one that returns the current depth (how many nested snippets we're in), where 0 would mean "not in a snippet"?

That particular meaning of 0 is wrong. Let it return the current depth (or the snippet), but `nil` for no snippet.

**Comment by cpitclaudel** [comment]
Sounds good. This would be consistent with syntax-ppss.

**Comment by npostavs** [comment]
> This would be consistent with syntax-ppss.

Is it? I seem to be getting `(= (nth 0 (syntax-ppss)) 0)` when point is outside any parens.

**Comment by cpitclaudel** [comment]
>> This would be consistent with syntax-ppss.
>
> Is it? I seem to be getting (= (nth 0 (syntax-ppss)) 0) when point is outside any parens.

The "depth in parens" one starts at 0, but the nestable comments counter returns nil outside comments IIRC.

**Comment by joaotavora** [comment]
Regardless, a "predicate" `-p` should always return a (possibly generalized) boolean. `yas-snippet-depth` would be a good name for function with the other contract. I prefer the predicate though, and I would prefer that it returns a sorted list of snippet objects, should we need to open API to that in the future. The user can then calculate the depth with a `length` call, and `(length nil)` is elegantly 0.

**Comment by cpitclaudel** [comment]
That sounds very good.  Btw, how does `yas-next-field-will-exit-p` currently behave with nested snippets?

**Comment by npostavs** [comment]
> Btw, how does `yas-next-field-will-exit-p` currently behave with nested snippets?

It works on the most recently inserted snippet, so the parent snippets will not be considered.

> returns a sorted list of snippet objects, should we need to open API to that in the future. The user can then calculate the depth with a `length` call, and `(length nil)` is elegantly 0.

So `yas--snippets-at-point` is basically doing this already, right? The only thing I'm not sure about is the "at-point" part. I notice there is an `ALL-SNIPPETS` argument, but it seems it's never used, and I can't see how there can be snippets that are not at point (although I guess if #719 is implemented then there might be).

**Comment by joaotavora** [comment]
> I notice there is an ALL-SNIPPETS argument, but it seems it's never used, and I can't see how there can be snippets that are not at point (although I guess if #719 is implemented then there might be).

Yes, and it might be useful also non-interactively, when point is temporarily out of the snippet for some reason. So you can:

1. Rename `yas--snippets-at-point` to `yas-snippets-at-point` or some other name.
2. Remove its mandatory arg, if any, but prepare to add an optional arg for the position, that when unspecified defaults to `point`. 
3. All in all, a bit like `overlays-at`, which could perhaps be the basis for the implementation (though I don't think it would quite work right now)

**Comment by npostavs** [comment]
I've tried a rename to `yas-active-snippets`, see #727.
