### ISSUE TITLE
Unwanted text alignment

### ISSUE THREAD

**Issue by xiongtx** [capitaomorte/yasnippet#563]
I'm using `yasnippet-20140617.1640`.

If I write an Org-mode template snippet like the following contrived example:

    * Title

    ***** Section
    ${2:section content}

YASnippet will automatically align the "section content" with the "S" in the word "Section". This is undesirable behavior for me. How can I turn this off?

Sorry if this is not an "issue" per se, but I'm a bit confused by this default setting.

**Comment by npostavs** [comment]
Customize `yas-indent-line`. You can also set that variable per-snippet by binding it in an `# expand-env` directive.

http://capitaomorte.github.io/yasnippet/snippet-development.html#sec-2-5

**Comment by xiongtx** [comment]
Ahh, that does it. Should have read the documentation more throughly.

Thanks!
