### ISSUE TITLE
Yasnippet not working with auto-complete-mode

### ISSUE THREAD

**Issue by hakonhagland** [capitaomorte/yasnippet#564]
I am just starting to experiment with Yasnippet, and it worked very well until I tried to combine it with auto-complete-mode. The problem is that Auto-Complete is taking over completely. For example, in `c-mode` I can type `pr` and then press `TAB` to expand a `printf` snippet, but after activating `auto-complete-mode` this does not work, but `auto-complete-mode` itself works just fine. Instead, I would like to have Yasnippet to have priority over Auto-Complete when I press the `TAB` key.

I am using Emacs 24.4 on Ubuntu 14.04, Yasnippet version: 0.8.1, and Auto-Complete version 1.5.0.

Here is minimal example

```
$ emacs -Q -l init.el t.c
```

where `init.el` is:

```
(require 'package)
(package-initialize)
(setq package-enable-at-startup nil)
(yas-global-mode 1)
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/ac-dict")
(ac-config-default)
(add-to-list 'ac-sources 'ac-source-yasnippet)
```

If I now type `pr` and then press `TAB`, I get the Auto-Complete popup menu, (whereas I would like to expand the `printf` snippet instead). If I type `M-x auto-complete-mode` to turn off `auto-complete-mode` and then type `pr` and then `TAB`, the `printf` snippet expands as expected.

Note this issue was first asked as a question on emacs.stackexchange.com. The link is here:

http://emacs.stackexchange.com/questions/9670/yasnippet-not-working-with-auto-complete-mode

**Comment by npostavs** [comment]
> Instead, I would like to have Yasnippet to have priority over Auto-Complete when I press the TAB key.

I think moving yasnippet's entry in `minor-mode-map-alist` to the front would do that, something like:

```elisp
(let ((yas-map-entry (assq 'yas-minor-mode minor-mode-map-alist)))
  (setq minor-mode-map-alist
        (cons yas-map-entry
              (delq yas-map-entry minor-mode-map-alist))))
```

You might also get the same effect by enabling (and therefore loading) yasnippet after auto-complete.

---

related: #336, #206.

**Comment by hakonhagland** [comment]
Thanks for the suggestions `npostavs`, but I tried both your suggestions and I could get none of them to work..

For example:

```batch
$ emacs -Q -l init2.el t.c
```

where `init2.el` is:

```elisp
(require 'package)
(package-initialize)
(setq package-enable-at-startup nil) 
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/ac-dict")
(ac-config-default)
(yas-global-mode 1)
(let ((yas-map-entry (assq 'yas-minor-mode minor-mode-map-alist)))
  (setq minor-mode-map-alist
        (cons yas-map-entry
              (delq yas-map-entry minor-mode-map-alist))))
```

does not work.

**Comment by npostavs** [comment]
Okay, in addition to manipulating `minor-mode-map-alist`, you also need to do:

```elisp
(setq ac-auto-start nil)
(ac-set-trigger-key "TAB")
```

**Comment by hakonhagland** [comment]
Thanks `npostavs`, this works! But, unfortunately, now `auto-complete` does not start automatically. I liked to have that feature, where the current completion candidate is updated as I type in the buffer..

**Comment by npostavs** [comment]
That would be nice, but I don't think there is anything yasnippet can do about this, so I'm closing this issue. Perhaps auto-complete authors can suggest a better solution.

**Comment by cpitclaudel** [comment]
If you're not yet too attached to autocomplete-mode, you could move to company; they work much better together (see http://stackoverflow.com/a/28510968/695591 in particular)
