### ISSUE TITLE
expanding node with snippets in org-mode leads to yasnippets loading. How to avoid it?

### ISSUE THREAD

**Issue by redguardtoo** [capitaomorte/yasnippet#565]
as title.

**Comment by capitaomorte** [comment]
Sorry @redguardtoo , I don't understand, you have to do better. Start like this.

```
~/Vendor/emacs-24.4/bin/emacs.exe -Q -L ./yasnippet/ --eval "(require 'yasnippet)" something.org
```

or maybe you meant:

```
~/Vendor/emacs-24.4/bin/emacs.exe -Q -L ./yasnippet/ --eval "(require 'yasnippet)" -f yas-global-mode something.org
```

* What is in `something.org`? 
* What do you do after running this command line? 
* What happens? 
* What did you expect should happen?

I don't understand exactly what is:

* "expand a node", well this I assume to be TAB pressed after an `org-mode` heading.
* "node with snippets", this I really don't understand

Even your expression "yasnippets loading" is ambiguous. The normal terminology is:

* *load*: load the library the .el file
* *activate*: activate the global `yas-global-mode` or a buffer local `yas-minor-mode`
* *jit-loading of snippets*: Some action triggers previously prepared snippets to be loaded from files into memory.
* *force-reloading*: via `yas-reload-all`, load snippets from all configured directories into memory.
* *expand*: A snippet expansion is triggered

**Comment by capitaomorte** [comment]
Closing until @redguardtoo provides a little more information :-)
