### ISSUE TITLE
`ruby-mode` is part of Emacs

### ISSUE THREAD

**Issue by wasamasa** [capitaomorte/yasnippet#566]
On my search for reason behind the weird behaviour of the tab key I've found this most certainly outdated oddity in the sources:

```elisp
(defvar yas--known-modes
  '(ruby-mode rst-mode markdown-mode)
  "A list of mode which is well known but not part of Emacs.")
```

```elisp
(defun yas--real-mode? (mode)
  "Try to find out if MODE is a real mode.

The MODE bound to a function (like `c-mode') is considered real
mode.  Other well known mode like `ruby-mode' which is not part of
Emacs might not bound to a function until it is loaded.  So
yasnippet keeps a list of modes like this to help the judgment."
  (or (fboundp mode)
      (find mode yas--known-modes)))
```

This just reads wrong. `ruby-mode` is part of Emacs since at least version 23. I haven't found any clear policy on the Emacs versions supported and would like a pointer or clarification regarding them.

**Comment by capitaomorte** [comment]
Yasnippet has been around since around emacs 21/22, when `ruby-mode` wasn't indeed a part of emacs. This is an artefact of that time and pluskid's implementation. Feel free to submit a pull request getting rid of `yas--known-mode` and `yas--real-mode`, which, in my searches, aren't used anywhere.

**Comment by wasamasa** [comment]
Thank you, I've overlooked that these are dead code.

So, what about the minimum supported Emacs version? Do you have a clearer policy on it than "Submit pull requests for anything odd looking"?
