### ISSUE TITLE
Deprecate "shadow" in doco

### ISSUE THREAD

**Issue by PhilHudson** [capitaomorte/yasnippet#570]
IMHO the word "shadow" has too many meanings and associations in ordinary natural-language Engligh use, some of them contradictory in this context. I'd like to suggest you favor a less ambiguous term: "override" or "replace" or something else.

**Comment by capitaomorte** [comment]
I like the term shadow as in Emacs's own:
```
list-load-path-shadows
  Command: Display a list of Emacs Lisp files that shadow other files.
```
But if you provide a proper pull request for "override" I won't object. Be sure to read CONTRIBUTING.md.

You could also have read it and provided a better description for this issue, I thought you were referring to a snippet named "doco". It took me a while to grasp doco is "documentation".

**Comment by capitaomorte** [comment]
Meanwhile, closing this issue.

**Comment by PhilHudson** [comment]
On Sun, 12 Apr 2015 at  4:44:13 pm BST, João Távora <notifications@github.com> wrote:

> You could also have read it and provided a better description for this issue, I
> thought you were referring to a snippet named "doco". It took me a while to
> grasp doco is "documentation".

I am suitably chagrined at having used a confusing term while
complaining about a confusing term. :-/ Sorry about that.

I'll do a PR.

-- 
Phil Hudson                   http://hudson-it.ddns.net
@UWascalWabbit                 PGP/GnuPG ID: 0x887DCA63
