### ISSUE TITLE
yas-snippet-dirs has some extra values

### ISSUE THREAD

**Issue by redguardtoo** [capitaomorte/yasnippet#574]
after upgrading to 0.9.0.1

yas-snippet-dirs's value becomes `("~/.emacs.d/snippets" yas-installed-snippets-dir "/home/cb/.emacs.d/elpa/haskell-mode-13.12/snippets" "/home/cb/Mail/drafts/snippets")`

`"/home/cb/.emacs.d/elpa/haskell-mode-13.12/snippets" "/home/cb/Mail/drafts/snippets"` is definitely NOT assigned by me, how this happens?

**Comment by npostavs** [comment]
`"/home/cb/.emacs.d/elpa/haskell-mode-13.12/snippets"` is from https://github.com/haskell/haskell-mode/blob/v13.12/haskell-yas.el#L61-L69

The other must be something similar. Anyway, it is definitely NOT assigned by Yasnippet, so closing,

**Comment by redguardtoo** [comment]
I understand now, but could yasnippet ignorre /home/cb/.emacs.d/elpa/haskell-mode-13.12/snippets if that directory does NOT exist?

Currently the yasnippet just throw some error message and quit.

**Comment by npostavs** [comment]
Yeah, that sounds doable, I've no time this week though.

**Comment by redguardtoo** [comment]
btw, the last item "/home/cb/Mail/drafts/snippets" is actually randomly produced, it's actually related to the file I opened in Emacs

**Comment by redguardtoo** [comment]
I figured out, it's `cake`, which wrongly set the yas-snippet-dirs

**Comment by redguardtoo** [comment]
anyway, the sanity check of yas-snippet-dirs before load and compile snippets still make sense

**Comment by npostavs** [comment]
> Currently the yasnippet just throw some error message and quit.

Actually, I'm not seeing that. I did
```elisp
(setq yas-snippet-dirs '("/foo/bar"))

(require 'yasnippet)
(yas-global-mode +1)
```
and got the following in `*Messages*`:
```
[yas] Check your `yas-snippet-dirs': /foo/bar is not a directory
[yas] Reloaded everything (snippets will load just-in-time)... (some errors, check *Messages*).
```
But yasnippet-mode does get enabled.

Please post the exact errors you see.

**Comment by redguardtoo** [comment]
I use yasnippet stable version 0.9.0.1, emacs 24.4 on Linux, the root cause is `cake`

**Comment by npostavs** [comment]
> the root cause is cake

Yes, but what I see is that yasnippet is already ignoring bad directories in `yas-snippet-dirs` (except for a warning message).

So can you expand more on what you mean by
> Currently the yasnippet just throw some error message and quit.

**Comment by redguardtoo** [comment]
The issue only happens on yasnippet 0.9.0.1, when `cake` is installed, it will insert some random values into yas-snippet-dirs (related to the current buffer). Then when I try to `yas-expand`, the yasnippet will crash and report the random directory insert by `cake` doesn't exist. That's all the information I got. Maybe it's resolved by yasnippet already in newer version, I don't know.

**Comment by capitaomorte** [comment]
> the yasnippet will crash and report the random directory insert by cake doesn't exist.

@npostavs the crash @redguardtoo might be referring to is in `yas-snippet-dirs` the function, which was introduced more or less recently and does have an `error` call when it finds something other than a string or a symbol in `yas-snippet-dirs`. I find that reasonable, but we could downgrade it to a warning like we do in `yas--load-snippet-dirs`. The two error-detection mechanisms could be merged. I don't like how `yas--load-snippet-dirs` returns an error list so that `yas-reload-all` can say that "Some errors were detected". This should be done with warnings and a resignalling "condition-case".

Alternatively, I don't view this as an error, if the user or a third party package inserts wrong *types* of values in YASnippet's internal structures, an error is in order.

@redguardtoo your should really really read https://github.com/capitaomorte/yasnippet#important-note-regarding-bug-reporting calmly and provide a better error description next time. 

@npostavs your call, including possibly just closing the issue.

**Comment by capitaomorte** [comment]
@npostavs: 5d44edb is my take on the issue. Behaviour is mostly unchanged, code is simplified I think.

**Comment by capitaomorte** [comment]
Damm those tests :-) I'll have better look later

**Comment by npostavs** [comment]
> @npostavs the crash @redguardtoo might be referring to is ... an error call when it finds something other than a string or a symbol in yas-snippet-dirs.

I'm under the impression that `cake` inserts some random *string* (specifically, whatever filename the current buffer is visiting when `cake` gets loaded) into `yas-snippet-dirs`, so it wouldn't trigger this error.

**Comment by redguardtoo** [comment]
cake insert a random path, the path doesn't exist. so yasnippet just throw
an exception and yas-expand cannot complete.

On Thu, May 21, 2015 at 11:13 PM, Noam Postavsky <notifications@github.com>
wrote:

> @npostavs <https://github.com/npostavs> the crash @redguardtoo
> <https://github.com/redguardtoo> might be referring to is ... an error
> call when it finds something other than a string or a symbol in
> yas-snippet-dirs.
>
> I'm under the impression that cake inserts some random *string*
> (specifically, whatever filename the current buffer is visiting when cake
> gets loaded) into yas-snippet-dirs, so it wouldn't trigger this error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/capitaomorte/yasnippet/issues/574#issuecomment-104273758>
> .
>



-- 
help me, help you.

**Comment by capitaomorte** [comment]
> so yasnippet just throw an exception and yas-expand cannot complete.

@redguardtoo, with the information you have provided, that is yet to prove. I invite you to provide a minimal error reproduction recipe.

**Comment by npostavs** [comment]
> a minimal error reproduction recipe.

For example, I created the following file called `check-574.el`:
```elisp
(add-to-list 'load-path "~/src/yasnippet/")
(require 'yasnippet)
(add-to-list 'yas-snippet-dirs "/non/existing/path")
(yas-global-mode +1)

(insert "fi")
(call-interactively 'yas-expand)
```
Running `emacs -Q -l check-574.el` results in the `fi` snippet successfully expanded in `*scratch*`:
```
;FIXME: 
```
With the following `*Messages*`
```
For information about GNU Emacs and the GNU system, type C-h C-a.
[yas] Discovered there was already  *code-conversion-work* in fundamental-mode
[yas] Discovered there was already  *Echo Area 0* in fundamental-mode
[yas] Discovered there was already  *Echo Area 1* in fundamental-mode
[yas] Discovered there was already  *load* in fundamental-mode
[yas] Discovered there was already *scratch* in lisp-interaction-mode
[yas] Loading for `lisp-interaction-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote c:/Users/npostavs/src/yasnippet/snippets/lisp-interaction-mode) (quote lisp-interaction-mode)))!
[yas] Loading compiled snippets from c:/Users/npostavs/src/yasnippet/snippets/lisp-interaction-mode
[yas] Loading for `emacs-lisp-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote c:/Users/npostavs/src/yasnippet/snippets/emacs-lisp-mode) (quote emacs-lisp-mode)))!
[yas] Loading compiled snippets from c:/Users/npostavs/src/yasnippet/snippets/emacs-lisp-mode
[yas] Loading for `prog-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote c:/Users/npostavs/src/yasnippet/snippets/prog-mode) (quote prog-mode)))!
[yas] Loading compiled snippets from c:/Users/npostavs/src/yasnippet/snippets/prog-mode
Loading c:/Users/npostavs/src/yasnippet/snippets/prog-mode/.yas-setup.el (source)...done
[yas] Loading for `fundamental-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote c:/Users/npostavs/src/yasnippet/snippets/fundamental-mode) (quote fundamental-mode)))!
[yas] Loading compiled snippets from c:/Users/npostavs/src/yasnippet/snippets/fundamental-mode
Loading c:/Users/npostavs/src/yasnippet/snippets/fundamental-mode/.yas-setup.el (source)...done
[yas] Prepared just-in-time loading for c:/Users/npostavs/src/yasnippet/snippets
[yas] Prepared just-in-time loading for ~/.emacs.d/snippets
[yas] Check your `yas-snippet-dirs': /non/existing/path is not a directory
[yas] Reloaded everything (snippets will load just-in-time)... (some errors, check *Messages*).
[yas] snippet expanded.
[yas] Snippet 0 exited.
```

**Comment by capitaomorte** [comment]
@npostavs, that's fine, but there's no error reproduced right? At least the "throws an error and exits" is not true

**Comment by npostavs** [comment]
> there's no error reproduced right?

Right, this is rather demonstrating my [earlier statement][1] "yasnippet is already ignoring bad directories in yas-snippet-dirs (except for a warning message)."

[1]: https://github.com/capitaomorte/yasnippet/issues/574#issuecomment-103943636

**Comment by redguardtoo** [comment]
That may be related to my earlier setup, I wrap yas-expand in my own my-yas-expand, inside that my-yas-expand, I `(require 'yasnippet) (yas-reload-all) (yas-expand)`

**Comment by capitaomorte** [comment]
@redguardtoo: frankly, don't you think you should have let us know about this "personal setup" 17 days ago when you reported the issue? I'll close this issue but keep working on the branch that simplifies this logic.

**Comment by npostavs** [comment]
> I wrap yas-expand in my own my-yas-expand, inside that my-yas-expand, I (require 'yasnippet) (yas-reload-all) (yas-expand)

You reload all the snippets every time you expand? Yikes.

**Comment by redguardtoo** [comment]
No, I just show your a simplified version of my code.
