### ISSUE TITLE
Yasnippet expansion, hippie-expand and smartparens

### ISSUE THREAD

**Issue by tuhdo** [capitaomorte/yasnippet#575]
Original issue is reported here: https://github.com/syl20bnr/spacemacs/issues/1512

It seems like `yas-hippie-try-expand` is outdated?

**Comment by npostavs** [comment]
From the description, it sounds like a smartparens bug.

**Comment by npostavs** [comment]
I've looked at some related issues, there are some contradictory reports over whether `auto-complete` is related or not. If I see a recipe to reproduce this starting from `emacs -Q` I would consider looking at it, meanwhile I'm closing.
