### ISSUE TITLE
yas-visit-snippet-file overwrites yas-prompt-functions

### ISSUE THREAD

**Issue by hpdeifel** [capitaomorte/yasnippet#576]
It just hardcodes ido for emacs >= 24, but I'd like to use another completion system like ivy-mode.

**Comment by npostavs** [comment]
Huh, so it does. Apparently it's on purpose: 503e105b3eed4c4677b999de8612351676612568 says ```yas/visit-snippet' now ignores yas/prompt-functions``, but it's not clear why...

**Comment by rootzlevel** [comment]
My speculation would be:

In contrast to `yas-insert-snippet` or `yas-expand`, `yas-visit-snippet-file` is not context (i.e buffer position) specific, because it does not insert anything. Thus, a context menu (`yas-x-prompt`, `yas-dropdown-prompt`) looks out of place.

This may be a valid reason, but the completion system for `yas-visit-snippet-file` should still be customizable.

@capitaomorte What was the real reason for this change back in 2010? :smile:

**Comment by capitaomorte** [comment]
@rootzlevel, I don't remember exactly, but your speculation seems logical. I'll remove it and do a bit of testing to see if I come across any problems, but there shouldn't be any in principle...

**Comment by npostavs** [comment]
I tried removing the `yas-prompt-functions` override and it looks to me that `yas-x-prompt` doesn't handle large lists very well, making it unsuitable as a default.

I think the solution will be to add something like
```elisp
(defcustom yas-prompt-biglist-functions
  (remq #'yas-x-prompt (remq #'yas-dropdown-prompt yas-prompt-functions)))
```
and use `yas-prompt-biglist-functions` from `yas-visit-snippet`.

> It just hardcodes ido for emacs >= 24

Yeah, the version check in `yas-ido-prompt`: `(or (>= emacs-major-version 24) ido-mode)` does look dubious, why not just `ido-mode`?

**Comment by npostavs** [comment]
> I tried removing the yas-prompt-functions override and it looks to me that yas-x-prompt doesn't handle large lists very well, making it unsuitable as a default.

But actually `yas-insert-snippet` shows the same list using `yas-x-prompt` and apparently nobody has a problem with it. So now I'm thinking I'll just remove the override.

**Comment by npostavs** [comment]
> Yeah, the version check in yas-ido-prompt: (or (>= emacs-major-version 24) ido-mode) does look dubious, why not just ido-mode?

But see ca1d083dc75dd7fcd2ff594b40ef362974281951, 7e39aa3e56a0d90ac103bd5366f2dc52342c12e9, and #266.
