### ISSUE TITLE
yasnippet + company-c-headers does not work.

### ISSUE THREAD

**Issue by Mafeuser** [capitaomorte/yasnippet#581]
Whole the problem is described at:
[1] https://github.com/randomphrase/company-c-headers/issues/6

the slides are present in:
[2] https://emacs.stackexchange.com/questions/7900/company-completion-within-yasnippet-snippet?noredirect=1#comment12441_7900

But as for me it looks on the problem with yasnippet?

As already mentioned it occurs when yasnippet is used to expand `#include<>`.

I end up with following error message when debug on error is set:

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p (34 . #<marker in no buffer>))
  yas--advance-end-maybe([cl-struct-yas--field 1 (31 . #<marker in no buffer>) (34 . #<marker in no buffer>) nil nil nil t nil] nil)
  yas--on-field-overlay-modification(#<overlay in no buffer> t 30 30 4)
  company--insert-candidate(#("<iosfwd" 0 7 (directory "/usr/lib/gcc/x86_64-redhat-lin...")))
  company-finish(#("<iosfwd" 0 7 (directory "/usr/lib/gcc/x86_64-redhat-lin...)))
  company-complete-selection()
  call-interactively(company-complete-selection nil nil)
  command-execute(company-complete-selection)
```

error occurs when the screen is in state shown on slide 4th of [2], ie:
#include >

indeed, `yas--advance-end-maybe` gets newend parameter set to nil in this state, which leads to this stacktrace.

my company/yasnippet config is:
(yas-reload-all)
(yas-global-mode 1)
(company-mode)
(setq company-backends '(company-c-headers))

versions:
emacs-version is "24.5.1"
company-20150516.1441
company-c-headers-20140930.1102
yasnippet-20150415.244

Please let me know, if I can help somehow.

regards,
Paul

**Comment by vibrys** [comment]
there is one more thing left to be checked at company-c-headers before passing this problem to yasnippet team.

What if company-c-headers completion results didn't involve opening symbols (</")?
yasnippet highlights contents ('io' on 3rd slide), which probably is the operation domain for yasnippet, while company-c-headers goes beyond that by cutting '<'  character.

regards,
vibrys

**Comment by npostavs** [comment]
> my company/yasnippet config is:

I would need more instructions. I got 
```
Company backend 'company-c-headers' could not be initialized:
Symbol's function definition is void: company-c-headers
```

But @saintaugustinus said 

> I have already found another way to solve this

Is this still an issue?
