### ISSUE TITLE
Expanding of a snippet temporarily blocks describe-variable function

### ISSUE THREAD

**Issue by mrkkrp** [capitaomorte/yasnippet#582]
The simplest way to reproduce the problem is probably by expanding something
like `defun` in `*scratch*`. Expand it, fill out name of function and
arguments. After this, the point will be in this position:

```
(defun name (a b c)
  ❚
  )
```

Now, invoke `describe-variable` either via <kbd>M-x describe-variable</kbd>
or using its keybinding <kbd>C-h k</kbd> or <kbd>F1 k</kbd>. Select any name
of variable. You will see the following message in the minibuffer:

> Wrong type argument: overlayp, nil

In `*Messages*` buffer:

> [yas] snippet expanded.
> [yas] Snippet 2 exited.
> yas--on-field-overlay-modification: Wrong type argument: overlayp, nil

A minor, but nasty bug. Note that if you change position of the point, the
error message is gone. `describe-function` seems to work OK…

Best,

— Mark

**Comment by npostavs** [comment]
Didn't happen here, what Emacs and Yasnippet versions are you using?

**Comment by mrkkrp** [comment]
Sorry, I should have tested it before posting here. Emacs 25.0.50, compiled from repo. Latest Yasnippet from melpa, 0.8.1. Now I'm testing it with `emacs -Q` and it didn't happen... So, it probably happens when Yasnippet is used with some other mode. I'll report here as soon as I know what causes the trouble.

**Comment by mrkkrp** [comment]
So, I believe it can be reproduced this way: `emacs -Q`, then evaluate the following forms:

```
(package-initialize)
(add-hook 'after-change-major-mode-hook #'fci-mode)
(yas-global-mode 1)
```

Then execute <kbd>M-x lisp-interaction-mode</kbd>, so the hook is executed, then expand `defun`, etc. The error happens because of `fill-column-indicator` package. I've lost count of bugs it introduces. I won't use it anymore. Sorry for the wasted time, I think I should close the issue.

**Comment by npostavs** [comment]
Ah, perhaps related to #1, I didn't realize `fci` stands for `fill-column-indicator` when I read that before.

**Comment by mrkkrp** [comment]
`fill-column-indicator` is extremely buggy. I can remember the following from my own experience:

* in Dired, it messes things up when you press <kbd>g</kbd>;
* when you want to send a bug report to Emacs maintainers, it shifts some lines;
* in ERC, it shifts some lines;
* in certain cases, rectangular selection (new feature in Emacs 25) is drawn in wrong places when it's enabled;
* newly discovered: it spoils Yasnippets in some ways (there are more problems with it).

I had a conversation with Emacs devs about adding built-in fill column indicator in Emacs 25, we talked about this package, and it's really ad hoc, too slow and buggy. I recommend using whitespace-mode (enabled `lines-tail` and `face` features highlight tails of lines that are longer than some limit).

Thanks for your reply!
