### ISSUE TITLE
yas--on-protection-overlay-modification: Exit the snippet first!

### ISSUE THREAD

**Issue by andreas-roehler** [capitaomorte/yasnippet#583]
Hi, 

while playing with yas-snippet again --thanks a lot BTW-- got repeatedly the error from subject. There was no other way to get rid than re-starting Emacs. 

Maybe have a less e-governing warning?

Emacs 24.5.3, ~/.emacs.d/elpa/yasnippet-0.8.0
 
Thanks,

Andreas

**Comment by npostavs** [comment]
I think this is a dup of #537, the GNU elpa version of yasnippet is unfortunately somewhat lagging.
