### ISSUE TITLE
Stepped indentation when inserting snippets in haskell-indentation-mode

### ISSUE THREAD

**Issue by eigengrau** [capitaomorte/yasnippet#584]
When using yasnippet 20150415.244 in conjuction with haskell-indentation-mode from haskell-mode 20150611.223, inserting snippets will produce stepped indentation and superfluous empty lines, i.e.:

```
x = case var of
     cond -> value
             
             otherwise -> other
```

Where the snippet definition is:

```
case ${1:x} of
    ${2:Data} -> ${4:undefined}
    ${3:Data} -> ${5:undefined}$0
```

This can be observed with and without electric-indent-mode.

Curiously, when disabling haskell-indentation-mode, the snippet is expanded without any indentation, but with extra empty lines:

```
x = case var of
cond -> value

otherwise -> other
```

I previously reported a haskell-mode [issue](https://github.com/haskell/haskell-mode/issues/719) for this. This is on Emacs 24.5 (run with `-q`).

**Comment by npostavs** [comment]
> I previously reported a haskell-mode [issue](https://github.com/haskell/haskell-mode/issues/719) for this. 

Followed up there (I think it's a case of snippet shadowing).
