### ISSUE TITLE
Disabling default snippets

### ISSUE THREAD

**Issue by gnzlbg** [capitaomorte/yasnippet#585]
I have snippets with the same key as some default ones, and when using`yas-expand` a drop down menu appears and I have to press `down` and then `Ret` to select my snippet. 

I would like that `yas-expand` expands my snippets automatically. 

I have achieved this before by manually deleting the default snippet folder, this is a very ugly workaround.

Is there a way to:
- ignore default snippets if there is a private one for the same mode with the same key?
- ignore default snippets for a given mode completely?
- ignore all default snippets?
- make the default snippets opt-in?

The point was raised [here](https://github.com/syl20bnr/spacemacs/issues/1923) that I should contribute my snippets back, but I cannot see how this would solve the problem.

**Comment by moonlite** [comment]
To ignore the default snippets just override yas-snippet-dirs. 

Either using `customize` or by adding something like this in your init.el:
```lisp
(setq-default yas-snippet-dirs '("~/.emacs.d/snippets")
```

**Comment by gnzlbg** [comment]
So I have set my snippets dir to:

**Comment by npostavs** [comment]
Is it possible spacemacs modifies `yas-snippet-dirs` after you set it?

**Comment by gnzlbg** [comment]
@npostavs maybe, I've pinged up on the issue. I'll let you know how that goes.

**Comment by LukeHoersten** [comment]
I have this same problem. I don't want to disable *all* the default snippets, just the snippets for a specific mode. Is that possible?

**Comment by npostavs** [comment]
I believe the original problem was with spacemacs and has been solved. To answer the more general queries:

> ignore default snippets if there is a private one for the same mode with the same key?

No, but if you make a snippet with the same *name*, it will override the old one.

> ignore default snippets for a given mode completely?

You can place a `.yas-skip` file in subdirectory for any snippets you'd like to skip.

> ignore all default snippets?

Remove `yas-installed-snippets-dir` from `yas-snippet-dirs` before snippet loading.
e.g.
```elisp
(with-eval-after-load 'yasnippet
  (setq yas-snippet-dirs (remq 'yas-installed-snippets-dir yas-snippet-dirs)))
```

> make the default snippets opt-in?

No, they're opt-out only.

**Comment by c02y** [comment]
> ```emacs-lisp
> (with-eval-after-load 'yasnippet
>   (setq yas-snippet-dirs (remq 'yas-installed-snippets-dir yas-snippet-dirs)))
> ```
Should be:
```emacs-lisp
(with-eval-after-load 'yasnippet
  (setq yas-snippet-dirs (remq 'yasnippet-snippets-dir yas-snippet-dirs)))
```
