### ISSUE TITLE
yas--fallback does not work properly with set-mark-command

### ISSUE THREAD

**Issue by rpglover64** [capitaomorte/yasnippet#587]
If I bind `yas-expand` to <kbd>C-SPC</kbd>, then pressing the <kbd>C-SPC</kbd> twice does not deactivate the mark (as it would if `yas-expand` weren't bound there).

**Comment by npostavs** [comment]
Seems fixable with
```diff
diff --git i/yasnippet.el w/yasnippet.el
index c456247..c5a0dd4 100644
--- i/yasnippet.el
+++ w/yasnippet.el
@@ -2230,7 +2230,7 @@ (defun yas--fallback ()
                 (beyond-yasnippet (yas--keybinding-beyond-yasnippet)))
            (yas--message 4 "Falling back to %s"  beyond-yasnippet)
            (assert (or (null beyond-yasnippet) (commandp beyond-yasnippet)))
-           (setq this-original-command beyond-yasnippet)
+           (setq this-command beyond-yasnippet)
            (when beyond-yasnippet
              (call-interactively beyond-yasnippet))))
         ((and (listp yas-fallback-behavior)
```

But I'm not sure what other implications this has. @capitaomorte thoughts?

**Comment by capitaomorte** [comment]
@npostavs, sorry for not seeing this earlier. I think that might work, but be careful of "org-mode" and stuff. Also `cua-mode`, but I don't think anyone uses that anymore.... In the long run using the "menu item `:filter` trick" might be a viable option, otherwise this is an area where emacs is truly lacking.

**Comment by npostavs** [comment]
Hmm, actually it might make sense to set `this-original-command` to `yas-expand`.

> I think that might work, but be careful of "org-mode" and stuff.

We'll see if someone complains then :)

> Also cua-mode, but I don't think anyone uses that anymore....

I don't think `cua-mode` has been deprecated so why would people stop using it?
