### ISSUE TITLE
How to implement a dynamic same expansion for times by choose 

### ISSUE THREAD

**Issue by llcc** [capitaomorte/yasnippet#590]
Hi @capitaomorte 

I would like to create a snippet like:
```
\includegraphics[width=$1\textwidth]{$2.png}
\includegraphics[width=$3\textwidth]{$4.png}
\includegraphics[width=$5\textwidth]{$6.png}
\includegraphics[width=$7\textwidth]{$8.png}
```
You can notice that all individual lines are exactly same, just several copy.
And for my situation, numbers of lines are not fixed and should be dynamic changed.
Once i input a number, lines of this number can be expanded with just one line snippet template. 
Is it possible?

**Comment by stardiviner** [comment]
@llcc This really is an interesting example, I think maybe yasnippet should add this support some kind of `[C-u]`. And it should work in your situation.

**Comment by capitaomorte** [comment]
@llcc and @stardiviner it is possible, but I don't have time to draft the example here. Look in the issues, and on google, for examples that use the `# type: command` snippet directive. Such a snippet is basically an elisp function that can do whatever you want. One of this things can be calling `yas-expand-snippet` on whatever dynamically generated string that represents a valid snippet. If you build that string from some input from the user, you've got your solution.

**Comment by stardiviner** [comment]
@capitaomorte awesome. powerful solution.
