### ISSUE TITLE
A minor cosmetic issue with popup menus

### ISSUE THREAD

**Issue by mrkkrp** [capitaomorte/yasnippet#592]
Is there any reason to add three spaces before each item to be displayed in popup menu? Here is [the code that does it](https://github.com/capitaomorte/yasnippet/blob/master/yasnippet.el#L1556). I tried really hard to understand how this may look better than non-prefixed strings, but I couldn't.

GUI popup menus always felt like a real pain to me, so I didn't use anything that uses them (except flyspell, where long lists of corrections always drove me crazy), but now they are beginning to be usable with my package [Ace Popup Menu](https://github.com/mrkkrp/ace-popup-menu). Leading spaces look really weird there.

Of course I don't know if my package will be popular, and thus leading spaces will be apparent to more people (this Yasnippet feature is rarely used after all), but I cannot see why not remove the leading spaces, because they are pretty useless anyway. Thank you.

**Comment by capitaomorte** [comment]
Sorry for the delay in answering. Your link to the source code now points to a changed file, i.e. that line does not point where it used to.

But I think I understand your issue. The spaces are there for cosmetic purposes, basically to emulate Textmate's semi-hierarchic menus. You're probably right this is a seldom-used feature, so they can probably be removed. But maybe your package could chomp them, wouldn't that work?

**Comment by mrkkrp** [comment]
@capitaomorte, I don't remember now, but I thought about that before opening the issue. My conclusion was that I do not change menu items but show them “as is”. After all, someone could have a menu where spaces matter. Also changing length of strings can complicate implementation of the menu without any real benefit (if memory serves me well). So I concluded that conceptually right place to fix it is in Yasnippet source code, not in Ace Popup Menu.

**Comment by capitaomorte** [comment]
@mrkkrp, they matter in yasnippet. Not extremely so, but they are a cosmetic improvement. My perspective is that if leading spaces hurt your packages display, then your package should remove them. I'm talking about leading spaces, not any other type.

**Comment by mrkkrp** [comment]
@capitaomorte, As I said I don't think I should do it my package. If you don't want to remove them in Yasnippet, OK. I'm closing the issue.

**Comment by capitaomorte** [comment]
> If you don't want to remove them in Yasnippet

It's not a matter of "wanting", it's that your current argument hasn't persuaded me yet. I explained why: these spaces are not useless and they appear to only hurt something that hijacks information meant purely for a graphical display (i.e. your package).

If you provide more arguments, I might be persuaded. 

Good luck with your package.

**Comment by mrkkrp** [comment]
@capitaomorte,

> It's not a matter of "wanting"

really? I don't see how this leading whitespaces are useful. Do you know that you can create sections in popup menus? IMHO, what you currently do feels like a hack. If API for popup menus provided a way to lay out hierarchic menus then everything would be OK. You would use it and I would work with this. But menus are flat in Emacs.

So, don't hack, use capabilities that are provided to you. If you need to separate things, put them in different sections. I don't remember but it seems that Yasnippet doesn't ever use popup menus to show complex hierarchical menus. So I don't see any reason in this prefixing.

My package works on the same (low) level that normal `x-popup-menu` function. Idea is that if user want to trim things, he needs to do it himself. I would consider it a bug if my package trimmed menu items that are passed to it.

If my argumentation doesn't sound reasonable, then well, do whatever you want, what can I say...

**Comment by capitaomorte** [comment]
> really? 

yes really.

> Do you know that you can create sections in popup menus?

As a matter of fact, no I didn't. 

> IMHO, what you currently do feels like a hack. 

It certainly is. A useful one though.

If you teach me how to create sections in popup menus, that certainly counts as a new argument. So feel free to either teach me here how to solve my problem without the hack or, better yet, submit a pull request.

Thanks in advance.

> If my argumentation doesn't sound reasonable, then well, do whatever you want, what can I say...

Your current argumentation sounds perfectly reasonable, if a tad bit aggressive.

**Comment by mrkkrp** [comment]
@capitaomorte, Sorry I sometimes sound "aggressive" because I'm quite emotional person, so when I want to prove something I may get a bit "attacking". This doesn't mean I have anything against you or whatever :-)

**Comment by mrkkrp** [comment]
@capitaomorte, I will try to fix it and open a pull request, I cannot say when, I'm quite busy now.

**Comment by mrkkrp** [comment]
@capitaomorte, actually you already use something like this. See doc-string of `x-popup-menu`:

> Alternatively, you can specify a menu of multiple panes with a list of the
> form (TITLE PANE1 PANE2...), where each pane is a list of form (TITLE
> ITEM1 ITEM2...). Each ITEM is normally a cons cell (STRING . VALUE); but a
> string can appear as an item--that makes a nonselectable line in the
> menu. With this form of menu, the return value is VALUE from the chosen
> item.

By sections I meant panes. Look at your code:

```emacs-lisp
(defun yas-x-prompt (prompt choices &optional display-fn)
  "Display choices in a x-window prompt."
  (when (and window-system choices)
    (or
     (x-popup-menu
      (if (fboundp 'posn-at-point)
          (let ((x-y (posn-x-y (posn-at-point (point)))))
            (list (list (+ (car x-y) 10)
                        (+ (cdr x-y) 20))
                  (selected-window)))
        t)
      `(,prompt ("title"
                 ,@(mapcar* (lambda (c d) `(,(concat "   " d) . ,c))
                            choices
                            (if display-fn (mapcar display-fn choices) choices)))))
     (keyboard-quit))))
```

You're creating popup menu with title `prompt` and signe section called
`"title"`. By default titles of panes are not displayed (although in
`ace-popup-menu` you tell the package display them), so your menu looks
like:

```
prompt
------
item1
item2
item3
…
```

Since it doesn't ever have complex structure where padding of this sort
would make sense, why to use it at all?
