### ISSUE TITLE
yas-visit-snippet-file when snippets have been compiled

### ISSUE THREAD

**Issue by zmwangx** [capitaomorte/yasnippet#597]
I guess this is more of a question. When I have compiled my snippets (thus creating `.yas-compiled-snippets.el` files), `yas-visit-snippet-file` doesn't take me to the original snippet files, but instead open up a kind of inspect-only buffer which can't be saved with `yas-load-snippet-buffer-and-close` (first, it can't guess the file; second, the compiled snippet comes with parts of my comments stripped). Is there a workaround in such a case? Or do I have to manually navigate to the snippet file, which is simply far less efficient?

**Comment by zmwangx** [comment]
I accidentally submitted the issue without filling out the description. I have updated the description.

**Comment by npostavs** [comment]
I guess it's to do with [this][1], but I'm not sure what the "purpose" is.
```elisp
(defun yas-define-snippets (mode snippets)
  (if yas--creating-compiled-snippets
      ...
                  (file                   nil) ;; omit on purpose
```

[1]: https://github.com/capitaomorte/yasnippet/blob/e8934ce816ac0f6fdfce06b7e3fabb1fe6bf1190/yasnippet.el#L1679

**Comment by capitaomorte** [comment]
@npostavs I guess my intention was that, when loading compiled snippets, you might not have access to the file anymore. If the file is still there, there's no guarantee you're visiting the snippet definition that is actually loaded in memory.

**Comment by zmwangx** [comment]
Okay fair enough, thanks for the clarification. Is it possible to have something along the line of `yas-visit-original-snippet-file`, though?

**Comment by capitaomorte** [comment]
@zmwangx, i guess, or maybe `yas-visit-snippet-file` file could warn and provide that option. Turning this into a feature request, in case someone can think about and provide a concise implementation.

**Comment by npostavs** [comment]
We would have to add some info to the snippet structure. Either extend the format of the existing `yas--template-file` field, or add a new field. Have to think about which way is better.

Should the warning be an extra "are you sure?" style prompt (potentially annoying), or just a message (potentially overlooked)?

**Comment by zmwangx** [comment]
> Should the warning be an extra "are you sure?" style prompt (potentially annoying), or just a message (potentially overlooked)?

IMHO a message is enough, assuming people who compile their snippets know what they are doing. Completing the [The `.yas-compiled-snippet.el` file](https://capitaomorte.github.io/yasnippet/snippet-organization.html#sec-6) section in docs would be a plus (currently it's labeled as TODO).

**Comment by npostavs** [comment]
> IMHO a message is enough, assuming people who compile their snippets know what they are doing.

Yeah, I'm leaning towards just a message too.

> Completing the The .yas-compiled-snippet.el file section in docs would be a plus (currently it's labeled as TODO).

Do you have some idea of what should be written there? I don't use this feature...

**Comment by zmwangx** [comment]
> Do you have some idea of what should be written there? I don't use this feature...

Just talk a little bit about compiling, e.g., `yas-compile-directory` and `yas-recompile-all`?

**Comment by capitaomorte** [comment]
@zmwangx, I think you should submit a pull request. You seem to be in in the subject matter and have a good grasp of english, and possibly use this feature more extensively than I do lately.

**Comment by zmwangx** [comment]
Would you please comment on whether there's substantial performance gain of compilation? I haven't read the source code, and even if I do I probably won't be able to tell (I'm not that into elisp). I do feel like loading snippet tables is somewhat faster after compilation, but that might as well be placebo effect on my part.

If there were no substantial gain then it might be better to just leave that part out, since it wouldn't be very useful anyway and worse still introduce other problems (like the one in this issue). Otherwise, I would be happy to oblige, but wouldn't it make more sense to complete that part of the documentation after this feature is implemented (either you guys take a shot or someone is kind enough to contribute)? As it currently stands I'm not sure if compilation is advisable or not.

**Comment by npostavs** [comment]
> I haven't read the source code, and even if I do I probably won't be able to tell (I'm not that into elisp).

I don't think reading the source would tell you that anyway. The only way to know for sure is to measure it. I *suspect* it would be faster just because the there are less files to read in the compiled case, therefore less disk I/O.

> wouldn't it make more sense to complete that part of the documentation after this feature is implemented (either you guys take a shot or someone is kind enough to contribute)? As it currently stands I'm not sure if compilation is advisable or not.

Since we're not about to remove the compilation feature regardless, it would be better if it was documented.

**Comment by zmwangx** [comment]
> I don't think reading the source would tell you that anyway.

I think there might be extra parsing involved when the snippet is user-written than auto-generated, no?

> The only way to know for sure is to measure it.

Yeah, but I don't know how to profile elisp (or just get a precise time, for that matter) :sweat: 

> less disk I/O.

Definitely, but I don't know whether that would lead to "substantial" improvement (apart from disk latency, is elisp's file IO fast)? Maybe only profiling would tell.

> it would be better if it was documented.

Good point, I'll try to submit a PR then when I have time. I don't know if there's much to say other than slightly elaborating on the docstrings of `yas-compile-directory` and `yas-recompile-all`.

**Comment by capitaomorte** [comment]
> Would you please comment 

No! no comment. I deny everything!

> on whether there's substantial performance gain of compilation? I haven't read the source code, and even if I do I probably won't be able to tell (I'm not that into elisp). I do feel like loading snippet tables is somewhat faster after compilation, but that might as well be placebo effect on my part.

Hehe just kidding. You can read a bit about the feature in #262. There I have some benchmarks

```
NO-JIT NO-COMPILED: 6.318065 s
NO-JIT    COMPILED: 3.507434 s (no recompilation-needed, no auto-compilation checks)
```

That is *without jit* but it makes no difference, because I was measuring Emacs startup times there. I would guess that that 0.5 factor would be more or less kept every time a new mode needs to jit-load snippets.

> Since we're not about to remove the compilation feature regardless, it would be better if it was documented.

Yes. Incidentally, as you suggested, the particular kind of snippet compilation that yasnippet offers now is quite, err, rubbish. You're basically saving on file open times and not much more. But the concept of compilation and its general framework should be kept. It should speed up tremendously the loading *and* the execution of snippets when the `snippet-engine` branch is merged. Using that engine, a yasnippet template definition is converted into a pure elisp function, which can be compiled and stored in bytecode. `.yas-compiled-snippets` would become a small `elc` file. 

Unfortunately, things in that branch aren't moving terribly fast. But they are moving.

**Comment by zmwangx** [comment]
> There I have some benchmarks

Not too bad from the benchmarks. However, if we are only saving on disk IO right now, then the gain is probably very minor on SSD-based filesystems?


> It should speed up tremendously the loading and the execution of snippets when the snippet-engine branch is merged. Using that engine, a yasnippet template definition is converted into a pure elisp function, which can be compiled and stored in bytecode. `.yas-compiled-snippets` would become a small `elc` file.

Given that, the documentation should probably be deferred, since it will become outdated anyway. Currently, one either doesn't compile at all, or it shouldn't be too hard to spot the compilation-related functions.

**Comment by capitaomorte** [comment]
> Not too bad from the benchmarks. However, if we are only saving on disk IO right now, then the gain is probably very minor on SSD-based filesystems?

Perhaps, I don't know. The only way to know is to measure. 

> Given that, the documentation should probably be deferred, since it will become outdated anyway. Currently, one either doesn't compile at all, or it shouldn't be too hard to spot the compilation-related functions.

No, just the opposite, I intent for the interface to stay largely the same, only the implementation details changing. So in that section I would talk of `yas-compile-directory` and that sentence would be unchanged.

**Comment by zmwangx** [comment]
Okay, I thought you were adding something more fancy. An attempt at the documentation: #599.

**Comment by npostavs** [comment]
I have an initial draft of the fix for this, it passes yasnippet-tests.el, but I haven't actually checked whether it really fixes this problem yet.

https://github.com/capitaomorte/yasnippet/compare/master...npostavs:load-save-file

**Comment by zmwangx** [comment]
@npostavs I just gave it a shot but it doesn't seem to work for me.

**Comment by npostavs** [comment]
@zmwangx Okay just tried now and it seems to work. Have you recompiled the snippets after loading the new code?

**Comment by zmwangx** [comment]
@npostavs Yeah it does work. Turns out I forgot to byte-recompile `yasnippet.el`. Sorry about that.
