### ISSUE TITLE
please bump version of submodule snippets

### ISSUE THREAD

**Issue by fommil** [capitaomorte/yasnippet#601]
the yassnippets just got a big improvement for `scala-mode`, can you please update to their `HEAD`?

**Comment by capitaomorte** [comment]
Done. But, we should discuss this process, I think the least we could do is only update the snippets submodule releases a version or something. Though version-wise yasnippet can't brag much... Well, enjoy anyway.

**Comment by cowboyd** [comment]
I agree. With this last update, I brought in some questionable changes to the javascript snippets. https://github.com/AndreaCrotti/yasnippet-snippets/issues/101

**Comment by capitaomorte** [comment]
@cowboyd, I understand, but a single line in your emacs setting `yas-snippet-dirs` will keep you on your favourite snippets, which can be any version of any repo you want.

**Comment by fommil** [comment]
And individual snippets can be overridden
