### ISSUE TITLE
different snippets for different ESS dialects

### ISSUE THREAD

**Issue by scheidan** [capitaomorte/yasnippet#602]
I'd like to define different sets of snippets for different languages that are used in [ESS](https://github.com/emacs-ess/ESS), for example for R and Julia.

The problem is that ESS runs for all languages in the same major mode `ess-mode` but uses different "dialects". Any ideas for a work-around?

Otherwise yasnippets works perfect - thanks for that!

**Comment by stardiviner** [comment]
Maybe you have to put snippets in separate directories, and prefix trigger key with corresponding dialetc. for example: Julia prefix trigger key with `j-`, and R prefix trigger key with `r-`. Do you think?

**Comment by npostavs** [comment]
> The problem is that ESS runs for all languages in the same major mode ess-mode but uses different "dialects". Any ideas for a work-around?

I think you could use the [condition system][1] for this, something like:

```elisp
(defun my-ess-mode-hook ()
  (setq yas-buffer-local-condition
        '(cons 'require-snippet-condition
               *ess-current-dialect*)))

(add-hook 'ess-mode-hook #'my-ess-mode-hook)
```

Replace `*ess-current-dialect*` with whatever elisp expression evaluates to the "dialect". Then, e.g. for R snipppets add `#condition: 'R-dialect` (replace `R-dialect` with whatever `*ess-current-dialect*` returns).

[1]: http://capitaomorte.github.io/yasnippet/snippet-expansion.html#sec-2-2

**Comment by stardiviner** [comment]
@npostavs really good idea.
