### ISSUE TITLE
`yas-expand-snippet' needs properly setup `yas-minor-mode'

### ISSUE THREAD

**Issue by map7** [capitaomorte/yasnippet#605]
I'm working with emacs version 24.3.1 on Debian Wheezy 7.8. I'm getting a yas-snippet error when trying to use magit and projectile all together.

Here is my configuration (I've slimmed it down to just the parts which are giving the error)
````
(require 'cask "~/.cask/cask.el")
(cask-initialize)

;; Yasnippet
(yas-global-mode 1)

;; Projectile
(projectile-global-mode)
(add-hook 'projectile-mode-hook 'projectile-rails-on)
````

When I make a change to my code (ruby on rails project), then go to 'magit-status' and hit 'c,c' to commit the changes this is suppose to load up a new commit window but fails with the following error message;

    yas-expand-snippet: [yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'

If I remove either of the projectile lines then yas-snippet does not complain and I can use magit to commit any changes I want. The problem then is I don't have projectile.

If the only thing I change in my configuration above is turn yas-global-mode to 0 then I get the following error

    Error in post-command-hook (projectile-global-mode-check-buffers): (error "[yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'")

**Comment by npostavs** [comment]
> When I make a change to my code (ruby on rails project), then go to 'magit-status' and hit 'c,c' to commit the changes this is suppose to load up a new commit window but fails with the following error message;

Can you enable debug-on-error and post the backtrace?

**Comment by map7** [comment]
On 08/09/15 06:37, Noam Postavsky wrote:
>     When I make a change to my code (ruby on rails project), then go to
>     'magit-status' and hit 'c,c' to commit the changes this is suppose
>     to load up a new commit window but fails with the following error
>     message;
> 
> Can you enable debug-on-error and post the backtrace?
> 

Here is the backtrace when I run the magit-commit

Debugger entered--entering a function:
* magit-commit(nil)
  call-interactively(magit-commit)
  magit-key-mode-command(magit-commit)
  (lambda nil (interactive) (magit-key-mode-command (quote magit-commit)))()
  call-interactively((lambda nil (interactive) (magit-key-mode-command
(quote magit-commit))) nil nil)

The minor modes which are on the COMMIT_EDITMSG buffer are
MRev, Rails, Projectile & yas

This is the first time I've gone through the debug process in emacs let
me know if there is more information I can give you.

**Comment by npostavs** [comment]
> Here is the backtrace when I run the magit-commit

That looks like you did `(debug-on-entry 'magit-commit)` but I was looking for the backtrace starting from the error, which you should be able to get by adding `(setq debug-on-error t)` to your configuration then triggering the error by trying to commit.

**Comment by map7** [comment]
On 08/09/15 13:02, Noam Postavsky wrote:
>     Here is the backtrace when I run the magit-commit
> 
> That looks like you did |(debug-on-entry 'magit-commit)| but I was
> looking for the backtrace starting from the error, which you should be
> able to get by adding |(setq debug-on-error t)| to your configuration
> then triggering the error by trying to commit.
> 
> —

I've now put the line in my config like so;

(require 'cask "~/.cask/cask.el")
(cask-initialize)

;; Enable debug
(setq debug-on-error t)

;; Yasnippet
(add-to-list 'load-path "~/.emacs.d/external/yasnippet")
(require 'yasnippet)
(yas-global-mode 1)

;; Projectile
(projectile-global-mode)
(add-hook 'projectile-mode-hook 'projectile-rails-on)

;; Keybinding
(global-set-key [f5] 'magit-status)


I've started emacs and used 'magit-commit', it displays the same yas
error in the status line but nothing is in the *Backtrace* buffer.

Here is what is in my *Messages*
[yas] Loading compiled snippets from
/home/map7/.emacs.d/.cask/24.3.1/elpa/angular-snippets-20140513.2223/snippets/html-mode
[yas] Loading compiled snippets from
/home/map7/.emacs.d/.cask/24.3.1/elpa/angular-snippets-20140513.2223/snippets/js-mode
[yas] Loading compiled snippets from
/home/map7/.emacs.d/.cask/24.3.1/elpa/angular-snippets-20140513.2223/snippets/js2-mode
[yas] Loading compiled snippets from
/home/map7/.emacs.d/.cask/24.3.1/elpa/angular-snippets-20140513.2223/snippets/web-mode
[yas] Loading compiled snippets from
/home/map7/.emacs.d/.cask/24.3.1/elpa/angular-snippets-20140513.2223/snippets/html-mode
[yas] Loading compiled snippets from
/home/map7/.emacs.d/.cask/24.3.1/elpa/angular-snippets-20140513.2223/snippets/js-mode
[yas] Loading compiled snippets from
/home/map7/.emacs.d/.cask/24.3.1/elpa/angular-snippets-20140513.2223/snippets/js2-mode
[yas] Loading compiled snippets from
/home/map7/.emacs.d/.cask/24.3.1/elpa/angular-snippets-20140513.2223/snippets/web-mode
[yas] Prepared just-in-time loading for
/home/map7/.emacs.d/.cask/24.3.1/elpa/angular-snippets-20140513.2223/snippets
[yas] Discovered there was already *scratch* in fundamental-mode
[yas] Discovered there was already *Messages* in fundamental-mode
[yas] Discovered there was already  *code-conversion-work* in
fundamental-mode
[yas] Discovered there was already  *load* in fundamental-mode
[yas] Discovered there was already  *Echo Area 0* in fundamental-mode
[yas] Discovered there was already  *Echo Area 1* in fundamental-mode
[yas] Discovered there was already  *code-converting-work* in
fundamental-mode
[yas] Loading for `fundamental-mode', just-in-time: (lambda nil
(yas--load-directory-1 (quote
/home/map7/.emacs.d/external/yasnippet/snippets/fundamental-mode) (quote
fundamental-mode)))!
[yas] Loading compiled snippets from
/home/map7/.emacs.d/external/yasnippet/snippets/fundamental-mode
Loading
/home/map7/.emacs.d/external/yasnippet/snippets/fundamental-mode/.yas-setup.el
(source)...done
[yas] Prepared just-in-time loading for
/home/map7/.emacs.d/external/yasnippet/snippets
[yas] Discovered there was already *scratch* in fundamental-mode
[yas] Discovered there was already *Messages* in fundamental-mode
[yas] Discovered there was already  *code-conversion-work* in
fundamental-mode
[yas] Discovered there was already  *load* in fundamental-mode
[yas] Discovered there was already  *Echo Area 0* in fundamental-mode
[yas] Discovered there was already  *Echo Area 1* in fundamental-mode
[yas] Discovered there was already  *code-converting-work* in
fundamental-mode
[yas] Loading for `fundamental-mode', just-in-time: (lambda nil
(yas--load-directory-1 (quote
/home/map7/.emacs.d/snippets/fundamental-mode) (quote fundamental-mode)))!
[yas] Loading compiled snippets from
/home/map7/.emacs.d/snippets/fundamental-mode
Loading /home/map7/.emacs.d/snippets/fundamental-mode/.yas-setup.el
(source)...done
[yas] Prepared just-in-time loading for ~/.emacs.d/snippets
[yas] Reloaded everything (snippets will load just-in-time)....
[yas] Loading for `lisp-interaction-mode', just-in-time: (lambda nil
(yas--load-directory-1 (quote
/home/map7/.emacs.d/external/yasnippet/snippets/lisp-interaction-mode)
(quote lisp-interaction-mode)))!
[yas] Loading compiled snippets from
/home/map7/.emacs.d/external/yasnippet/snippets/lisp-interaction-mode
[yas] Loading for `lisp-interaction-mode', just-in-time: (lambda nil
(yas--load-directory-1 (quote
/home/map7/.emacs.d/snippets/lisp-interaction-mode) (quote
lisp-interaction-mode)))!
[yas] Loading compiled snippets from
/home/map7/.emacs.d/snippets/lisp-interaction-mode
[yas] Loading for `emacs-lisp-mode', just-in-time: (lambda nil
(yas--load-directory-1 (quote
/home/map7/.emacs.d/external/yasnippet/snippets/emacs-lisp-mode) (quote
emacs-lisp-mode)))!
[yas] Loading compiled snippets from
/home/map7/.emacs.d/external/yasnippet/snippets/emacs-lisp-mode
[yas] Loading for `emacs-lisp-mode', just-in-time: (lambda nil
(yas--load-directory-1 (quote
/home/map7/.emacs.d/snippets/emacs-lisp-mode) (quote emacs-lisp-mode)))!
[yas] Loading compiled snippets from
/home/map7/.emacs.d/snippets/emacs-lisp-mode
[yas] Loading for `prog-mode', just-in-time: (lambda nil
(yas--load-directory-1 (quote
/home/map7/.emacs.d/external/yasnippet/snippets/prog-mode) (quote
prog-mode)))!
[yas] Loading compiled snippets from
/home/map7/.emacs.d/external/yasnippet/snippets/prog-mode
Loading
/home/map7/.emacs.d/external/yasnippet/snippets/prog-mode/.yas-setup.el
(source)...done
[yas] Loading for `prog-mode', just-in-time: (lambda nil
(yas--load-directory-1 (quote /home/map7/.emacs.d/snippets/prog-mode)
(quote prog-mode)))!
[yas] Loading compiled snippets from /home/map7/.emacs.d/snippets/prog-mode
Loading /home/map7/.emacs.d/snippets/prog-mode/.yas-setup.el (source)...done
For information about GNU Emacs and the GNU system, type C-h C-a.
[yas] Loading for `enh-ruby-mode', just-in-time: (lambda nil
(yas--load-directory-1 (quote
/home/map7/.emacs.d/external/yasnippet/snippets/enh-ruby-mode) (quote
enh-ruby-mode)))!
[yas] Loading compiled snippets from
/home/map7/.emacs.d/external/yasnippet/snippets/enh-ruby-mode
[yas] Loading for `enh-ruby-mode', just-in-time: (lambda nil
(yas--load-directory-1 (quote
/home/map7/.emacs.d/snippets/enh-ruby-mode) (quote enh-ruby-mode)))!
[yas] Loading compiled snippets from
/home/map7/.emacs.d/snippets/enh-ruby-mode
Loading vc-git...done
(No files need saving)
Type a prefix key to toggle it. Run 'actions' with their prefixes. '?'
for more help.
COMMIT_EDITMSG has auto save data; consider M-x recover-this-file
Entering debugger...
or: [yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'
Quit [2 times]
byte-code: Beginning of buffer [14 times]



*Warnings*
Warning (magit): Cannot determine a suitable Emacsclient

Determining an Emacsclient executable suitable for the
current Emacs instance failed.  For more information
please see https://github.com/magit/magit/wiki/Emacsclient.

**Comment by npostavs** [comment]
>     Entering debugger...
>     or: [yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'

Hmm, looks like the backtrace was swallowed somehow. Can you trigger the error if you just open `.git/COMMIT_EDITMSG` directly?

**Comment by map7** [comment]
.

On 09/09/15 06:20, Noam Postavsky wrote:
>     |Entering debugger... or: [yas] `yas-expand-snippet' needs properly
>     setup `yas-minor-mode' |
> 
> Hmm, looks like the backtrace was swallowed somehow. Can you trigger the
> error if you just open |.git/COMMIT_EDITMSG| directly?
> 

I get the same error message in *Messages* and nothing in *Backtrace*,
it does however open up COMMIT_EDITMSG in a background buffer. If I
select that buffer I can see that it has the minor modes Fundamental,
Rails, Projectile & yas.

**Comment by stardiviner** [comment]
I got same error when try to open a file `_form.html.erb` in Rails with `projectile-rails-find-current-view`. After I open it the second time, then the file opened successfully.

**Comment by map7** [comment]
Today I upgraded emacs from 24.3.1 to 24.4.1 and installed all my packages again using 'cask install' and the problem has gone away. I can now use Magit & yasnippet together

**Comment by Pitometsu** [comment]
Each time when I try to create new file when work in rails project with `projectile-rails`, I got the same error and `helm-mode` stuck so I can't do anything, just restart Emacs.

**Comment by Pitometsu** [comment]
Temporary workaround:
```elisp
(setq projectile-rails-expand-snippet nil)
```

**Comment by Pitometsu** [comment]
Seems like it's now fixed in `projectile-rails`.

**Comment by stardiviner** [comment]
yes, projectile-rails added nil parameter.
