### ISSUE TITLE
YASnippet fails with Flycheck

### ISSUE THREAD

**Issue by hotpxl** [capitaomorte/yasnippet#607]
Hi.

I'll put the stack trace up front. Some of the byte codes are not printable so I abbreviated them.

> ```
> Debugger entered--Lisp error: (wrong-type-argument overlayp nil)
>   overlay-get(nil yas--snippet)
>   yas--on-field-overlay-modification(#<overlay from 869 to 873 in main.cpp> t 2657 2657 68)
>   message("%s" "expected '(' for function-style cast or type construction")
>   display-message-or-buffer("expected '(' for function-style cast or type construction" "*Flycheck error messages*")
>   flycheck-display-error-messages(([cl-struct-flycheck-error #<buffer main.cpp> irony "/Users/hotpxl/tmp/has/main.cpp" 50 41 "expected '(' for function-style cast or type construction" error nil]))
>   flycheck-display-errors(([cl-struct-flycheck-error #<buffer main.cpp> irony "/Users/hotpxl/tmp/has/main.cpp" 50 41 "expected '(' for function-style cast or type construction" error nil]))
>   #[0 "\301 \210\205......
>   funcall(#[0 "\301 \210\205......
>   flycheck-display-error-at-point()
>   apply(flycheck-display-error-at-point nil)
>   byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
>   timer-event-handler([t 21998 34972 29119 nil flycheck-display-error-at-point nil nil 0])
> ```

I use YASnippet with Company mode and Flycheck. My backend will expand call signature after completion, and then I can use YASnippet to fill the blanks. But when I do, it throws this error.

1. ~~I don't know why Flycheck is calling `yas--on-field-overlay-modification`.~~ I saw that it's like an event handler that is registered, and will get called every time an event is triggered.

The "expected '(' ..." thing is an expected Clang error (not error in Clang, but in my C++ code, since it is just expanded and the syntax is just partially filled).

Anyway YASnippet it throwing such error.

1. I wonder what `yas--active-field-overlay` is and why it is nil?
1. ~~How to fix this issue?~~ I guess checking for nil would fix this issue.

**Comment by hotpxl** [comment]
FYI, the Company backend just calls `yas-expand-snippet snippet-str` while `snippet-str` is `(${1:int}, ${2:int}, ${3:long}, ${4:float}, ${5:const char *})$0` after it completes the name of the function. So the Company backend is doing nothing special.

**Comment by capitaomorte** [comment]
I wish there was a simple recipe for me to reproduce this bug so I could investigate it, otherwise itºs going to take a while until I can infer exactly what your configuration is. Can you provide it? See https://github.com/capitaomorte/yasnippet#important-note-regarding-bug-reporting for how to do so.

**Comment by hotpxl** [comment]
Hi. Sorry for the late reply. I lost track of all the issues i submitted.

i do have a emacs config file (https://github.com/hotpxl/colonise/blob/master/emacs)

i have sort of nailed down the problem. if you disable these few lines (https://github.com/hotpxl/colonise/blob/master/emacs#L144-L152), the error goes away. i guess it's when you have something like

```
function_name($YAS_0, $YAS_1, $YAS_2)
```

`$YAS_` means it's a placeholder. when you have something like that, and when you are hitting tab to jump from one placeholder to the other, the parentheses thing is also rendering the brackets, and they somehow fall into the same overlay with yasnippet, hence the bug

**Comment by hotpxl** [comment]
Sorry I wasn't able to get a minimal config file that breaks. As soon as I started deleting some of my lines, the bug does not occur at all times. I guess it's when I have plugins all having overlays and they conflict with each other somehow. What I'm sure about, is this line (https://github.com/capitaomorte/yasnippet/blob/master/yasnippet.el#L3405) where `yas--active-field-overlay` is nil (as far as the traceback shows).

**Comment by npostavs** [comment]
I don't really understand the problem, but are you saying something like the following would fix it?

```diff
diff --git i/yasnippet.el w/yasnippet.el
index 77702eb..065d030 100644
--- i/yasnippet.el
+++ w/yasnippet.el
@@ -3402,9 +3402,9 @@ (defun yas--on-field-overlay-modification (overlay after? _beg _end &optional _l
   (unless (or yas--inhibit-overlay-hooks
               (yas--undo-in-progress))
     (let* ((field (overlay-get overlay 'yas--field))
            (snippet (overlay-get yas--active-field-overlay 'yas--snippet)))
-      (cond (after?
+      (cond ((and after? snippet)
              (yas--advance-end-maybe field (overlay-end overlay))
              (save-excursion
                (yas--field-update-display field))
              (yas--update-mirrors snippet))

```

**Comment by hotpxl** [comment]
I tried and I don't think it fixes the problem. I wonder if you could reproduce the problem. On my side, it does happen deterministically, but I think the root cause might be somewhere deep. My hunch is that whenever there are too many overlays, things start clashing into each other.

**Comment by npostavs** [comment]
> I wonder if you could reproduce the problem.

I don't even see any instructions on how to reproduce it.

**Comment by hotpxl** [comment]
Sorry about the confusion. I was not aware of the proper way to describe the problem to you. I have a somewhat "minimal" Emacs [init file](https://gist.github.com/hotpxl/cfad63d5e88ed164bc76). It basically installs Company, YASnippet, Flycheck, and Irony. You have to manually `M-x irony-install-server` to install Irony.

Then you could open up any C++ file. Define a function with a long name, and some parameters. Then when you try to type the name of the function, you will get completion candidates. If you choose the candidate, Irony will invoke YASnippet to lay out a template for the parameters, so you could tab through the parameters. If you then quickly fill the parameters and tab through, you will see the error.

**Comment by hotpxl** [comment]
I would suggest such patch. It seems to fix the issue. But I'm not clear *why* `yas--active-field-overlay` could not be an overlay.

```diff
--- yasnippet.el	2015-11-02 15:57:47.000000000 -0800
+++ yasnippet.fix.el	2015-11-02 15:57:43.000000000 -0800
@@ -3403,21 +3403,22 @@
 progress."
   (unless (or yas--inhibit-overlay-hooks
               (yas--undo-in-progress))
-    (let* ((field (overlay-get overlay 'yas--field))
-           (snippet (overlay-get yas--active-field-overlay 'yas--snippet)))
-      (cond (after?
-             (yas--advance-end-maybe field (overlay-end overlay))
-             (save-excursion
-               (yas--field-update-display field))
-             (yas--update-mirrors snippet))
-            (field
-             (when (and (not after?)
-                        (not (yas--field-modified-p field))
-                        (eq (point) (if (markerp (yas--field-start field))
-                                        (marker-position (yas--field-start field))
-                                      (yas--field-start field))))
-               (yas--skip-and-clear field))
-             (setf (yas--field-modified-p field) t))))))
+    (if (overlayp yas--active-field-overlay)
+      (let* ((field (overlay-get overlay 'yas--field))
+             (snippet (overlay-get yas--active-field-overlay 'yas--snippet)))
+        (cond (after?
+                (yas--advance-end-maybe field (overlay-end overlay))
+                (save-excursion
+                  (yas--field-update-display field))
+                (yas--update-mirrors snippet))
+              (field
+                (when (and (not after?)
+                           (not (yas--field-modified-p field))
+                           (eq (point) (if (markerp (yas--field-start field))
+                                         (marker-position (yas--field-start field))
+                                         (yas--field-start field))))
+                  (yas--skip-and-clear field))
+                (setf (yas--field-modified-p field) t)))))))
 
 ;;; Apropos protection overlays:
 ;;
```

**Comment by hotpxl** [comment]
I would suggest such a patch. Although I don't see why `yas--active-field-overlay` could be something other than an overlay.

```diff
--- yasnippet.orig.el	2015-11-02 16:04:36.000000000 -0800
+++ yasnippet.el	2015-11-02 16:04:40.000000000 -0800
@@ -3403,21 +3403,22 @@
 progress."
   (unless (or yas--inhibit-overlay-hooks
               (yas--undo-in-progress))
-    (let* ((field (overlay-get overlay 'yas--field))
-           (snippet (overlay-get yas--active-field-overlay 'yas--snippet)))
-      (cond (after?
-             (yas--advance-end-maybe field (overlay-end overlay))
-             (save-excursion
-               (yas--field-update-display field))
-             (yas--update-mirrors snippet))
-            (field
-             (when (and (not after?)
-                        (not (yas--field-modified-p field))
-                        (eq (point) (if (markerp (yas--field-start field))
-                                        (marker-position (yas--field-start field))
-                                      (yas--field-start field))))
-               (yas--skip-and-clear field))
-             (setf (yas--field-modified-p field) t))))))
+    (if (overlayp yas--active-field-overlay)
+      (let* ((field (overlay-get overlay 'yas--field))
+             (snippet (overlay-get yas--active-field-overlay 'yas--snippet)))
+        (cond (after?
+                (yas--advance-end-maybe field (overlay-end overlay))
+                (save-excursion
+                  (yas--field-update-display field))
+                (yas--update-mirrors snippet))
+              (field
+                (when (and (not after?)
+                           (not (yas--field-modified-p field))
+                           (eq (point) (if (markerp (yas--field-start field))
+                                         (marker-position (yas--field-start field))
+                                         (yas--field-start field))))
+                  (yas--skip-and-clear field))
+                (setf (yas--field-modified-p field) t)))))))
 
 ;;; Apropos protection overlays:
 ;;
```

**Comment by npostavs** [comment]
> It basically installs Company, YASnippet, Flycheck, and Irony.

And like 20 other packages, can you trim it down a bit more?

> I would suggest such a patch.

That should be the same as 
```diff
diff --git i/yasnippet.el w/yasnippet.el
index ed9aa2f..86cccbf 100644
--- i/yasnippet.el
+++ w/yasnippet.el
@@ -3399,7 +3399,8 @@ (defun yas--on-field-overlay-modification (overlay after? _beg _end &optional _l
 at field start.  This hook doesn't do anything if an undo is in
 progress."
   (unless (or yas--inhibit-overlay-hooks
-              (yas--undo-in-progress))
+              (yas--undo-in-progress)
+              (not (overlayp yas--active-field-overlay)))
     (let* ((field (overlay-get overlay 'yas--field))
            (snippet (overlay-get yas--active-field-overlay 'yas--snippet)))
       (cond (after?
```
right?

> Although I don't see why yas--active-field-overlay could be something other than an overlay.

Well, the default value is `nil`, which is what it appears to be in your stacktrace. What doesn't make sense is how `yas--on-field-overlay-modification` can be called in this case, since it's only called as the modification hook of `yas--active-field-overlay`.

**Comment by hotpxl** [comment]
I trimmed down unnecessary packages. Still [here](https://gist.github.com/hotpxl/cfad63d5e88ed164bc76).

Yes. Your patch is the same. In fact the error happens after a few successful invocations of the function. So it sure is not the case where the variable is still in default mode.

**Comment by npostavs** [comment]
> I trimmed down unnecessary packages. Still here.

I had to comment out a bit more https://gist.github.com/hotpxl/cfad63d5e88ed164bc76#file-emacs-L64-L76

---

I have reproduced the problem, using the following c++ buffer:

```c
void func(int x);
int main() {
  fun|
     ^--- cursor here
}
```
`TAB` (expands to `func(int x)` with `int x` the active field), then hit `y` and do `C-b C-f` a few times.

It seems that when the modification hook is run, the current buffer is not the C++ source buffer, but actually `*Messages*` (`yas--active-field-overlay` is buffer local). The `_beg` `_end` and `_length` also appear to correspond to the `*Messages*` buffer (certainly they're too big to match the yasnippet overlay in the C++ buffer).  This looks like an Emacs bug.

**Comment by hotpxl** [comment]
Nice catch! That makes sense. In the original stack trace, it shows that Flycheck called `message`, and it in turn triggered the modification hook. The second argument to the hook is `t`, so it is invoked "after a change" according to the doc. The overlay object is from the C++ buffer, but as you said, `_beg`, `_end`, and `_length` appear to correspond to the `*Messages*` buffer. Could you help report the bug to Emacs please? Can we have the workaround for now?
Thanks

**Comment by hotpxl** [comment]
I traced the call into Emacs source code `src/buffer.c`. There is a function `report_overlay_modification`. It *should* (I guess) be called with `after` set to `false` and `true` alternatively. But on the erroneous invocation, it is called with `after` set to `true` twice consecutively. The first call `_beg` and `_end` are normal small integer (inside C++ buffer). The second call they are huge and must refer to the `*Messages*` buffer. Inside the call, it uses a global array to store overlay modification hook functions. Now it's called twice consecutively with `after` set to `true`, it must have reused old hook functions, hence the call to our function with correct overlay but wrong cursor. Because on a call with `after` set to `false`, it will "clear" the hook functions.

**Comment by npostavs** [comment]
Reported to Emacs bug tracker http://debbugs.gnu.org/cgi/bugreport.cgi?bug=21824
