### ISSUE TITLE
When installing from emacs, adding (yas-global-mode 1) doesn't work

### ISSUE THREAD

**Issue by lots-of-birds** [capitaomorte/yasnippet#608]
Installation of Yasnippet from emacs using MELPA
1) M-x list-packages
2) C-s yasnippet
3) press enter on this entry to access yasnippet MELPA documentation.
4) See that it states :
To enable it in all buffers, add the following line to your init file:   (yas-global-mode 1)
5) install it (maybe verify that it is installed by using a .c file and enabling minor mode)
6) Put (yas-global-mode 1) in .emacs and get an error on startup

-----
This is due to the fact that when using MELPA, the modules are loaded after the reading of the init file .emacs

Workaround I used:
(eval-after-load "yasnippet" '(yas-global-mode 1) )

**Comment by npostavs** [comment]
It should work if you put `(package-initialize)` in your .emacs before configuring any packages. I believe Emacs 25 will insert this statement automatically.

I'm closing, as this is a general problem of Emacs' package.el, not a yasnippet bug.
