### ISSUE TITLE
Make hash tables buffer local variables.

### ISSUE THREAD

**Issue by lawlist** [capitaomorte/yasnippet#610]
I have a customized version of yasnippet, but many characteristics remain the same.  I had an issue today where switching between buffers of different major modes where yas-minor-mode was enabled locally, resulted in snippets being unavailable in the buffer that was loaded earlier in time.  The cause was global hash-tables, instead of buffer local -- i.e., adding `make-variable-buffer-local` fixed it.

**Comment by capitaomorte** [comment]
> I had an issue today where switching between buffers of different major modes where yas-minor-mode was enabled locally, resulted in snippets being unavailable in the buffer that was loaded earlier in time. 

I suspect that you know exactly what you mean by this, but I really don't: Can you post a clear guide (preferably one starting from `emacs -Q` and using a minimal amount of packages other than yasnippet) that demonstrates this issue?

**Comment by lawlist** [comment]
Essentially most of the variables used by yasnippet should be buffer-local, not global.  Another problem I discovered today was `yas--direct-keymaps` was global, and should be buffer-local.  Going through all the `defvar` and `defconst` and adding `(make-variable-buffer-local . . .` will fix the problem so that users can have multiple open buffers with different kinds of snippets in each buffer.  As far as I can tell, there are probably only a couple of variables in the library that should be global -- everything else should be buffer-local.

**Comment by capitaomorte** [comment]
> Essentially most of the variables used by yasnippet should be buffer-local, not global. The reason is because the values may be different for each buffer. 

This doesn't really make sense, sorry. You've given me the definition of buffer-local variables as a justification for making every variable a buffer-local variable.

> Another problem I discovered today was yas--direct-keymaps was global, and should be buffer-local. Going through all the defvar and defconst and adding (make-variable-buffer-local . . . will fix the problem 

I hope you realize that the "problem" that you still have describe

> so that users can have multiple open buffers, of different major modes, with different kinds of snippets in each buffer.

This looks like the beginning of a description, but it's very vague.

As with #611, why don't you describe a small, simple situation, where you expected something to happen but that expectation wasn't met by Yasnippet. Be sure to also read https://github.com/capitaomorte/yasnippet#important-note-regarding-bug-reporting before, please. I am closing this issue, but I will promptly reopen it as soon as you clearly describe the problem, OK?
