### ISSUE TITLE
Modify `yas--simple-mirror-regexp` to support LaTeX \$

### ISSUE THREAD

**Issue by lawlist** [capitaomorte/yasnippet#611]
I use a custom version of yasnippet, but many of the original characteristics remain.

I determined that `yas--simple-mirror-regexp` was responsible for deleting the dollar sign and part of the numbers when surrounding a dollar amount with a snippet when writing LaTeX documents.  I fixed it by using:  `"[^\\]$\\([0-9]+\\)"`  I don't do any *real* programming, so I have no idea how that might affect other things.

On another note, to work with LaTeX, I had to comment out all the `yas--protect-escapes` and `yas--restore-escapes` in `yas--snippet-parse-create` to prevent them from deleting my backslashes when surrounding LaTeX codes with a snippet.  I don't know how to fix it, but people who would like to use yasnippet with LaTeX will probably have the same problem.  I do *not* use AUCTeX, and am working with a custom version modified from the built-in `tex-mode.el`.

**Comment by capitaomorte** [comment]
Again, just as with #610, and before I consider your technique for fixing the problem, can you demonstrate what the problem is, what snippet in what situation is incorrectly deleting dollar sign in what situations? Post a bit of the `latex` file you are using.

**Comment by lawlist** [comment]
Here are two of the most common examples:

\$15,530.45

Seymoure Hersh.\\
The Hello World Company\\
111 N. Wne-two-three way.\\
Los Angeles, CA  90026

~\\

And some more text.

~\\

____

Here is an italics snippet:

    # -*- mode: snippet -*-
    # contributor: lawlist
    # key: italics
    # name: italics
    # binding: TAB i
    # --
    `(let* (
          (region-active-p (region-active-p))
          (reg-beg (when region-active-p (region-beginning)))
          (reg-end (when region-active-p (region-end))) )
        (cond
          (lawlist-mc/mode
            "\\textit{$0}")
          ((and
              (not lawlist-mc/mode)
              region-active-p)
            (concat
              "\\textit{"
              ys-selected-text
              "}"))
          (t
            "\\textit{$1}")))`

Here is a double-underline snippet:

    # -*- mode: snippet -*-
    # contributor: lawlist
    # key: double_underline
    # name: double_underline
    # binding: TAB u
    # --
    `(let* (
          (region-active-p (region-active-p))
          (reg-beg (when region-active-p (region-beginning)))
          (reg-end (when region-active-p (region-end))) )
        (cond
          (lawlist-mc/mode
            "\\uuline{$0}")
          ((and
              (not lawlist-mc/mode)
              region-active-p)
            (concat
              "\\uuline{"
              ys-selected-text
              "}"))
          (t
            "\\uuline{$1}")))`

**Comment by capitaomorte** [comment]
@lawlist let's for a moment put aside your implementation and your version and your ideas about yasnippet's source code, which I will be very happy to discuss with you, *after* you explain to me what the problem you're experiencing is.

This is what I know so far: 

1. You start Emacs and activate yasnippet
2. You open a latex file with some text with a dollar sign, such as a dollar amount
3. You select that text and choose a snippet from the menu
4. Something unexpected happens

I still have to know:

* Exactly what snippet you selected in 3. Post the actual content of the snippet here.
* In 4, what the expected result was and what the actual result was


Then the yasnippet team can determine if something needs to be fixed. Then we can decide how to fix it.

By the way, I have experimented with this snippet, which worked fine in my tests. It's a snippet for emphasizing latex text.

```
# key: e
# name: emph
# --
\emph{${1:`yas-selected-text`}}$0
```

**Comment by lawlist** [comment]
Your test does indeed work as advertised.  I will need to diff my version of yasnippet to the current version in the Github repository and see what has changed.  Thank you.
