### ISSUE TITLE
space necessary? 

### ISSUE THREAD

**Issue by bumbker** [capitaomorte/yasnippet#612]
Can I set up Yasnippet to expand all my snippets inside text with no space first?

**Comment by capitaomorte** [comment]
You'll have to be more specific, I can't understand what specific situation you are referring to, though I can guess it's related to how yasnippet replaces a trigger key (abbreviation) with the snippet expansion.

It looks like you might want to read the documentation of the variable `yas-key-syntaxes`. Use `C-h v yas-key-syntaxes RET` for that. Or read here http://capitaomorte.github.io/yasnippet/snippet-reference.html#yas-key-syntaxes

**Comment by bumbker** [comment]
I mean as I'm typing along in the buffer I want to be able to no-spaceTriggerSnippet  right inside a word instead of  space-first->   TriggerSnippet.  .

**Comment by capitaomorte** [comment]
Let me ask you this: what is the snippet abbreviation you are trying to expand and what is the text that immediately precedes that abbreviation, without the space? Is it `some innocent textbla` where `bla` is the  snippet trigger key that you want to expand to something else? 

If so, I think it is possible, you have to add `'yas-shortest-key-until-whitespace` to `yas-key-syntaxes`. Paging @npostavs for some expertise on this issue.

**Comment by npostavs** [comment]
> you have to add `'yas-shortest-key-until-whitespace` to `yas-key-syntaxes`

Yup. Or `'yas-longest-key-from-whitespace` depending on your preferences.

**Comment by bumbker** [comment]
Exactly right.  some innocent textbla where bla is the snippet trigger   describes it perfectly.
I want all of my snippets to work that way.  My snippet trigger keys are all 4 letters of only consonants like tfpt and kfmn so I don't have to worry about word spelling conflicting with them and I don't want to hit the space bar first every time.  I wonder If I can change or add something in yasnippet.el to make it work that way for all snippets. I'm a memory system enthusiast.

**Comment by capitaomorte** [comment]
Add this line to your configuration file 
```
(add-to-list 'yas-key-syntaxes 'yas-shortest-key-from-whitespace)
```

**Comment by bumbker** [comment]
Now this pops up in the echo area:
Wrong type argument: stringp, yas-shortest-key-from-whitespace

**Comment by npostavs** [comment]
That's 
```elisp
(add-to-list 'yas-key-syntaxes 'yas-longest-key-from-whitespace)
;; or
(add-to-list 'yas-key-syntaxes 'yas-shortest-key-until-whitespace)


;; NOT  
(add-to-list 'yas-key-syntaxes 'yas-shortest-key-from-whitespace)
```

**Comment by capitaomorte** [comment]
Ooops, my bad, sorry about that.

Also @npostavs, a better error message should pop up when a symbol not naming a function is added to `yas-key-syntaxes`, don't you think?

**Comment by npostavs** [comment]
Actually I think @bumbker might be using an older yasnippet that doesn't support functions in `yas-key-syntaxes`.

But it was causing an infinite loop in latest yasnippet, fixed now by 8df6a6ed8e667a92b681c3950cee6acfd4213078.

**Comment by capitaomorte** [comment]
> Actually I think @bumbker might be using an older yasnippet that doesn't support functions in yas-key-syntaxes.

oh, that won't work then...

> But it was causing an infinite loop in latest yasnippet, fixed now by 8df6a6e.

oops, another screw-up of mine I guess. Thanks!

**Comment by Ynjxsjmh** [comment]
I tried adding `(add-to-list 'yas-key-syntaxes 'yas-longest-key-from-whitespace)` into my configuration file. After I executed `eval-buffer`, everything went right and I could expand my snippets inside text with no space ahead.

But after restarting my Emacs, I got the error `Symbol's value as variable is void: yas-key-syntaxes` and I couldn't expand snippets inside text with no space ahead anymore.

What's wrong with that? After using `--debug-init` restart my Emacs, it gives the output:
```
Debugger entered--Lisp error: (void-variable yas-key-syntaxes)
  (member 'yas-longest-key-from-whitespace yas-key-syntaxes)
  (if (member 'yas-longest-key-from-whitespace yas-key-syntaxes) yas-key-syntaxes (setq yas-key-syntaxes (cons 'yas-longest-key-from-whitespace yas-key-syntaxes)))
  eval-buffer(#<buffer  *load*-712002> nil "c:/Users/Administrator/.emacs.d/lisp/my-init.el" nil t)  ; Reading at buffer position 1325
  load-with-code-conversion("c:/Users/Administrator/.emacs.d/lisp/my-init.el" "c:/Users/Administrator/.emacs.d/lisp/my-init.el" nil t)
  require(my-init)
  (let* ((file-name-handler-alist nil)) (require 'init-autoload) (require 'init-modeline) (require 'init-utils) (require 'init-elpa) (require 'init-exec-path) (require 'init-spelling) (require 'init-gui-frames) (require 'init-uniquify) (require 'init-ibuffer) (require 'init-ivy) (require 'init-hippie-expand) (require 'init-windows) (require 'init-markdown) (require 'init-erlang) (require 'init-javascript) (require 'init-org) (require 'init-css) (require 'init-python) (require 'init-haskell) (require 'init-ruby-mode) (require 'init-lisp) (require 'init-elisp) (require 'init-yasnippet) (require 'init-cc-mode) (require 'init-gud) (require 'init-linum-mode) (require 'init-git) (require 'init-gtags) (require 'init-clipboard) (require 'init-evil) (require 'init-multiple-cursors) (require 'init-ctags) (require 'init-bbdb) (require 'init-gnus) (require 'init-lua-mode) (require 'init-workgroups2) (require 'init-term-mode) (require 'init-web-mode) (require 'init-company) (require 'init-chinese) (require 'init-keyfreq) (require 'init-httpd) (require 'init-misc) (require 'init-emacs-w3m) (require 'init-hydra) (require 'init-shackle) (require 'init-dired) (require 'init-writting) (require 'my-init) (setq load-path (cdr load-path)) (load (expand-file-name "~/.emacs.d/lisp/init-site-lisp") t t) (load (expand-file-name "~/.custom.el") t nil) (load (setq custom-file (expand-file-name "~/.emacs.d/custom-set-variables.el")) t t))
  eval-buffer(#<buffer  *load*> nil "c:/Users/Administrator/.emacs.d/init.el" nil t)  ; Reading at buffer position 6107
  load-with-code-conversion("c:/Users/Administrator/.emacs.d/init.el" "c:/Users/Administrator/.emacs.d/init.el" t t)
  load("c:/Users/Administrator/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1000be22d>)()
  command-line()
  normal-top-level()
```

**Comment by npostavs** [comment]
@Ynjxsjmh The `yas-key-syntaxes` variable only exists after yasnippet is loaded, for your init file you should use
```elisp
(eval-after-load 'yasnippet
  '(add-to-list 'yas-key-syntaxes 'yas-longest-key-from-whitespace))
```

**Comment by Ynjxsjmh** [comment]
That's it, thanks a lot!
