### ISSUE TITLE
Trigger snippet inside another not working

### ISSUE THREAD

**Issue by DiogoFerrari** [capitaomorte/yasnippet#613]
Dear
I am trying to trigger snippet inside another in org-mode but it is not working even with (setq yas-triggers-in-field t). Would you know what is going on?

Thanks

**Comment by capitaomorte** [comment]
> Would you know what is going on?

No, not really but if you provide a complete reproducible error recipe starting from `emacs -Q`, we might. Read https://github.com/capitaomorte/yasnippet#important-note-regarding-bug-reporting for why we need this and for an example of a good error report.

**Comment by notetiene** [comment]
```bash
$ emacs --version
GNU Emacs 24.5.1
$ cd /tmp/
$ git clone https://github.com/capitaomorte/yasnippet.git yasnippet-bug
$ cd yasnippet-bug
$ git log -1 --oneline
35642ac Simplify string matching.
$ HOME=$PWD
$ emacs -Q -L .
```
snippets files:
```elisp
# -*- mode: snippet -*-
#name : cond
# key: cond
# --
(cond (${1:condition}
       $0
       )
      (t

       ))
```
```elisp
# -*- mode: snippet -*-
#name : if
# key: if
# this file is supposed to expand cond also
# --
(if ${1:cond$2}
    $0
  )
```
*scratch*:
```elisp
(require 'yasnippet)
(yas-global-mode 1)
(setq 

if
  ^^^
 cursor
```
when you press TAB repeatedly that's what I obtain:
``` elisp
(if cond
    
    ^^^
   cursor
    )
```
cond is not expanded. I know the snippets don't make sense in lisp, but it's just for demonstration purposes.

**Comment by npostavs** [comment]
Is this the same as #269?

**Comment by notetiene** [comment]
Not the original bug. It's the same as your response I think.

**Comment by npostavs** [comment]
> It's the same as your response I think.

Ah, actually my response there appears to work fine. Maybe when I posted it I wasn't aware of `yas-triggers-in-field`. Something that actually fails is
```
# key: nest
# name: nest
# --
(${1:nest}$2)$0
```

The problem is that when point is after `nest`, it is actually in field `$2` and `yas-expand-from-trigger-key` restricts expansion to within that field (which is empty).

```elisp
(defun yas-next-field-or-maybe-expand ()
  ...        
        (when active-field
          (unless (yas-expand-from-trigger-key active-field)
            (yas-next-field)))
  ...)

(defun yas-expand-from-trigger-key (&optional field)
  ...
                                    (narrow-to-region (yas--field-start field)
                                                      (yas--field-end field))
                                    (yas--templates-for-key-at-point)
  ...)
```

[yasnippet.el:2162-2164](https://github.com/capitaomorte/yasnippet/blob/b055f132be939443dfc2801d587239e547a1b6f9/yasnippet.el#L2162-L2164)
[yasnippet.el:3060-3062](https://github.com/capitaomorte/yasnippet/blob/b055f132be939443dfc2801d587239e547a1b6f9/yasnippet.el#L3060-L3062)

**Comment by DiogoFerrari** [comment]
I think the new version of org-mode and yas are playing well. I had the problem after I updated the packages. I removed all instructions and it started working
