### ISSUE TITLE
lobby to remove yasnippet-bundle from third-party repos

### ISSUE THREAD

**Issue by bjourne** [capitaomorte/yasnippet#615]
On Marmalade there is a yasnippet-bundle package: https://marmalade-repo.org/packages/yasnippet-bundle It appears to be an ancient and obsolete version of yasnippet. Maybe you can campaign to have it removed? Because if you mistakenly believe that yasnippet-bundle is a *bundle* of snippets for yasnippet and install both packages, then yasnippet will break in strange and mysterious ways.

**Comment by capitaomorte** [comment]
> ancient and obsolete version of yasnippet. 

yep

> then yasnippet will break in strange and mysterious ways.

likely

> Maybe you can campaign

Nice try :smile: , but no. I'm really busy, sorry, and I can't control what packagers do: perhaps it's useful to an handful of people, who knows... But if you campaign for it, you hereby have my full support. 

Alternatively, if you submit a 50-line-max reasonably-well-written piece of elisp that reliably detects problematic earlier versions and panics with a unmisterious message, I'll gladly merge it to the codebase.

**Comment by bjourne** [comment]
I'll see what I can do. I'm not involved in any of the yasnippet projects so I don't know what they will say.
