### ISSUE TITLE
yas-choose-value breaks in snippet with too many lines

### ISSUE THREAD

**Issue by Poquaruse** [capitaomorte/yasnippet#617]
Hi all,

yas-choose-value breaks in a snippet with too many lines. Take a look at the example below. (If it doesn't break for you just add more lines...)

    # -*- mode: snippet; require-final-newline: nil -*-
    # name: 
    # key: 
    # binding: direct-keybinding
    # --
    ${1:$$(yas-choose-value'("true" "false"))}
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a
    a

Trying this snippet shows:

    [yas] elisp error: Wrong type argument: number-or-marker-p, nil
    a [...]

If you delete enough lines, it does work again.

Any hints, tips?

Thanks and best regards!

**Comment by npostavs** [comment]
Seems to be working for me, I tried up to 384 `a` lines.

Can you list yasnippet, Emacs, and OS versions?

---

By the way, you shouldn't be using a blank `# name:`.

**Comment by Poquaruse** [comment]
Hi, 

thanks for trying to reproduce the error! I'm using the following setup.

Windows 8.1 incl. latest updates
emacs-24.5-bin-i686-mingw32 
yasnippet 20151004.1657 installed via use-package

I've started emacs using -Q. Then in the scratch buffer I evaluated

    (require 'package)
    (setq package-enable-at-startup nil)
    (add-to-list 'package-archives
    	     '("melpa" . "http://melpa.org/packages/"))
    (package-initialize)
    
    ;; bootstrap use-package
    (unless (package-installed-p 'use-package)
      (package-refresh-contents)
      (package-install 'use-package))
    (require 'use-package)
    
    (use-package yasnippet
      :defer t
      :ensure t
      :init
      (use-package popup
        :ensure t)
      (yas-global-mode 1))

After that, I visited a file and tried to evaluate one of the problematic snippets and the same error occured. Name and key usually aren't empty, I just wanted to create a minimal example and forgot about filling them...

Any tips on how I could help debugging this?

**Comment by npostavs** [comment]
Can you check that it still reproduces with just
```elisp
(load "~/.emacs.d/elpa/yasnippet-20151004.1657/yasnippet.el") ; modify the 20151004.1657 if needed
(yas-global-mode 1)
```

To get a backtrace also evaluate
```elisp
(setq debug-on-error t)

;; redefine this function so backtrace context isn't lost by catching and rethrowing
(defun yas--eval-lisp (form)
  "Evaluate FORM and convert the result to string."
  (let ((retval (catch 'yas--exception
                  (save-excursion
                    (save-restriction
                      (save-match-data
                        (widen)
                        (let ((result (eval form)))
                          (when result
                            (format "%s" result)))))))))
    (when (and (consp retval)
               (eq 'yas--exception (car retval)))
      (error (cdr retval)))
    retval))
```

**Comment by Poquaruse** [comment]
Unfortunately, the same problem occurs.

Here is the debug output. (BTW: How do I quickly indent that by 4 spaces so that it is shown as code here?)

Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  +(nil 10)
  (list (+ (car x-y) 10) (+ (cdr x-y) 20))
  (list (list (+ (car x-y) 10) (+ (cdr x-y) 20)) (selected-window))
  (let ((x-y (posn-x-y (posn-at-point (point))))) (list (list (+ (car x-y) 10) (+ (cdr x-y) 20)) (selected-window)))
  (if (fboundp (quote posn-at-point)) (let ((x-y (posn-x-y (posn-at-point (point))))) (list (list (+ (car x-y) 10) (+ (cdr x-y) 20)) (selected-window))) t)
  (x-popup-menu (if (fboundp (quote posn-at-point)) (let ((x-y (posn-x-y (posn-at-point (point))))) (list (list (+ (car x-y) 10) (+ (cdr x-y) 20)) (selected-window))) t) (list prompt (cons "title" (mapcar* (function (lambda (c d) (cons (concat "   " d) c))) choices (if display-fn (mapcar display-fn choices) choices)))))
  (or (x-popup-menu (if (fboundp (quote posn-at-point)) (let ((x-y (posn-x-y (posn-at-point ...)))) (list (list (+ (car x-y) 10) (+ (cdr x-y) 20)) (selected-window))) t) (list prompt (cons "title" (mapcar* (function (lambda (c d) (cons ... c))) choices (if display-fn (mapcar display-fn choices) choices))))) (keyboard-quit))
  (progn (or (x-popup-menu (if (fboundp (quote posn-at-point)) (let ((x-y (posn-x-y ...))) (list (list (+ ... 10) (+ ... 20)) (selected-window))) t) (list prompt (cons "title" (mapcar* (function (lambda ... ...)) choices (if display-fn (mapcar display-fn choices) choices))))) (keyboard-quit)))
  (if (and window-system choices) (progn (or (x-popup-menu (if (fboundp (quote posn-at-point)) (let ((x-y ...)) (list (list ... ...) (selected-window))) t) (list prompt (cons "title" (mapcar* (function ...) choices (if display-fn ... choices))))) (keyboard-quit))))
  yas-x-prompt("Choose: " ("true" "false"))
  funcall(yas-x-prompt "Choose: " ("true" "false"))
  (lambda (fn) (funcall fn "Choose: " possibilities))(yas-x-prompt)
  some((lambda (fn) (funcall fn "Choose: " possibilities)) (yas-x-prompt yas-dropdown-prompt yas-completing-prompt yas-ido-prompt yas-no-prompt))
  (if (or yas-moving-away-p yas-modified-p) nil (let* ((last-link (last possibilities)) (last-elem (car last-link))) (if (listp last-elem) (progn (setcar last-link (car last-elem)) (setcdr last-link (cdr last-elem))))) (some (function (lambda (fn) (funcall fn "Choose: " possibilities))) yas-prompt-functions))
  yas-choose-value(("true" "false"))
  eval((yas-choose-value (quote ("true" "false"))))
  (let ((result (eval form))) (if result (progn (format "%s" result))))
  (progn (widen) (let ((result (eval form))) (if result (progn (format "%s" result)))))
  (unwind-protect (progn (widen) (let ((result (eval form))) (if result (progn (format "%s" result))))) (set-match-data save-match-data-internal (quote evaporate)))
  (let ((save-match-data-internal (match-data))) (unwind-protect (progn (widen) (let ((result (eval form))) (if result (progn (format "%s" result))))) (set-match-data save-match-data-internal (quote evaporate))))
  (save-restriction (let ((save-match-data-internal (match-data))) (unwind-protect (progn (widen) (let ((result (eval form))) (if result (progn (format "%s" result))))) (set-match-data save-match-data-internal (quote evaporate)))))
  (save-excursion (save-restriction (let ((save-match-data-internal (match-data))) (unwind-protect (progn (widen) (let ((result ...)) (if result (progn ...)))) (set-match-data save-match-data-internal (quote evaporate))))))
  (catch (quote yas--exception) (save-excursion (save-restriction (let ((save-match-data-internal (match-data))) (unwind-protect (progn (widen) (let (...) (if result ...))) (set-match-data save-match-data-internal (quote evaporate)))))))
  (let ((retval (catch (quote yas--exception) (save-excursion (save-restriction (let (...) (unwind-protect ... ...))))))) (if (and (consp retval) (eq (quote yas--exception) (car retval))) (progn (error (cdr retval)))) retval)
  yas--eval-lisp((yas-choose-value (quote ("true" "false"))))
  (let ((ret (yas--eval-lisp transform))) (or ret (and empty-on-nil-p "")))
  (save-excursion (goto-char start-point) (let ((ret (yas--eval-lisp transform))) (or ret (and empty-on-nil-p ""))))
  (and transform (save-excursion (goto-char start-point) (let ((ret (yas--eval-lisp transform))) (or ret (and empty-on-nil-p "")))))
  (let* ((yas-text (yas--field-text-for-display field)) (yas-modified-p (progn (or (and (vectorp field) (>= (length field) 9) (memq (aref field 0) cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-modified-p) (quote yas--field))) (aref field 7))) (yas-moving-away-p nil) (transform (if (progn (and (vectorp field-or-mirror) (>= (length field-or-mirror) 7) (memq (aref field-or-mirror 0) cl-struct-yas--mirror-tags) t)) (progn (or (and (vectorp field-or-mirror) (>= ... 7) (memq ... cl-struct-yas--mirror-tags)) (error "%s accessing a non-%s" (quote yas--mirror-transform) (quote yas--mirror))) (aref field-or-mirror 3)) (progn (or (and (vectorp field-or-mirror) (>= ... 9) (memq ... cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-transform) (quote yas--field))) (aref field-or-mirror 6)))) (start-point (if (progn (and (vectorp field-or-mirror) (>= (length field-or-mirror) 7) (memq (aref field-or-mirror 0) cl-struct-yas--mirror-tags) t)) (progn (or (and (vectorp field-or-mirror) (>= ... 7) (memq ... cl-struct-yas--mirror-tags)) (error "%s accessing a non-%s" (quote yas--mirror-start) (quote yas--mirror))) (aref field-or-mirror 1)) (progn (or (and (vectorp field-or-mirror) (>= ... 9) (memq ... cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-start) (quote yas--field))) (aref field-or-mirror 2)))) (transformed (and transform (save-excursion (goto-char start-point) (let ((ret ...)) (or ret (and empty-on-nil-p ""))))))) transformed)
  yas--apply-transform([cl-struct-yas--field 1 #<marker at 1 in *testing snippet: test*> #<marker at 1 in *testing snippet: test*> nil nil (yas-choose-value (quote ("true" "false"))) nil nil] [cl-struct-yas--field 1 #<marker at 1 in *testing snippet: test*> #<marker at 1 in *testing snippet: test*> nil nil (yas-choose-value (quote ("true" "false"))) nil nil])
  (and (not (eq (progn (or (and (vectorp field) (>= (length field) 9) (memq (aref field 0) cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-number) (quote yas--field))) (aref field 1)) 0)) (yas--apply-transform field field))
  (let ((transformed (and (not (eq (progn (or ... ...) (aref field 1)) 0)) (yas--apply-transform field field)))) (if (and transformed (not (string= transformed (buffer-substring-no-properties (progn (or ... ...) (aref field 2)) (progn (or ... ...) (aref field 3)))))) (progn (progn (or (and (vectorp field) (>= (length field) 9) (memq (aref field 0) cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-modified-p) (quote yas--field))) (let* ((v field)) (aset v 7 t))) (goto-char (progn (or (and (vectorp field) (>= ... 9) (memq ... cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-start) (quote yas--field))) (aref field 2))) (let ((yas--inhibit-overlay-hooks t)) (insert transformed) (if (> (progn (or ... ...) (aref field 3)) (point)) (delete-region (point) (progn (or ... ...) (aref field 3))) (set-marker (progn (or ... ...) (aref field 3)) (point)) (yas--advance-start-maybe (progn (or ... ...) (aref field 8)) (point))) t))))
  (progn (let ((transformed (and (not (eq (progn ... ...) 0)) (yas--apply-transform field field)))) (if (and transformed (not (string= transformed (buffer-substring-no-properties (progn ... ...) (progn ... ...))))) (progn (progn (or (and (vectorp field) (>= ... 9) (memq ... cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-modified-p) (quote yas--field))) (let* ((v field)) (aset v 7 t))) (goto-char (progn (or (and ... ... ...) (error "%s accessing a non-%s" ... ...)) (aref field 2))) (let ((yas--inhibit-overlay-hooks t)) (insert transformed) (if (> (progn ... ...) (point)) (delete-region (point) (progn ... ...)) (set-marker (progn ... ...) (point)) (yas--advance-start-maybe (progn ... ...) (point))) t)))))
  (if (progn (or (and (vectorp field) (>= (length field) 9) (memq (aref field 0) cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-transform) (quote yas--field))) (aref field 6)) (progn (let ((transformed (and (not (eq ... 0)) (yas--apply-transform field field)))) (if (and transformed (not (string= transformed (buffer-substring-no-properties ... ...)))) (progn (progn (or (and ... ... ...) (error "%s accessing a non-%s" ... ...)) (let* (...) (aset v 7 t))) (goto-char (progn (or ... ...) (aref field 2))) (let ((yas--inhibit-overlay-hooks t)) (insert transformed) (if (> ... ...) (delete-region ... ...) (set-marker ... ...) (yas--advance-start-maybe ... ...)) t))))))
  yas--field-update-display([cl-struct-yas--field 1 #<marker at 1 in *testing snippet: test*> #<marker at 1 in *testing snippet: test*> nil nil (yas-choose-value (quote ("true" "false"))) nil nil])
  (if (yas--field-update-display field) (yas--update-mirrors snippet) (progn (or (and (vectorp field) (>= (length field) 9) (memq (aref field 0) cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-modified-p) (quote yas--field))) (let* ((v field)) (aset v 7 nil))))
  (if (progn (or (and (vectorp field) (>= (length field) 9) (memq (aref field 0) cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-modified-p) (quote yas--field))) (aref field 7)) nil (if (yas--field-update-display field) (yas--update-mirrors snippet) (progn (or (and (vectorp field) (>= (length field) 9) (memq (aref field 0) cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-modified-p) (quote yas--field))) (let* ((v field)) (aset v 7 nil)))))
  (if (and number (zerop number)) (progn (set-mark (progn (or (and (vectorp field) (>= (length field) 9) (memq (aref field 0) cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-end) (quote yas--field))) (aref field 3))) (progn (or (and (vectorp snippet) (>= (length snippet) 8) (memq (aref snippet 0) cl-struct-yas--snippet-tags)) (error "%s accessing a non-%s" (quote yas--snippet-force-exit) (quote yas--snippet))) (let* ((v snippet)) (aset v 7 (or (progn (or ... ...) (aref field 6)) t))))) (progn (or (and (vectorp snippet) (>= (length snippet) 8) (memq (aref snippet 0) cl-struct-yas--snippet-tags)) (error "%s accessing a non-%s" (quote yas--snippet-active-field) (quote yas--snippet))) (let* ((v snippet)) (aset v 5 field))) (if (progn (or (and (vectorp field) (>= (length field) 9) (memq (aref field 0) cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-modified-p) (quote yas--field))) (aref field 7)) nil (if (yas--field-update-display field) (yas--update-mirrors snippet) (progn (or (and (vectorp field) (>= (length field) 9) (memq (aref field 0) cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-modified-p) (quote yas--field))) (let* ((v field)) (aset v 7 nil))))))
  (let ((number (progn (or (and (vectorp field) (>= (length field) 9) (memq (aref field 0) cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-number) (quote yas--field))) (aref field 1)))) (if (and number (zerop number)) (progn (set-mark (progn (or (and (vectorp field) (>= ... 9) (memq ... cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-end) (quote yas--field))) (aref field 3))) (progn (or (and (vectorp snippet) (>= (length snippet) 8) (memq (aref snippet 0) cl-struct-yas--snippet-tags)) (error "%s accessing a non-%s" (quote yas--snippet-force-exit) (quote yas--snippet))) (let* ((v snippet)) (aset v 7 (or (progn ... ...) t))))) (progn (or (and (vectorp snippet) (>= (length snippet) 8) (memq (aref snippet 0) cl-struct-yas--snippet-tags)) (error "%s accessing a non-%s" (quote yas--snippet-active-field) (quote yas--snippet))) (let* ((v snippet)) (aset v 5 field))) (if (progn (or (and (vectorp field) (>= (length field) 9) (memq (aref field 0) cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-modified-p) (quote yas--field))) (aref field 7)) nil (if (yas--field-update-display field) (yas--update-mirrors snippet) (progn (or (and (vectorp field) (>= ... 9) (memq ... cl-struct-yas--field-tags)) (error "%s accessing a non-%s" (quote yas--field-modified-p) (quote yas--field))) (let* ((v field)) (aset v 7 nil)))))))
  yas--move-to-field([cl-struct-yas--snippet ([cl-struct-yas--field 1 #<marker at 1 in *testing snippet: test*> #<marker at 1 in *testing snippet: test*> nil nil (yas-choose-value (quote ("true" "false"))) nil nil]) nil 0 #<overlay from 1 to 97 in *testing snippet: test*> [cl-struct-yas--field 1 #<marker at 1 in *testing snippet: test*> #<marker at 1 in *testing snippet: test*> nil nil (yas-choose-value (quote ("true" "false"))) nil nil] nil nil] [cl-struct-yas--field 1 #<marker at 1 in *testing snippet: test*> #<marker at 1 in *testing snippet: test*> nil nil (yas-choose-value (quote ("true" "false"))) nil nil])
  (progn (sit-for 0) (yas--move-to-field snippet first-field))
  (if first-field (progn (sit-for 0) (yas--move-to-field snippet first-field)))
  (let ((first-field (car (progn (or (and (vectorp snippet) (>= ... 8) (memq ... cl-struct-yas--snippet-tags)) (error "%s accessing a non-%s" (quote yas--snippet-fields) (quote yas--snippet))) (aref snippet 1))))) (if first-field (progn (sit-for 0) (yas--move-to-field snippet first-field))))
  (cond ((listp content) (yas--eval-lisp-no-saves content)) (t (let ((buffer-undo-list t)) (setq yas--start-column (current-column)) (let ((yas--inhibit-overlay-hooks t)) (setq snippet (if expand-env (eval (cons ... ...)) (insert content) (yas--snippet-create start (point)))))) (let ((existing-field (and yas--active-field-overlay (overlay-buffer yas--active-field-overlay) (overlay-get yas--active-field-overlay (quote yas--field))))) (if existing-field (progn (progn (or (and ... ... ...) (error "%s accessing a non-%s" ... ...)) (let* (...) (aset v 6 existing-field))) (yas--advance-end-maybe existing-field (overlay-end yas--active-field-overlay))))) (if (progn (or (and (vectorp snippet) (>= (length snippet) 8) (memq (aref snippet 0) cl-struct-yas--snippet-tags)) (error "%s accessing a non-%s" (quote yas--snippet-fields) (quote yas--snippet))) (aref snippet 1)) nil (yas-exit-snippet snippet)) (let ((newstart (overlay-start (progn (or ... ...) (aref snippet 4)))) (end (overlay-end (progn (or ... ...) (aref snippet 4))))) (if (< newstart start) (progn (setq buffer-undo-list (cons (cons ... newstart) buffer-undo-list)))) (setq buffer-undo-list (cons (cons newstart end) buffer-undo-list)) (setq buffer-undo-list (cons (list (quote apply) (quote yas--take-care-of-redo) start end snippet) buffer-undo-list))) (let ((first-field (car (progn (or ... ...) (aref snippet 1))))) (if first-field (progn (sit-for 0) (yas--move-to-field snippet first-field)))) (yas--message 3 "snippet expanded.") t))
  (let* ((yas-selected-text (or yas-selected-text (and (region-active-p) (buffer-substring-no-properties (region-beginning) (region-end))))) (start (or start (and (region-active-p) (region-beginning)) (point))) (end (or end (and (region-active-p) (region-end)) (point))) (to-delete (and start end (buffer-substring-no-properties start end))) snippet) (goto-char start) (setq yas--indent-original-column (current-column)) (if (and to-delete (> end start)) (progn (delete-region start end))) (cond ((listp content) (yas--eval-lisp-no-saves content)) (t (let ((buffer-undo-list t)) (setq yas--start-column (current-column)) (let ((yas--inhibit-overlay-hooks t)) (setq snippet (if expand-env (eval ...) (insert content) (yas--snippet-create start ...))))) (let ((existing-field (and yas--active-field-overlay (overlay-buffer yas--active-field-overlay) (overlay-get yas--active-field-overlay ...)))) (if existing-field (progn (progn (or ... ...) (let* ... ...)) (yas--advance-end-maybe existing-field (overlay-end yas--active-field-overlay))))) (if (progn (or (and (vectorp snippet) (>= ... 8) (memq ... cl-struct-yas--snippet-tags)) (error "%s accessing a non-%s" (quote yas--snippet-fields) (quote yas--snippet))) (aref snippet 1)) nil (yas-exit-snippet snippet)) (let ((newstart (overlay-start (progn ... ...))) (end (overlay-end (progn ... ...)))) (if (< newstart start) (progn (setq buffer-undo-list (cons ... buffer-undo-list)))) (setq buffer-undo-list (cons (cons newstart end) buffer-undo-list)) (setq buffer-undo-list (cons (list (quote apply) (quote yas--take-care-of-redo) start end snippet) buffer-undo-list))) (let ((first-field (car (progn ... ...)))) (if first-field (progn (sit-for 0) (yas--move-to-field snippet first-field)))) (yas--message 3 "snippet expanded.") t)))
  yas-expand-snippet("${1:$$(yas-choose-value'(\"true\" \"false\"))}\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na\na" 1 1 nil)
  (let ((buffer-name (format "*testing snippet: %s*" (progn (or (and (vectorp yas--current-template) (>= ... 14) (memq ... cl-struct-yas--template-tags)) (error "%s accessing a non-%s" (quote yas--template-name) (quote yas--template))) (aref yas--current-template 3))))) (kill-buffer (get-buffer-create buffer-name)) (switch-to-buffer (get-buffer-create buffer-name)) (setq buffer-undo-list nil) (condition-case nil (funcall test-mode) (error nil)) (yas-minor-mode 1) (setq buffer-read-only nil) (yas-expand-snippet (progn (or (and (vectorp yas--current-template) (>= (length yas--current-template) 14) (memq (aref yas--current-template 0) cl-struct-yas--template-tags)) (error "%s accessing a non-%s" (quote yas--template-content) (quote yas--template))) (aref yas--current-template 2)) (point-min) (point-max) (progn (or (and (vectorp yas--current-template) (>= (length yas--current-template) 14) (memq (aref yas--current-template 0) cl-struct-yas--template-tags)) (error "%s accessing a non-%s" (quote yas--template-expand-env) (quote yas--template))) (aref yas--current-template 5))) (if (and debug (require (quote yasnippet-debug) nil t)) (progn (add-hook (quote post-command-hook) (quote yas-debug-snippet-vars) nil t))))
  (cond (yas--current-template (let ((buffer-name (format "*testing snippet: %s*" (progn (or ... ...) (aref yas--current-template 3))))) (kill-buffer (get-buffer-create buffer-name)) (switch-to-buffer (get-buffer-create buffer-name)) (setq buffer-undo-list nil) (condition-case nil (funcall test-mode) (error nil)) (yas-minor-mode 1) (setq buffer-read-only nil) (yas-expand-snippet (progn (or (and (vectorp yas--current-template) (>= ... 14) (memq ... cl-struct-yas--template-tags)) (error "%s accessing a non-%s" (quote yas--template-content) (quote yas--template))) (aref yas--current-template 2)) (point-min) (point-max) (progn (or (and (vectorp yas--current-template) (>= ... 14) (memq ... cl-struct-yas--template-tags)) (error "%s accessing a non-%s" (quote yas--template-expand-env) (quote yas--template))) (aref yas--current-template 5))) (if (and debug (require (quote yasnippet-debug) nil t)) (progn (add-hook (quote post-command-hook) (quote yas-debug-snippet-vars) nil t))))) (t (yas--message 3 "Cannot test snippet for unknown major mode")))
  (let* ((major-mode-and-parent (yas--compute-major-mode-and-parents buffer-file-name)) (parsed (yas--parse-template)) (test-mode (or (and (car major-mode-and-parent) (fboundp (car major-mode-and-parent)) (car major-mode-and-parent)) (first yas--guessed-modes) (intern (read-from-minibuffer (yas--format "Please input a mode: "))))) (yas--current-template (and parsed (fboundp test-mode) (yas--make-template :table nil :key (first parsed) :content (second parsed) :name (car (cdr (cdr parsed))) :expand-env (sixth parsed))))) (cond (yas--current-template (let ((buffer-name (format "*testing snippet: %s*" (progn ... ...)))) (kill-buffer (get-buffer-create buffer-name)) (switch-to-buffer (get-buffer-create buffer-name)) (setq buffer-undo-list nil) (condition-case nil (funcall test-mode) (error nil)) (yas-minor-mode 1) (setq buffer-read-only nil) (yas-expand-snippet (progn (or (and ... ... ...) (error "%s accessing a non-%s" ... ...)) (aref yas--current-template 2)) (point-min) (point-max) (progn (or (and ... ... ...) (error "%s accessing a non-%s" ... ...)) (aref yas--current-template 5))) (if (and debug (require (quote yasnippet-debug) nil t)) (progn (add-hook (quote post-command-hook) (quote yas-debug-snippet-vars) nil t))))) (t (yas--message 3 "Cannot test snippet for unknown major mode"))))
  yas-tryout-snippet(nil)
  call-interactively(yas-tryout-snippet nil nil)
  command-execute(yas-tryout-snippet)

**Comment by npostavs** [comment]
Ah, I didn't see it because I use ido prompting. Looks like the problem is in `yas-x-prompt`:
```elisp
(defun yas-x-prompt (prompt choices &optional display-fn)
          (let ((x-y (posn-x-y (posn-at-point (point)))))
            (list (list (+ (car x-y) 10)
                        (+ (cdr x-y) 20))
                  (selected-window)))
	  ...
  )
```

`posn-at-point` returns nil because all the `a`s have pushed point outside of the visible window.

**Comment by capitaomorte** [comment]
@npostavs, what about this naive fix for these extreme cases?
```
diff --git a/yasnippet.el b/yasnippet.el
index 1f6c7de..bdae881 100644
--- a/yasnippet.el
+++ b/yasnippet.el
@@ -1552,8 +1552,8 @@ Optional PROMPT sets the prompt to use."
      (x-popup-menu
       (if (fboundp 'posn-at-point)
           (let ((x-y (posn-x-y (posn-at-point (point)))))
-            (list (list (+ (car x-y) 10)
-                        (+ (cdr x-y) 20))
+            (list (list (+ (or (car x-y) 0) 10)
+                        (+ (or (cdr x-y) 0) 20))
                   (selected-window)))
         t)
       `(,prompt ("title"

**Comment by npostavs** [comment]
> what about this naive fix

That might be good enough, the other possibilty is to remember the xy position before we expand.

@Poquaruse Do you have an example of a real life snippet that triggers this? Might help to see which approach gives a nicer effect.

**Comment by Poquaruse** [comment]
Hi there,

Sorry for my delayed answer. Below you find an example which breaks on my (small) screen. Just add a few lines or reformat the file so that less content is placed in each line.
    
    # -*- mode: snippet; -*-
    # name: LatexLetter
    # key: \letter
    # binding: direct-keybinding 
    # --
    \documentclass[version=last,${1:$$(yas-choose-value '("1" "2" "3"))}]{scrlttr2}
    \usepackage{polyglossia}
    \setmainlanguage[babelshorthands=true]{english}
    \usepackage{ifthen}
    \usepackage{graphicx}
    \newboolean{sig}
    \setboolean{sig}{${2:$$(yas-choose-value '("true" "false"))}}
    \KOMAoption{fromphone}{${3:$$(yas-choose-value '("true" "false"))}}
    \KOMAoption{fromemail}{${4:$$(yas-choose-value '("true" "false"))}}
    \KOMAoption{fromfax}{${5:$$(yas-choose-value '("true" "false"))}}
    %\setkomavar{place}{${6:place}}
    \makeatletter%
    \ifthenelse{\boolean{sig}}%
    {\setkomavar{signature}{\includegraphics[scale=0.4]{abc.png}\\\usekomavar{fromname}}
    \@setplength{sigbeforevskip}{0.2cm}%
    }{\setkomavar{signature}{\usekomavar{fromname}}}%
    \makeatother%
    \begin{document}
    %\setkomavar{date}{${7:date}}
    \setkomavar{subject}{${8:subject}}
    \begin{letter}{
    ${9:name}\\\\
    ${10:company}\\\\
    ${11:street}\\\\
    ${12:place}\\\\
    }
    \opening{${13:Dear}}
    $0
    \closing{${14:Best regards}}
    \end{letter}%
    %\encl{encl}
    \end{document}%

Best regards

**Comment by capitaomorte** [comment]
I guess the x prompt should be show near the place where the field is. If point is not there at the time of prompting, perhaps it should. If that point is not visible in the window, perhaps a `recenter` is in order.

**Comment by npostavs** [comment]
> I guess the x prompt should be show near the place where the field is.

Yes, just using `(0, 0)` as the coordinates means the prompt shows up while the place the text will be inserted is not visible which is quite confusing.

> If that point is not visible in the window, perhaps a recenter is in order.

It seems `redisplay` is what's needed. I guess `recenter` moves point, whereas we want to move the window.

**Comment by capitaomorte** [comment]
`recenter` doesn't move point, it does what you want I think:

```
recenter is an interactive built-in function in `C source code'.

(recenter &optional ARG)

Center point in selected window and maybe redisplay frame.
```

**Comment by npostavs** [comment]
> recenter doesn't move point,

Ok, my explanation is wrong, 

> it does what you want I think:

But when I tried `recenter` instead of `redisplay` with the `LatexLetter` snippet, point was at the bottom of buffer while the x prompt was shown (instead of being located at `${1...}`).

**Comment by capitaomorte** [comment]
I gotta try it myself, but I'm really busy lately, no time for any hacking, sorry. Do what you think makes sense
