### ISSUE TITLE
Problem with using transformed mirror fields.

### ISSUE THREAD

**Issue by nitishch** [capitaomorte/yasnippet#624]
For `for` loop, I have the following snippet:
```
for (${1:int var = 0}; ${1:$(extractVar yas-text)} ${2:< n} ; ${1:$(extractVar yas-text)}${3:++}) {
    $0
```

`extractVar` is the following function:

```elisp
(defun extractVar (string)
  (car (cdr (org-split-string (substring-no-properties string)))))
```

What `extractVar` does is it takes the string for example "int varName = 0" and returns the string "varName". 

This snippet looked fine but this doesn't work. When I expand this snippet, it puts the following into the buffer:

```
for (int i = 0; [yas] elisp error: Wrong type argument: stringp, nil < n; [yas] elisp error: Wrong type argument: stringp, nil++) {
```

Note that it prints `int i = 0` in the first field although I put the default value `int var = 0`. In my previous `for` snippet, I had `int i = 0`. This problem persists even after restarting Emacs.

Also, if I try out the snippet with `C-c C-t` in the Snippet buffer with c++-mode as major mode, it works fine. Any idea as to what the problem is?

**Comment by npostavs** [comment]
> Note that it prints int i = 0 in the first field although I put the default value int var = 0. In my previous for snippet, I had int i = 0.

Are you sure you're running the snippet you think you're running? Try making some random changes to make sure.

> Wrong type argument: stringp, nil

Maybe use 
```elisp
(defun extractVar (string)
  (or (car (cdr (org-split-string (substring-no-properties string)))) ""))
```

**Comment by nitishch** [comment]
Until now, I was doing `yas-reload-all` to make changes. I ran `yas-recompile-all` and then `yas-reload-all` and then the problem is solved thought I don't yet understand what caused the problem.

**Comment by npostavs** [comment]
> I ran yas-recompile-all and then yas-reload-all and then the problem is solved

I guess you had a stale `.yas-compiled-snippets.el` file. If you have compiled snippets, then they are loaded instead of the non-compiled versions.
