### ISSUE TITLE
Other trigger keys

### ISSUE THREAD

**Issue by bumbker** [capitaomorte/yasnippet#628]
How do I set up for a key to be the yasnippet trigger key but still do its normal behavior when there is no snippet key before point?  I want "r"  and "j"  to expand snippets but still insert r's and j's when there is no snippet key before point. It was working previously though.  I use:
```elisp
(define-key yas-minor-mode-map (kbd "tab") nil) ;; with <> surrounding tab
(define-key yas-minor-mode-map (kbd "TAB") nil)
(define-key yas-minor-mode-map (kbd "r") 'yas-expand)
(define-key yas-minor-mode-map (kbd "j") 'yas-expand)   ;; just C-x C-e ing them in a file
```
Now the only problem is I cannot type r's and j's  and insert r's and j's  when I just want an r or j
But previously it was doing what I want  and I do have this in my yasnippet.el:
`(defcustom yas-fallback-behavior 'call-other-command etcetera...`
and I noticed  that now it will put in an r or j when I type immediatley after the expansion happens but as soon as I type a space the r and j are disabled they do nothing
actually no,  I can type r's and j's after any character except a space    weird or what????
this trouble started after I created a .emacs file with a couple global-set-key 's for macros
I have deleted the .emacs file so I'm starting off of .emcs.d/init.el  again but the problem persists

**Comment by npostavs** [comment]
> It was working previously though.

Seems to be working for me still.

> this trouble started after I created a .emacs file with a couple global-set-key 's for macros

Does it happen starting from `emacs -Q`?

**Comment by bumbker** [comment]
I can't seem to get into yas-minor-mode even, if I start from emacs -q How do I do that?

**Comment by bumbker** [comment]
Got it all loaded up again on my other laptop and it's doing fine on that one.  I guess I don't dare create a .emacs file on it.  I did that as an experiment 'cause the macros didn't seem to be loading up from the .emac.d/init  I'm still pretty new at this stuff though.  I'm thinking that I wish I were able to just make a big elisp program for my project.  I'm just using # command:  type snippets.  Basically, I just need abbreves plus move the cursor before and/or after expansion .  How does one set up  functions that can be called out of nowhere by a defined key sequence?   if that's not awfully complicated and if you don't mind me asking?   Yep, I'm fishing around for any and all help and info,  but whatever help I get is greatly appreciated.  I'm going into a years long project and I must be certain of my tools so I know I won't have to change everything in the middle. And I surely want to keep it all within Emacs so as not to fear an O.S. upgrade breaking my Autokey or something.  Plus it's just more efficient when it's all inside Emacs.

**Comment by bumbker** [comment]
O.K.  I started with emacs -q and loaded yasnippet.el and  activated yas-minor-mode  and triggered snippets with tab key and evaluated the (define-key lines  and triggered a snippet with the r key and still the same problem.  I can only type an r  (or j) in a word  and not after a space. ???  And I don't have to expand a snippet first the problem is there as soon as I evaluate the lines such as:
(define-key yas-minor-mode-map (kbd "r") 'yas-expand)  If I C-x C-e this line , whether or not I've made the tab key 'nil yet ,  If I make the r 'yas-expand  It  causes the r to do nothing after a space.  
Only after a space

**Comment by npostavs** [comment]
> I can't seem to get into yas-minor-mode even, if I start from emacs -q How do I do that?

Hi, see https://github.com/capitaomorte/yasnippet#important-note-regarding-bug-reporting which explains about this (please complain if it's not clear).

Also, could you try to break your posts into more paragraphs. They're kind scary-wall-of-text at the moment.

**Comment by bumbker** [comment]
I fixed it !!!!  This is embarrassing but I should tell you what happened.  I was working too fast and I ended up with snippet file that defines a space as the key of a snippet that does nothing.  So when I tried to type r after space it was just expanding that nothing snippet.  My apologies and thanks for all your good work
