### ISSUE TITLE
LaTeX environment wrapping around selection and allowing parameters

### ISSUE THREAD

**Issue by paaguti** [capitaomorte/yasnippet#633]
A LaTEX \begin{env} \end{env} should 
1.allow parameters like in
\begin{env}[parameters]
...
\end{env}

and
2. wrap around a selected region

Diff attached
[yasnippet-begin.txt](https://github.com/capitaomorte/yasnippet/files/46529/yasnippet-begin.txt)

**Comment by npostavs** [comment]
> Diff attached

In general, please inline the diff (wrapped in ```` ``` ```` markers), or send a pull request.

```diff
diff --git a/snippets b/snippets
--- a/snippets
+++ b/snippets
@@ -1 +1 @@
-Subproject commit 247fd0461164f49a0aff4999ed3ee77a8c38846a
+Subproject commit 247fd0461164f49a0aff4999ed3ee77a8c38846a-dirty
```

It looks like you made a change to the snippets submodule, so you need to `cd` into that directory to get the actual diff. Send it to http://github.com/AndreaCrotti/yasnippet-snippets (see https://github.com/capitaomorte/yasnippet#where-are-the-snippets).
