### ISSUE TITLE
Symbol's function definition is void: yas-global-mode

### ISSUE THREAD

**Issue by rschuetzler** [capitaomorte/yasnippet#634]
Updated yasnippet to version 20151126.518 on Windows and now I'm getting a warning that `yas-global-mode` is void. Has something changed in the initialization of yasnippet?

**Comment by npostavs** [comment]
> I'm getting a warning

Warning or error? If an error, can you `toggle-debug-on-error` (or start Emacs with `--debug-init` if it happens in your init file) and post the bactrace?

If a warning, where is the warning coming from exactly? Byte compilation?

> Has something changed in the initialization of yasnippet?

Shouldn't have, I think.

**Comment by rschuetzler** [comment]
After debugging, I just removed the yasnippet package and reinstalled it. That seems to have corrected the issue.
