### ISSUE TITLE
# expand-env: ((yas-wrap-around-region t)) seems not to work correctly

### ISSUE THREAD

**Issue by paaguti** [capitaomorte/yasnippet#636]
Hi,

in Latex mode, I have defined the following snippet:

```
# -*- mode: snippet -*-
# name: \begin{figure} ... \end{figure}
# key: figure
# expand-env: ((yas-wrap-around-region t))
# --
\begin{figure}${1:[${2:h!t}]}
\centering
$0
\caption{${3:\label{fig:${4:label}}}${5:Caption}}
\end{figure}
```
when I expand without a selected region it works fine. However, when I have an include graphics command like:

```
\includegraphics[width=.9\textwidth]{one-packet}
```

in the selected region and I expand the snippet (from the menu), the selected region gets crippled.

**Comment by npostavs** [comment]
> the selected region gets crippled.

I don't know what "crippled" means. It's better if you show expected result, and actual result.

This may be related to #523.

**Comment by paaguti-work** [comment]
OK, 
1. include the snippet in your latex-mode snippets directory
2. create a new file:
`emacs kk.tex`
and paste the following:
```


\includegraphics[width=.9\textwidth]{pepe}

```
Now select from the line before the \includegraphics to the line after and apply the snippet. You should be seeing:
```
\begin{figure}[h!t]
  \centering
  
  \includegras[width=.9\width{
      
      \cation{${3:\label{fig:${4:label}}}${5:Caption}}
\end{figure}
```
However, I'd be expecting something like
```
\begin{figure}[h!t]
  \centering

  \includegraphics[width=.9\textwidth]{pepe}
  \caption{\label{fig:label}Caption}
\end{figure}
```

**Comment by paaguti** [comment]
For the moment being, I have found a work-around: removing the `expand-env` line and including the selection before `$0` with: 
```
`(yas-selected-text)`
```
However, the bug needs to be solved, IMvHO
