### ISSUE TITLE
escaping `<$>`

### ISSUE THREAD

**Issue by yaxu** [capitaomorte/yasnippet#640]
I can't seem to escape the string `<$>` in a snippet, which is awkward as it's an operator in Haskell.

* `<$>` gives `<`
* `<\$>` gives `<`
* `<\\$>` gives `<\'
* `<\$\>` gives `<$\>"
* `<\$<` gives `<$<`

The last one suggests it's something to do with the combination of `$` and `>`.

**Comment by npostavs** [comment]
> The last one suggests it's something to do with the combination of $ and >.

Yes, `$>` is used as an indentation marker, which is documented at... hmm, it's not documented :(

And it doesn't look like there is any way to escape it, it's processed in `yas--indent` which is called after everything has been parsed and expanded.

**Comment by yaxu** [comment]
Thanks for confirming that @npostavs 
So this line is the problem:
  https://github.com/capitaomorte/yasnippet/blob/master/yasnippet.el#L3891

Maybe this would be an improvement:
`(while (re-search-forward "(^|[^\\])$>" nil t)`

i.e., search for `$>` that comes after either the start of a line, or a character that isn't `\`. That would mean that `\\$>` wouldn't be matched, however.

**Comment by sabof** [comment]
Things have been unescaped by that point though. Meaning the problem can't be resolved within `yas--indent` since both "\$>" and "$>" look like "$>".

**Comment by npostavs** [comment]
Proposed fix at #686, `<\$>` should give `<$>`.
