### ISSUE TITLE
Can not change the next-field keybinding

### ISSUE THREAD

**Issue by azer** [capitaomorte/yasnippet#641]
When I'm jumping to next field, I'd like to hit SPACE button instead of TAB button, because it conflicts with auto-complete. I can't see any documentation for how to change key bindings using elisp. any ideas? 

Here is my config;

```elisp
(define-key yas-minor-mode-map [(tab)]        nil)
(define-key yas-minor-mode-map (kbd "TAB")    nil)
(define-key yas-minor-mode-map (kbd "<tab>")  nil)
```

**Comment by azer** [comment]
figured out later

**Comment by npostavs** [comment]
For the record it is `yas-keymap`, which is sort of mentioned at http://capitaomorte.github.io/yasnippet/faq.html#sec-4, the docs could probably be improved.

**Comment by azer** [comment]
I didn't see the docs, thanks

**Comment by azer** [comment]
could you add the link of the docs as website url to the repo @npostavs @capitaomorte ?

**Comment by npostavs** [comment]
[README.mdown#L106](https://github.com/capitaomorte/yasnippet/blame/71f0142edae6196535bfc27b79f317dc7a12ea1d/README.mdown#L106)
[README.mdown#L164](https://github.com/capitaomorte/yasnippet/blame/71f0142edae6196535bfc27b79f317dc7a12ea1d/README.mdown#L164)

Or did you mean something else?

**Comment by capitaomorte** [comment]
I think I know... Done

It's the github project website link near the project description.
