### ISSUE TITLE
Iterate inside template?

### ISSUE THREAD

**Issue by saritasa** [capitaomorte/yasnippet#642]
I'm new to emacs/LISP and would like guidance how to achieve the following output

I'd like to type
"color glass hat sport" in a single string ($1) that will be converted to the following:

```python
    Color = "C"
    Glass = "G"
    Hat   = "H"
    Sport = "S"
 
    _CATEGORIES = (
        (Color, 'Colors'), (Glass, 'Glasses'), (Hat, 'Hats'), (Sport, 'Sports'),
    )
```

How to achieve that with YAS Snippets?

**Comment by npostavs** [comment]
Yasnippet provides ["mirror" transformations][m] so you can transform what you type with an arbitrary piece of elisp. You could structure the snippet like this:

```
# -*- mode: snippet; require-final-newline: nil -*-
# name: categories
# key: cat
# --
$1
${1:$(transform-1 yas-text)}

_CATEGORIES = (           
    ${1:$(transform-2 yas-text)}
)
```

You would have "color glass hat sport" still left in the buffer after the snippet finishes though. Possibly after #28 is implemented you could delete it automatically.

It remains to write functions `transform-1` and `transform-2` to turn `color glass hat sport` into the strings you want. `transform-1` could be defined like this:
```elisp
(defun transform-1 (string)
  (mapconcat (lambda (word)
               (setq word (capitalize word))
               (format "%-5s = \"%.1s\"" word word))
             (split-string string)
             "\n"))
```
I used the sloppy way of aligning the `=` signs, which will work as long as your words are no longer than 5 letters.

[m]: http://capitaomorte.github.io/yasnippet/snippet-development.html#sec-3-6

**Comment by saritasa** [comment]
thank you very much for your guidance! I'll try to implement it this way and will post here once done
