### ISSUE TITLE
Typing doesn't clear snippet field when org-mode is active

### ISSUE THREAD

**Issue by jpeloquin** [capitaomorte/yasnippet#644]
When a snippet with a default-valued field is triggered when org-mode is active, typing characters into the field does not clear the default value.

(This report applies to the 20160104.129 version off MELPA.)

To reproduce, trigger this snippet in a `.org` file:

```
# -*- mode: snippet -*-
# name: src
# key: src
# --
#+begin_src ${1:lang} ${2:options}
$0
#+end_src
```

The buffer will contain this, with `lang` active (highlighted):

```
#+begin_src lang options

#+end_src
```
At this point typing `foo` should produce

```
#+begin_src foo options

#+end_src
```
but actually produces
```
#+begin_src foolang options

#+end_src
```

Undoing the changes in 17fe7904ae422a5ae4ddfd561fc506c2791bdb18 fixes this issue.
The problem appears to be that org-mode (version 24.5.1, anyway) rebinds keys to `org-self-insert-command` rather than `self-insert-command`.

**Comment by capitaomorte** [comment]
@npostavs see my comment in #639, and the https://github.com/capitaomorte/yasnippet/commit/ad5396d1591fb605823bd34475d2750ce1402628 commit which might be useful to solving this problem.

**Comment by npostavs** [comment]
> Undoing the changes in 17fe790 fixes this issue.

I was kind of thinking in the back of my mind that #639 might lead to some kind of trouble. Thanks for your report, now we have a concrete problem to look at.

I'm proposing to use the same criteria as `delete-selection-mode`, see #645 (it's not working for `yank` though).

**Comment by capitaomorte** [comment]
I think #645 is a fine idea!

**Comment by dahanbn** [comment]
I have the same issue in Markdown mode as well. The default value of a snippet field doesn't get overwritten if I type in a new value. I use the version 20160104.129 as well.

In elisp mode the replacement of the default value is working.
