### ISSUE TITLE
When I'm using org-mode, it loads the text-mode snippets

### ISSUE THREAD

**Issue by Sunkworld** [capitaomorte/yasnippet#647]
When I'm editing .org files, yas only loads the snippets of text-mode, I tried to reinstall the plugin and delete the unrelated parts in my .emacs, however, the issue persists. I wonder where's the problem.
This is how my .emac file:
> (add-to-list 'load-path
> 	       "~/.emacs.d/plugins/yasnippet")
> (require 'yasnippet)
> (yas-global-mode 1)

and this is what happened when I opened a .org file:
> [yas] Loading snippet files from /Users/Yuuko/.emacs.d/plugins/yasnippet/snippets/text-mode

**Comment by npostavs** [comment]
The reason is that `org-mode` is a descendant of `text-mode` (via `outline-mode`) so it inherits text-mode's snippets too. See also #580.

**Comment by capitaomorte** [comment]
@npostavs, I think @Sunkworld is reporting that it _only_ loads `text-mode` snippets, which is strange, since at least in the git and melpa installation methods there are `org-mode` snippet bundled. 

@Sunkworld how did you install yasnippet?

**Comment by npostavs** [comment]
Oh, you're right, the OP does say "yas only loads the snippets of text-mode". But I didn't see that when I tried myself.

> and this is what happened when I opened a .org file:
> 
>> [yas] Loading snippet files from /Users/Yuuko/.emacs.d/plugins/yasnippet/snippets/text-mode

That is what shows in the minibuffer, but the messages regarding loading org-mode snippets are in the `*Messages*` buffer:
```
(New file)
[yas] Loading for `org-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote c:/Users/npostavs/src/yasnippet/snippets/org-mode) (quote org-mode)))!
[yas] Loading snippet files from c:/Users/npostavs/src/yasnippet/snippets/org-mode
[yas] Loading for `text-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote c:/Users/npostavs/src/yasnippet/snippets/text-mode) (quote text-mode)))!
[yas] Loading snippet files from c:/Users/npostavs/src/yasnippet/snippets/text-mode
```

@Sunkworld: if you can show a case of not loading the org-mode snippets starting from `emacs -Q` I will reopen.

**Comment by Sunkworld** [comment]
It turns out to be my typo in using the org-mode snippets…Sorry for that…

**Comment by PetersonLian** [comment]
For my case ,  I  used same snippets name.
