### ISSUE TITLE
[yas] Reloaded everything (snippets will load just-in-time)... (some errors, check *Messages*).

### ISSUE THREAD

**Issue by outsinre** [capitaomorte/yasnippet#648]
Emacs 24.5.1, yasnippet-0.9.0.1 installed through ELPA. During startup, I got "some errors, check *Messages*)":

```
[yas] Prepared just-in-time loading for /home/zachary/.emacs.d/elpa/elpy-1.10.0/snippets/
[yas] Discovered there was already *scratch* in fundamental-mode
[yas] Discovered there was already  *code-conversion-work* in fundamental-mode
[yas] Discovered there was already  *load* in fundamental-mode
[yas] Discovered there was already  *Echo Area 0* in fundamental-mode
[yas] Discovered there was already  *Echo Area 1* in fundamental-mode
[yas] Discovered there was already  *load*-658543 in fundamental-mode
[yas] Loading for `fundamental-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/zachary/.emacs.d/elpa/yasnippet-0.9.0.1/snippets/fundamental-mode) (quote fundamental-mode)))!
[yas] Loading compiled snippets from /home/zachary/.emacs.d/elpa/yasnippet-0.9.0.1/snippets/fundamental-mode
Loading /home/zachary/.emacs.d/elpa/yasnippet-0.9.0.1/snippets/fundamental-mode/.yas-setup...done
[yas] Prepared just-in-time loading for /home/zachary/.emacs.d/elpa/yasnippet-0.9.0.1/snippets
[yas] Check your `yas-snippet-dirs': ~/.emacs.d/snippets is not a directory
[yas] Reloaded everything (snippets will load just-in-time)... (some errors, check *Messages*).
```

**Comment by capitaomorte** [comment]
Well, did you check your `yas-snippet-dirs`? What is the value in that variable? Use 
```C-h v RET yas-snippet-dirs RET```

**Comment by outsinre** [comment]
capitaomorte, `C-h v RET yas-snippet-dirs RET` shows:

    ("~/.emacs.d/snippets" yas-installed-snippets-dir "/home/zachary/.emacs.d/elpa/elpy-1.10.0/snippets/")

**Comment by outsinre** [comment]
After creating an empty `"~/.emacs.d/snippets"` directory, the `*Message*` buffer looks:

ad-handle-definition: `ido-completing-read` got redefined
[yas] Prepared just-in-time loading for /home/zachary/.emacs.d/elpa/elpy-1.10.0/snippets/
[yas] Discovered there was already *scratch* in fundamental-mode
[yas] Discovered there was already  *code-conversion-work* in fundamental-mode
[yas] Discovered there was already  *load* in fundamental-mode
[yas] Discovered there was already  *Echo Area 0* in fundamental-mode
[yas] Discovered there was already  *Echo Area 1* in fundamental-mode
[yas] Discovered there was already  *load*-271162 in fundamental-mode
[yas] Loading for `fundamental-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/zachary/.emacs.d/elpa/yasnippet-0.9.0.1/snippets/fundamental-mode) (quote fundamental-mode)))!
[yas] Loading compiled snippets from /home/zachary/.emacs.d/elpa/yasnippet-0.9.0.1/snippets/fundamental-mode
Loading /home/zachary/.emacs.d/elpa/yasnippet-0.9.0.1/snippets/fundamental-mode/.yas-setup...done
[yas] Prepared just-in-time loading for /home/zachary/.emacs.d/elpa/yasnippet-0.9.0.1/snippets
[yas] Prepared just-in-time loading for ~/.emacs.d/snippets
[yas] Reloaded everything (snippets will load just-in-time)....
For information about GNU Emacs and the GNU system, type C-h C-a.

---
I am not sure such output is normal to `yasnippet` package.

**Comment by capitaomorte** [comment]
It's pretty normal, if perhaps a little verbose. @npostavs should we close this or investigate if ~/.emacs.d/snippets should be automatically created?

**Comment by npostavs** [comment]
> investigate if ~/.emacs.d/snippets should be automatically created?

Yeah, I think this makes sense, `yas-new-snippet` doesn't work so great without this this directory either.
