### ISSUE TITLE
Haskell-mode pragma snippet is a huge pain with autopairing braces

### ISSUE THREAD

**Issue by kozross** [capitaomorte/yasnippet#659]
As someone who programs in several curly-brace languages *as well as* Haskell, the pragma snippet of '{' is really annoying for me to use, as I have autopair for curly braces on. Would it be possible to change it to something that doesn't clash with autopairing curly braces?

**Comment by npostavs** [comment]
Yasnippet dooesn't supply any snippets, see https://github.com/AndreaCrotti/yasnippet-snippets, for haskell there is also https://github.com/haskell/haskell-snippets
