### ISSUE TITLE
Conflict with org-src-tab-acts-natively

### ISSUE THREAD

**Issue by mankoff** [capitaomorte/yasnippet#660]
The following template works fine if `org-src-tab-acts-natively` is set to `nil`. If `org-src-tab-acts-natively` is `t`, then the second `$1.png` is ignored, that text is instead inserted where `HERE` appears, and `$0` is also ignored.

Is it possible to have yasnippet and Org play nicely here? I've been able to recreate this with yasnippet-20160131.948 from elpa and the current Org git head (8.3.3).

```
# -*- mode: snippet; require-final-newline: nil -*-
# name: test
# key: yatest_
# --
#+NAME: fig:$1
#+BEGIN_SRC python :results file :exports results :session foo
HERE
  import numpy as np

  $0

  plt.savefig('fig.png', transparent=True, bbox_inches='tight')
  '$1.png'

#+END_SRC
#+RESULTS: fig:$1

```

**Comment by npostavs** [comment]
> I've been able to recreate this with yasnippet-20160131.948 from elpa and the current Org git head (8.3.3).

I don't see the problem with latest yasnippet and org released with Emacs 24.5 (8.2.10), can you confirm this is org 8.3 specific?

**Comment by mankoff** [comment]
I'm actually unable to recreate this on further testing. Sorry for the bad report. I'll resubmit if I can give a more complete MWE.

**Comment by npostavs** [comment]
This was reported again at #761, I managed to reproduce it. Looks like `org-src-fontify-natively` is required as well.
