### ISSUE TITLE
yasnippet placeholder incompatible with paredit

### ISSUE THREAD

**Issue by stardiviner** [capitaomorte/yasnippet#662]
I defined a snippet like this:
```
# -*- mode: snippet -*-
# name: do
# key: do
# group: do.do
# --
(do (${1:(${2:var} ${3:init-form} ${4:step-form})})
    (${5:(end-test-form)} ${6:(result-form*)})
  ${0:statement*})
```

After input `(` in `step-form` placeholder:
Here is the result:
```
(do ((i 0 () step-form))
    ((end-test-form) (result-form*))
  statement*)
```

I tested with disable `paredit` mode. Then it can work.
Is there a way to fix this problem?

**Comment by capitaomorte** [comment]
Last time I checked paredit was very aggressive in the way it manipulated text and text properties. I personally recommend you use `electric-pair-mode` instead. As for this problematic interaction, I don't know if there's anything yasnippet can do about it, but I can have a look later.

**Comment by npostavs** [comment]
You can "fix" this with `(put 'paredit-open-round 'delete-selection t)`. You probably don't want that setting if you actually use `delete-selection-mode` though. We might need a list of "clearing" commands for `yas--skip-and-clear-field-p` to check, in addition to piggy-backing on delete-selection commands.

**Comment by npostavs** [comment]
Same problem without `paredit`, using `insert-parenthesis` (<kbd>M-(</kbd>).

**Comment by capitaomorte** [comment]
> Same problem without paredit, using insert-parenthesis (M-()

@npostavs is the problem that the field is not being cleared?  is that it? I don't understand stardiviners explanation properly, but that seems to be it.

If that's the case I wouldn't mind a solution where we say "only the commands that have `delete-selection` or `yas-delete` non-nil will clear fields". We set `yas-delete` on a handful of built-in emacs commands that don't already have `delete-selection` and then advise other packages authors to do the same for their commands.

**Comment by npostavs** [comment]
> is the problem that the field is not being cleared? is that it?

Yes, that's my understanding.

> If that's the case I wouldn't mind a solution where we say "only the commands that have delete-selection or yas-delete non-nil will clear fields".

Actually, I had a different idea inspired by recent discussion in https://github.com/capitaomorte/yasnippet/pull/678#discussion_r59508605: instead of checking the command's properties, just check if it's inserting text according to the modification hook `length` parameter. I'll push some code later today.

**Comment by capitaomorte** [comment]
> Actually, I had a different idea inspired by recent discussion in #678 (comment): instead of checking the command's properties, just check if it's inserting text according to the modification hook length parameter. I'll push some code later today.

In that case, we'll lose per-command control, right? But I don't mind, it's a good and simple idea, so your call.

**Comment by npostavs** [comment]
> In that case, we'll lose per-command control, right?

Yes, hopefully we don't need it. The less configuring the better. If it really turns out it's needed, we can add a `yas-delete` property, but I'll wait until there's a clear need for it.

> I'll push some code later today.

See #680.

**Comment by stardiviner** [comment]
@npostavs Your patch fixed my issue. Tested ok. Thanks.
