### ISSUE TITLE
Anonymous command just after entering a field throws an error.

### ISSUE THREAD

**Issue by debug-ito** [capitaomorte/yasnippet#664]
Invoking an anonymous command just after entering a field throws an error. Here, "anonymous command" is a lambda function with `(interactive)` inside.

For example, set the following in your .emacs (I have many bindings of this kind!)

```elisp
(global-set-key (kbd "C-c h") (lambda () (interactive) (insert "hoge")))
(yas-global-mode 1)
```

Then, open "hoge.c" and type "if\<TAB\>". The result would be below with "condition" selected.

```c
if (condition) {
  
 }
```

Then, type "C-c h". This leads to the following error.

```
let: Wrong type argument: symbolp, (lambda nil (interactive) (insert "hoge"))
```

This is because the variable `this-command` is set to the anonymous function when it's inspected in `yas--skip-and-clear-field-p`. In `yas--skip-and-clear-field-p`, `this-command` is checked by `commandp`, but `commandp` returns `t` for functions (and even strings!). On the other hand, `get` only accepts symbols, thus it throws an error.

I suggest ensuring that the argument to `get` is always a symbol, because the content of `this-command` (and `this-original-command`, too?) can be practically anything.

**Comment by debug-ito** [comment]
The `yas--skip-and-clear-field-p` I'm talking about was introduced in #645

**Comment by npostavs** [comment]
Thanks for the report and analysis.
