### ISSUE TITLE
question: indentation of multiline transform mirror in snippet

### ISSUE THREAD

**Issue by mbriggs** [capitaomorte/yasnippet#665]
Hi,

I have a snippet where a mirror turns a single line field into a multiline one via elisp. The multiline field is currently not indenting past the first line, would love to know if there is a way to make that work

snippet in question: 

```
def initialize(${1:params})
  ${1:$(mb/ruby-initialize-args yas-text)}
end
```

```lisp
; uses s.el and dash.el
(defun mb/ruby-initialize-args (args)
  (string-join (--map (concat "@" it " = " it) (s-split ", " args)) "\n"))
```

results in

```ruby
  def initialize(foo, bar, bin)
    @foo = foo
@bar = bar
@bin = bin
  end
```

thanks for the help!

**Comment by capitaomorte** [comment]
I can tell you straight up this is hard to do cleanly, but you can try reading the current indentation (in the `def initialize`  in the elisp function, and then use that to calculate the amount of whitespace to add to each line but the second. I'll try to come up with a better solution if I find the time...

**Comment by mbriggs** [comment]
thats a good idea, thanks :) its kind of a corner case, but its the sort of thing that really flexes the power of having elisp transforms.

I would offer to PR, but it seems like the whole copyright assignment business would be hela-overkill for something this trivial

**Comment by capitaomorte** [comment]
what would you be PR'ing to, @mbriggs?

**Comment by capitaomorte** [comment]
... I mean, trivial changes can go without copyright assignment perfectly. I just didn't understand what trivial change you want to perform in yasnippet. You are aware that the snippets themselves are not a part of yasnippet anymore, right?

**Comment by mbriggs** [comment]
without looking at the code, I am assuming that there is a way to handle this from within yasnippet either with a) a small modification to the existing indentation code, or b) a new indentation strategy. By that comment what i meant was that i would be fine spending a bit of time looking at that, but that doesnt feel like enough investment in the project to warrant getting forms filled out by my boss and going back and forth with the FSF :) I said it mostly because i kind of felt guilty about not offering a patch for this, since yasnippet is something i use MANY times a day and have for quite awhile. If you think it wouldnt require that to fix the problem for myself, I'll get it working and do the patch.

**Comment by capitaomorte** [comment]
I think you overestimate the complications regarding copyright assignment. I contribute in my free time, I didn't need my boss to assign anything. Nowadays I think it doesn't take snail-mail at all, just a scanned copy of a letter with your signature on it.

I also think you underestimate the effort in adapting Yasnippet to a new "new indentation strategy". I would love to be proven wrong.

Somewhere in between you might want to contribute.

**Comment by capitaomorte** [comment]
@npostavs, this fix I committed seems to be breaking a silly apparently unrelated test, otherwise good to go. Have a look at the backtrace, I seem to remember you having come across it.

@mbriggs, can you give the `issue-665-multiline-mirror-indentation` some testing?

**Comment by npostavs** [comment]
> Have a look at the backtrace, I seem to remember you having come across it.

It seems to be tickling one of those cc-mode parsing edge cases, hard to say why.

By the way, you shouldn't use `ert-simulate-command` on `yas-mock-insert`, because it's already calling `ert-simulate-command` inside.

**Comment by npostavs** [comment]
> It seems to be tickling one of those cc-mode parsing edge cases, hard to say why.

It can be avoided by clearing the buffer during `yas-should-expand` instead of narrowing. 

Without this, we attempt to expand a `printf` snippet when in C mode, but with point in the middle of some Lisp code, which hardly seems like a useful test case.

```diff
diff --git i/yasnippet-tests.el w/yasnippet-tests.el
index 0d818c7..3ba790c 100644
--- i/yasnippet-tests.el
+++ w/yasnippet-tests.el
@@ -877,7 +877,7 @@ (ert-deftest test-yas-activate-extra-modes ()
 (defun yas-should-expand (keys-and-expansions)
   (dolist (key-and-expansion keys-and-expansions)
     (yas-exit-all-snippets)
-    (narrow-to-region (point) (point))
+    (erase-buffer)
     (insert (car key-and-expansion))
     (let ((yas-fallback-behavior nil))
       (ert-simulate-command '(yas-expand)))
```

**Comment by npostavs** [comment]
> By the way, you shouldn't use ert-simulate-command on yas-mock-insert, because it's already calling ert-simulate-command inside.

> It can be avoided by clearing the buffer during yas-should-expand instead of narrowing.

I've rewritten `issue-665-multiline-mirror-indentation` to account for these.

**Comment by capitaomorte** [comment]
> I've rewritten issue-665-multiline-mirror-indentation to account for these.

No prob, though adding a commit would also have been fine. Without learning this from this issue, I wondered what had happened. IMO it's better not to rewrite reasonably "published" branches.

**Comment by npostavs** [comment]
Yeah, I obviously should have just pushed a new branch, now I'm not sure why I didn't do that.
