### ISSUE TITLE
Are the two hooks(yas-before-expand-snippet-hook and yas-after-exit-snippet-hook) called in pair？

### ISSUE THREAD

**Issue by netjune** [capitaomorte/yasnippet#667]
It seems not sometimes.

**Comment by npostavs** [comment]
I'm not sure what the specific problem being reported here is.

**Comment by netjune** [comment]
> 在 2016年3月16日，11:22，Noam Postavsky <notifications@github.com> 写道：
> 
> I'm not sure what the specific problem being reported here is.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/capitaomorte/yasnippet/issues/667#issuecomment-197133021>
I want to disable something(like auto completion) in yas-before-expand-snippet-hook by setting a flag 
and re-enable them in yas-after-exit-snippet-hook by clear the flag. But the flag was not always cleared.

**Comment by capitaomorte** [comment]
@npostavs , my slightly lazy 2 cents: entering and exiting snippet hooks have always been a problem. This use case looks legitimate enough. I don't have time right now to review it, but a possible exploration can be to use a transient minor mode much like `completion-in-region-mode`. Look at in Emacs's minibuffer.el.

**Comment by npostavs** [comment]
> But the flag was not always cleared.

Okay, we need to know under which circumstances it wasn't cleared. And also double check that this problem still occurs with the latest yasnippet (since you mentioned in #666 that you were using 0.8.0).

**Comment by npostavs** [comment]
Closing, report is too vague. If you can demonstrate a specific case where something goes wrong, we can reopen.

https://github.com/capitaomorte/yasnippet#important-note-regarding-bug-reporting
