### ISSUE TITLE
when yas-global-mode is on, how to disable yasnippet for certain major modes?

### ISSUE THREAD

**Issue by introom** [capitaomorte/yasnippet#669]
I tried:
  (setq yas-dont-activate #'(lambda () (null (yas--get-snippet-tables))))

but it doesn't work.

**Comment by introom** [comment]
I'd like to achieve the effect that only when there is (active) snippets for the current mode then enable yas, meanwhile without manually specifying the mode hooks.
A little bit flavor of the `(setq yas-dont-activate #'(lambda () (null (yas--get-snippet-tables))))', which sadly doesn't work.

**Comment by npostavs** [comment]
> I'd like to achieve the effect that only when there is (active) snippets for the current mode then enable yas,

Oh. Well you can't use `yas-dont-activate` for that because it runs before `yas-minor-mode` has turned on, so the active snippet tables are still unknown. Perhaps try
```elisp
(defun disable-yas-if-no-snippets ()
  (when (and yas-minor-mode (null (yas--get-snippet-tables)))
    (yas-minor-mode -1)))
(add-hook 'yas-minor-mode-hook #'disable-yas-if-no-snippets)
```

**Comment by introom** [comment]
thanks for that.
