### ISSUE TITLE
Snippets for minor modes

### ISSUE THREAD

**Issue by Profpatsch** [capitaomorte/yasnippet#670]
I wonder if I can create snippets that are bound to minor modes?

My use case is that `maven` uses `pom.xml` files with predefined `dependency` tags and I want to be able to insert them via snippet, but not define those for nxml-mode, rather for a minor `maven-mode` which I enable in the right files.

**Comment by npostavs** [comment]
Try calling `yas-activate-extra-mode` in `maven-mode-hook`

**Comment by Profpatsch** [comment]
It worked, thanks!
