### ISSUE TITLE
yasnippet stops compile error highlighting

### ISSUE THREAD

**Issue by jeffpollock9** [capitaomorte/yasnippet#672]
Hello,

I was pointed to making a report here from: 

http://emacs.stackexchange.com/questions/21377/yasnippet-stops-compile-error-highlighting

In short, if I reduce my .emacs file to:
````
(require 'package)
(add-to-list
 'package-archives
 '("melpa" . "http://melpa.org/packages/")
 t)
(package-initialize)

(require 'yasnippet)
(yas-global-mode 1)
````

then `M-x compile` does not highlight errors (pictures shown in link above). Any suggestions?

I've reproduced this on my home and work computers, currently with: emacs 24.5.1, yasnippet 0.8.0

Thanks,
Jeff

**Comment by npostavs** [comment]
> yasnippet 0.8.0

Can you check if it reproduces with the latest yasnippet from git/MELPA? I do intend to update GNU ELPA repository Real Soon Now, but meanwhile 0.8.0 is actually quite old.

**Comment by jeffpollock9** [comment]
Many thanks for the reply, @npostavs 

I cloned the git repo and now everything works perfectly - along with me feeling stupid for not doing that in the first place!

Jeff

**Comment by npostavs** [comment]
Thanks for checking. By the way, I've just now pushed `0.9.1` to GNU ELPA, so it should be available from there soon (a day or so?).
