### ISSUE TITLE
Weird issues since cleanup commit 18f7b1

### ISSUE THREAD

**Issue by syl20bnr** [capitaomorte/yasnippet#673]
Hey guys,

Bear with me since I have no repro steps but I will try to explain the symptoms clearly enough for you to find a solution.

First I'm pretty sure it does not come from Spacemacs config but OTOH if I `emacs -Q` and require yasnippet the symptoms does not appear.

Here are the symptoms:
- Starting Emacs gives `(void-function yas--load-pending-jits)`
- So I tried with `emacs -Q` --> works
- Then I removed some configuration of Yasnippet from Spacemacs, still the error
- The error seems to be triggered as soon as I add `yas-minor-mode` to `emacs-lisp-mode-hook`
- I dug into `yasnippet.el` and move around some code, namely moving `yas--load-pending-jits` before `define-minor-mode` and the error disappeared and was replaced by another missing symbol used in `yas--load-pending-jits`
- This was pulling an endless string so I put the definition of the minor mode at the end of the file and then I got a `Recursive load` error.

Sorry for lacking a repro step, I will try to add one at some point. I hope this description of the symptoms will be enough and most importantly I hope to learn why those errors are triggered.

cc @monnier @npostavs

EDIT: these errors let a dangling hook in post-command-hook and prevent Emacs from being usable.

**Comment by npostavs** [comment]
Oh, I think see what it is.  The change below creates a buffer in `emacs-lisp-mode` *while loading yasnippet.el*, creating this buffer starts `yas-minor-mode` (if you've added it to the hook), but yasnippet.el isn't completely loaded yet.

```diff
 (defvar yas--font-lock-keywords
   (append '(("^#.*$" . font-lock-comment-face))
-          lisp-font-lock-keywords-2
+          (with-temp-buffer
+            (emacs-lisp-mode)
+            (font-lock-set-defaults)
+            (if (eq t (car-safe font-lock-keywords))
+                ;; They're "compiled", so extract the source.
+                (cadr font-lock-keywords)
+              font-lock-keywords))
```

**Comment by syl20bnr** [comment]
Makes sense, thank you for the quick response. In the mean time we switched temporarily to the last stable version.

**Comment by syl20bnr** [comment]
Proposed fix in #674 
Note that I did not have signed the paper yet so feel free to amend the author, just merge it quick if the fix is adequate.

**Comment by npostavs** [comment]
I'm thinking a smaller fix, like #676. Can you try that out and confirm it works? I was using `(add-hook 'emacs-lisp-mode-hook 'yas-minor-mode) (require 'yasnippet)` as a reproducer, though I'm not 100% sure it's equivalent.

**Comment by syl20bnr** [comment]
Testing it.

**Comment by syl20bnr** [comment]
Fixes the OP error but if a snippet is visited without yasnippet loaded first the following error happens:

```
Ignoring unknown mode `snippet-mode'
File local-variables error: (void-function snippet-mode)
```

**Comment by npostavs** [comment]
I added an `;;;###autoload` cookie to fix that, but it seems the font lock settings don't take effect the first time with this change, hmm...

**Comment by syl20bnr** [comment]
Oh ok, I indeed tested without updating the autoload. LGTM :+1:

**Comment by npostavs** [comment]
> Oh ok, I indeed tested without updating the autoload.

Well yes, because I only added it after you reported the problem :)

There is still the problem of font lock not working the first time.

**Comment by monnier** [comment]
> - The error seems to be triggered as soon as I add `yas-minor-mode` to `emacs-lisp-mode-hook`

Indeed, if you do that before yasnippet.el is loaded we might get
into trouble.  We can probably fix this by appropriately moving things
around (i.e. make sure yas-minor-mode is defined before we do the
with-temp-buffer + emacs-lisp-mode dance), but it's probably preferable
to wrap the call to emacs-lisp-mode inside an ignore-errors.


        Stefan

**Comment by npostavs** [comment]
> wrap the call to emacs-lisp-mode inside an ignore-errors.

Yeah, that seems to work better.
