### ISSUE TITLE
Cursor move at beginning of line when filling a mirrored field and which-function-mode is on

### ISSUE THREAD

**Issue by nicolasdespres** [capitaomorte/yasnippet#677]
Hi and thank you a lot for the great extension yasnippet is!

I have been using it for a couple of years without trouble until now. My problem is kind of weird and most probably comes from a conflict with `(which-function-mode 1)`. Here the scenario:

1. Start emacs
2. Open a new c-header file like `/tmp/test.h`
3. Type `once` at the beginning of the file
4. Press TAB to expand the snippet
5. The default field value should be `TEST_H` and your cursor should be on the first `T` letter
6. Press `f` and *your cursor will move at the beginning of the line* if you keep typing character will be inserted at the beginning of the line and you will exit the snippet.

I am using GNU-Emacs 24.5 on OSX (installed with homebrew). I am using a cloned version of yasnippet release 0.9.1 (6aeccce2f17ac).

I have reduced my `.emacs` file do the minimum:

```elisp
;;; Conf path
(setq emacs-conf-path (expand-file-name "~/.emacs.d/elisp"))
(setq load-path (cons emacs-conf-path load-path))

;; Which function mode
(require 'which-func)
(which-function-mode 1) ;; <--- THIS LINE IS THE CULPRIT

;; Yasnippet
(add-to-list 'load-path (concat emacs-conf-path "/yasnippet"))
(require 'yasnippet)
(yas-global-mode 1)
```

As commented in the `.emacs` file the problem happen only when `(which-function-mode 1)` is on... I have no idea why is this happening.

**Comment by npostavs** [comment]
Thanks for the detailed report. 

I'm getting slightly different behaviour though: after expanding `once`, the snippet exits immediately, leaving point at `TEST_H` (I get normal expansion without `which-function-mode` as well). I see
```
[yas] snippet expanded.
[yas] Comitting snippets. Action would destroy a protection overlay.
[yas] Snippet 0 exited.
```
in `*Messages*`. This is using Emacs 24.5 on GNU/Linux, it would be surprising if underlying OS affects this.

I put a `(debug)` statement in `yas--on-protection-overlay-modification` where the message gets printed, and I got 
```
Debugger entered: nil
  (let ((snippets (yas--snippets-at-point))) (yas--message 3 "Comitting snippets. Action would destroy a protection overlay.") (debug) (let* ((--cl-var-- snippets) (snippet nil)) (while (consp --cl-var--) (setq snippet (car --cl-var--)) (yas--commit-snippet snippet) (setq --cl-var-- (cdr --cl-var--))) nil))
  (if (or yas--inhibit-overlay-hooks after\? (yas--undo-in-progress)) nil (let ((snippets (yas--snippets-at-point))) (yas--message 3 "Comitting snippets. Action would destroy a protection overlay.") (debug) (let* ((--cl-var-- snippets) (snippet nil)) (while (consp --cl-var--) (setq snippet (car --cl-var--)) (yas--commit-snippet snippet) (setq --cl-var-- (cdr --cl-var--))) nil)))
  yas--on-protection-overlay-modification(#<overlay from 15 to 16 in test.h> nil 15 16)
  remove-text-properties(15 16 (category nil))
  c-parse-state()
  c-where-wrt-brace-construct()
  c-defun-name()
  #[nil ... [c-cpp-define-name c-defun-name] 1]()
  byte-code(... [add-log-current-defun-function result case-fold-search add-log-current-defun-header-regexp nil re-search-backward 10000 t match-string-no-properties 1 0 string-match "\\([^ 	\n
\f].*[^ 	\n
\f]\\)"] 4)
  add-log-current-defun()
  which-function()
  byte-code(... [current window which-func-table which-function gethash puthash force-mode-line-update] 5)
  which-func-update-1(#<window 3 on test.h>)
  which-func-update()
  apply(which-func-update nil)
  byte-code(... [timer apply 5 6] 4)
  timer-event-handler([t 0 0 500000 t which-func-update nil idle 0])
```

Since this is triggered by timer, it might explain the discrepancy in observations.  Also I notice `add-log-current-defun`, which reminds me of #666. @netjune: does this look like the same problem as yours?

**Comment by nicolasdespres** [comment]
(sorry for the emoticon I just tried the github feature. I am not sure it was appropriate)

I get this in the `*Messages*` buffer:
```
[yas] snippet expanded.
[yas] Snippet 0 exited.
```

I had a look at `which-function-mode` source code and saw some timer invocation, so we end up with the same diagnostic. Indeed #666 looks like the same issue.

Apologies if I say something trivial because I am not a good `elisp` developer, but `which-function-mode` only interacts in readonly mode with the current buffer (it writes its output in the mode line). I find it weird that it can conflict with yasnippet in such a way.

I would like to be more helpful but I am afraid my `elisp` skills are not enough here.

**Comment by npostavs** [comment]
> Apologies if I say something trivial because I am not a good elisp developer, but which-function-mode only interacts in readonly mode with the current buffer (it writes its output in the mode line). I find it weird that it can conflict with yasnippet in such a way.

It is weird, but looking at the functions in my backtrace, I think what happens is that cc-mode modifies the buffer's text properties to cache parsing results, this modification is what's tripping up yasnippet. So we need to update yasnippet to somehow ignore property only changes.

**Comment by capitaomorte** [comment]
> So we need to update yasnippet to somehow ignore property only changes.

Sounds about right.

**Comment by npostavs** [comment]
@nicolasdespres @netjune please try out #678 to see if it helps.

**Comment by nicolasdespres** [comment]
Apparantly it works for me :). What I did:

```
cd ~/.emacs.d/elisp/yasnippet
git fetch origin pull/678/head:fix-which-func
git checkout fix-which-func
find . -type f -name '*.elc' -delete
# Restart emacs with test configuration
```

Surprising the last line was required...

**Comment by capitaomorte** [comment]
> Surprising the last line was required...

If you don't set `load-prefer-newer` in your configuration, emacs will prefer older ".elc" files than the newer ".el" files that the `git checkout` produced.

**Comment by nicolasdespres** [comment]
Thanks for the tips!

On Thu, Apr 14, 2016 at 11:59 AM, João Távora <notifications@github.com>
wrote:

> Surprising the last line was required...
>
> If you don't set load-prefer-newer in your configuration, emacs will
> prefer older ".elc" files than the newer ".el" files that the git checkout
> produced.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/capitaomorte/yasnippet/issues/677#issuecomment-209859406>
>



-- 
Nicolas Desprès

**Comment by netjune** [comment]
> 在 2016年4月10日，10:05，Noam Postavsky <notifications@github.com <mailto:notifications@github.com>> 写道：
> 
> Thanks for the detailed report.
> 
> I'm getting slightly different behaviour though: after expanding once, the snippet exits immediately, leaving point at TEST_H (I get normal expansion without which-function-mode as well). I see
> 
> [yas] snippet expanded.
> [yas] Comitting snippets. Action would destroy a protection overlay.
> [yas] Snippet 0 exited.
> in *Messages*. This is using Emacs 24.5 on GNU/Linux, it would be surprising if underlying OS affects this.
> 
> I put a (debug) statement in yas--on-protection-overlay-modification where the message gets printed, and I got
> 
> Debugger entered: nil
>   (let ((snippets (yas--snippets-at-point))) (yas--message 3 "Comitting snippets. Action would destroy a protection overlay.") (debug) (let* ((--cl-var-- snippets) (snippet nil)) (while (consp --cl-var--) (setq snippet (car --cl-var--)) (yas--commit-snippet snippet) (setq --cl-var-- (cdr --cl-var--))) nil))
>   (if (or yas--inhibit-overlay-hooks after\? (yas--undo-in-progress)) nil (let ((snippets (yas--snippets-at-point))) (yas--message 3 "Comitting snippets. Action would destroy a protection overlay.") (debug) (let* ((--cl-var-- snippets) (snippet nil)) (while (consp --cl-var--) (setq snippet (car --cl-var--)) (yas--commit-snippet snippet) (setq --cl-var-- (cdr --cl-var--))) nil)))
>   yas--on-protection-overlay-modification(#<overlay from 15 to 16 in test.h> nil 15 16)
>   remove-text-properties(15 16 (category nil))
>   c-parse-state()
>   c-where-wrt-brace-construct()
>   c-defun-name()
>   #[nil ... [c-cpp-define-name c-defun-name] 1]()
>   byte-code(... [add-log-current-defun-function result case-fold-search add-log-current-defun-header-regexp nil re-search-backward 10000 t match-string-no-properties 1 0 string-match "\\([^   \n
> \f].*[^     \n
> \f]\\)"] 4)
>   add-log-current-defun()
>   which-function()
>   byte-code(... [current window which-func-table which-function gethash puthash force-mode-line-update] 5)
>   which-func-update-1(#<window 3 on test.h>)
>   which-func-update()
>   apply(which-func-update nil)
>   byte-code(... [timer apply 5 6] 4)
>   timer-event-handler([t 0 0 500000 t which-func-update nil idle 0])
> Since this is triggered by timer, it might explain the discrepancy in observations. Also I notice add-log-current-defun, which reminds me of #666 <https://github.com/capitaomorte/yasnippet/issues/666>. @netjune <https://github.com/netjune>: does this look like the same problem as yours?
> 
Yes, I think so.
I just added the following code to my emacs init file, then the problem went away. I don't known why.

(add-hook 'c-mode-common-hook
		  (lambda ()
			;; = disable it becouse it breaks yasnippet
			(setq add-log-current-defun-function nil)))

**Comment by netjune** [comment]
> 在 2016年4月13日，08:13，Noam Postavsky <notifications@github.com> 写道：
> 
> @nicolasdespres <https://github.com/nicolasdespres> @netjune <https://github.com/netjune> please try out #678 <https://github.com/capitaomorte/yasnippet/pull/678> to see if it helps.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/capitaomorte/yasnippet/issues/677#issuecomment-209158900>
It works for me too. Thank you.

**Comment by nicolasdespres** [comment]
Bonjour capitaomorte/yasnippet,
Nicolas Desprès vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/CS8LKM/9cn/?hg=TnmuLewvU7 pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=e6aa6e53&email=reply@reply.github.com.&hg=TnmuLewvU7
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by nicolasdespres** [comment]
Bonjour capitaomorte/yasnippet,


Nicolas Desprès vous a laissé un message sur IQ Elite 


Cliquez ici a.iqelite.com/j/CS8LKM/9cn/?hg=WnMZhe7vB9 pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=e6aa6e53&email=reply@reply.github.com.&hg=WnMZhe7vB9
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------
