### ISSUE TITLE
Change default log level

### ISSUE THREAD

**Issue by wasamasa** [capitaomorte/yasnippet#682]
I'd like to propose a change of `yas-verbosity` to a level of 2.  Judging by the sources this catches nearly all warnings and errors (with the exception of `yas--safely-run-hooks`) while not bothering the user with debug messages.

Edit: https://github.com/capitaomorte/yasnippet/issues/224#issuecomment-4699919 suggests 2 should have been the default all along :D

**Comment by npostavs** [comment]
I'm thinking to adjust the levels a bit, and make 3 the default: #683.
