### ISSUE TITLE
[Emacs 25+,haskell-mode] Snippet with field breaks syntax-propertize

### ISSUE THREAD

**Issue by mrkkrp** [capitaomorte/yasnippet#687]
This perfectly valid snippet does not expand:

```
# -*- mode: snippet -*-
# contributor: Mark Karpov
# name: inline pragma
# key: inl
# expand-env: ((yas-indent-line 'fixed) (yas-wrap-around-region 'nil))
# --
{-# INLINE ${1:foo} #-}
$0
```

When I press <kbd>↹ Tab</kbd> after `inl` Emacs seemingly hangs, then after pressing <kbd>C-g</kbd> I see the following:

![bad-exp](https://cloud.githubusercontent.com/assets/8165792/14948994/446eaf26-1070-11e6-8ddf-208ff8e2c7f5.png)

Also note that syntax highliting in `snippet-mode` is broken:

![snippet-mode](https://cloud.githubusercontent.com/assets/8165792/14948999/4a4bda7c-1070-11e6-8389-1862a7e9a406.png)

----

I think it's a regression because a similar snippet (for language extensions) worked in the past. Now it does not work too.

**Comment by npostavs** [comment]
Doesn't happen in `*scratch*` with Emacs 24.5.  Which Emacs version and haskell mode are you using?

**Comment by npostavs** [comment]
Regarding the hightlighting, it's because the highlighting is based on regexps and can't handle the full syntax. We just hightlight every close brace: https://github.com/capitaomorte/yasnippet/blob/0.9.1/yasnippet.el#L885-L886

**Comment by mrkkrp** [comment]
Emacs 25 (master) and Haskell Mode from MELPA. I will try to reproduce in `emacs -Q`.

**Comment by mrkkrp** [comment]
I can reproduce this in `emacs -Q`.

**Comment by npostavs** [comment]
> Emacs 25 (master)

Can you try with 24.5 and/or the emacs-25 branch?

**Comment by fice-t** [comment]
It errors for me (only) on Emacs 25.0.93. It doesn't let me get a backtrace but after I `C-g` I get:
`Error during redisplay: (internal--syntax-propertize 119) signaled (quit)`. The number changes each time.

It also hangs like this with the built-in `prag` Haskell snippet.

**Comment by fice-t** [comment]
Oddly enough, if I define this snippet for `c-mode` and expand there, it works just fine.

**Comment by npostavs** [comment]
Hmm, seems to be some kind interaction with yasnippet field insertion with haskell-mode's syntax propertize function. And it only happens on Emacs 25+, so it could be a bug in emacs, yasnippet, or haskell-mode. :|

**Comment by npostavs** [comment]
I've opened haskell/haskell-mode#1315 which reproduces the effect without yasnippet.

**Comment by npostavs** [comment]
Reported as [Emacs bug #23443](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=23443)

**Comment by npostavs** [comment]
The conclusion from the Emacs bug discussion is that it's expected behaviour, see #695 for fix.
