### ISSUE TITLE
yas-reload-all causes yasnippet to stop working until restart of emacs

### ISSUE THREAD

**Issue by astoeckley** [capitaomorte/yasnippet#691]
When I call yas-reload-all using the mini-buffer, yasnippet no longer works, although "yas" continues to display in the mode line.

I was hoping to be able to edit snippets and try them out right away by reloading, but this isn't allowing me to do so.

I'm using the version currently on elpa, 0.9.1.

Is there anything I need to do that I'm not thinking of?

Thanks.

**Comment by npostavs** [comment]
How are you choosing the snippet files to edit? Are they located in `yas-snippet-dirs`? Can you post the output from `*Messages*`?

**Comment by astoeckley** [comment]
Ah thanks for this pointer. Something else was setting the dirs unexpectedly. Resolved now.

**Comment by npostavs** [comment]
Ok.

PS another way to try out snippets right away is `C-c C-l` in the snippet buffer to reload just that snippet immediately, or `C-c C-t` to try it out in a temp buffer without loading it.
