### ISSUE TITLE
How to associate custom snippets to a particular mode?

### ISSUE THREAD

**Issue by astoeckley** [capitaomorte/yasnippet#692]
The front page says this:

> Add your own snippets to ~/.emacs.d/snippets by placing files there or invoking yas-new-snippet.

For me, `yas-new-snippet` does not automatically save the file anywhere. I have to save it directly in emacs, as a normal file.

After they are saved to this directory, they are then not available on relaunch of emacs. How can I make them automatically get loaded either globally or for a particular mode?

The workaround would be for me to save them directly to one of the specific mode directories, but I'm trying to follow the front page's suggestion and save them in this general snippets dir.

I have this in my init.el:
```

(setq yas-snippet-dirs '(
                         "~/.emacs.d/snippets"
                         ))
```

**Comment by astoeckley** [comment]
Ah, I see they should be nested inside this directory with a directory name of the mode.

Got it.

**Comment by npostavs** [comment]
> For me, yas-new-snippet does not automatically save the file anywhere. I have to save it directly in emacs, as a normal file.

`C-c C-c` will load and save the snippet (and quit the window). Perhaps we should remap `C-x C-s` to do this also?

**Comment by astoeckley** [comment]
A lot of useful keymaps you've pointed out. You should list them all in one place the way bbatsov does:

https://github.com/bbatsov/projectile#interactive-commands

Or perhaps show me where I can find them all?

**Comment by capitaomorte** [comment]
> A lot of useful keymaps you've pointed out. You should list them all in one place the way bbatsov does:

Before bbatsov invented the webpage, there was also `C-h m` to describe the mode you're in, anywhere in Emacs. Also, the global menu "Snippet" lists all three: `C-c C-c` `C-c C-l` and `C-c C-t`. 

> Perhaps we should remap C-x C-s to do this also?

I don't know about remapping but something in the `after-save-hook` is probably in order. Or should it be `before-save-hook`? Still, it's probably complicated: what if the user is saving the file somewhere silly? Won't he be surprised to use the snippet in that session and then realize it was wrong in the next session where it won't be loaded?

Possibly a better idea is to include a comment in the new snippet template that says in very big letters: ```Use "C-c C-c" to load (and offer to save) this snippet```

**Comment by npostavs** [comment]
https://capitaomorte.github.io/yasnippet/snippet-development.html#sec-1 lists commands (and bindings for some of them), but it's out of date; seems I neglected to update it when adding `C-c C-l`.

> Possibly a better idea is to include a comment in the new snippet template that says in very big letters: Use "C-c C-c" to load (and offer to save) this snippet

Hmm, probably.

**Comment by npostavs** [comment]
Updated docs in #693.
