### ISSUE TITLE
programmatic (insert "foo") (yas-next-field) different to interactive

### ISSUE THREAD

**Issue by fommil** [capitaomorte/yasnippet#697]
We use yasnippet in ENSIME to expand dynamic templates for scala / java method completion.

It works really well, thank you!

However, I noticed a weirdness in our test suite where we do this (I added comments):

```elisp
	(ensime--yasnippet-complete-action (car (member "add" candidates))) ;; ultimately calls a yas-expand-template with the templates "a: Int" and "b: Int"
	(insert "2") (yas-next-field) ;; this is equivalent to the user typing "2" to fill out a method parameter input, then TABbing to the next
    (insert "3") (yas-next-field) ;; and again
```

at this point I expect the expanded text to look like `add(2, 3)`, and indeed this is what happens if I use ENSIME to expand such a method. But in our tests, the expanded text looks like `add(2a: Int, b: Int)` i.e. the templates are not being overwritten.

Am I doing something wrong in my tests or is this a difference in behaviour between interactive and noninteractive use?

**Comment by npostavs** [comment]
The decision about when to overwrite the field contents has been changed recently: #680. I think the new behaviour should support the noninteractive case better, but it's true that I didn't actually check it. Which yasnippet version are you using?

**Comment by npostavs** [comment]
```elisp
(progn
  (yas-expand-snippet "add (${1:a}: Int, ${2:b}: Int)")
  (insert "2") (yas-next-field)
  (insert "3") (yas-next-field))
```
gives `add (2: Int, 3: Int)` with the latest `master`: 0d79e6988ec371279fc1c23733c7371bd21927ee

**Comment by npostavs** [comment]
Oh and if you want to make the tests work with the 0.9.1 method as well, the yasnippet tests use
```elisp
(defun yas-mock-insert (string)
  (dotimes (i (length string))
    (let ((last-command-event (aref string i)))
      (ert-simulate-command '(self-insert-command 1)))))
```

**Comment by fommil** [comment]
cool! We're not using `ert` in these tests, but it might work.

**Comment by fommil** [comment]
thank you, this fixed it :smile:
