### ISSUE TITLE
yas/expand only if and only if abbrev and yas/trigger-key where typed in succession

### ISSUE THREAD

**Issue by capitaomorte** [capitaomorte/yasnippet#91]
<b>What steps will reproduce the problem?</b>
1. Install and activate yasnippet the usual way
2. open a file with a mode where yasnippet has a snippet key for
3. simply move point to a word boundary, where the word before point is a snippet key
4. press tab

<b>What is the expected output? What do you see instead?</b>
If I haven't even started typing, there shouldn't be any snippet expansion.

<b>What version of the product are you using? On what operating system?</b>
yasnippet 0.6.1.b, CarbonEmacs 22.3.1, on Mac OS X 10.5.8

Google Code Info:
Issue #: 89
Author: wyue...@gmail.com
Created On: 2009-09-01T00:23:33.000Z
Closed On:

**Comment by wentasah** [comment]
I was looking for a solution to this issue and setting `yas-expand-only-for-last-commands` to `(self-insert-command)` solves it for me. So this issue may probably be closed.

**Comment by capitaomorte** [comment]
@wentasah, as I said 4 years ago, it's not the original request, but it's good enough aparently, so marking a workaround and closing.
